### ISSUE TITLE
Inter-Planetary Travel

### ISSUE THREAD

**Issue by TDay1** [UQcsse3200/2023-studio-2#10]
# **Description**
**Task:** Inter-Planetary Travel.
**Feature:** [Space Feature](#3)

Implement the inter-planetary travel mechanism, allowing players to move between planets. This involves designing the logic for changing maps/views, updating the UI, and updating the game state as the player transitions between planets.

## **Example (optional)**
- **Part**: When players choose to travel from Planet A to Planet B, the inter-planetary travel mechanism should be used

# **Dependencies**
- [x] Global State Management system must be implemented (#5) for completion but much of the ticket can be implemented without it.
- [x] Planets class (Which haven't been implemented by the Map team so cannot create JUnit Test at this moment)
- [x] Minigames
# **Milestones**
- [x] Design the inter-planetary travel mechanics and update the wiki documentation (Aug. 19).
- [x] Implement the logic for transitioning between planets (Aug. 20).
- [x] Integrate the travel mechanism with the specified minigames spawn at each state, determine whether the minigames are finished or not (Aug. 23).
- [x] Test inter-planetary travel for accuracy and functionality (Aug. 23).

**Completion Deadline:** Aug. 23

# **Documentation**
- TBD

# **Member**
- TBD
