### ISSUE TITLE
Companion Design and Implementation 

### ISSUE THREAD

**Issue by JivalX** [UQcsse3200/2023-studio-2#107]
# **Description**
**Task:** [Design and Implementation of Dr. Emily Carter](#3).
**Feature:** [Companion Character Design and Integration](#2)

This ticket involves the design and creation of the companion character, Dr. Emily Carter, based on the story requirements. Dr. Carter will play a crucial role in the game, accompanying the main character on their journey through space. The companion character's design would align with the narrative and add depth to the storytelling. This includes defining her appearance, traits and interactions with the main character.
 
## **Example (optional)**
- **Story benefits**: Emily Carter is a crucial component of the game that will affect the story line of the game as it moves forward.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Define Dr. Emily Carter's Appearance and Traits (Aug. 26).
- [x] Create Dr. Emily Carter's character (Aug. 27).
- [x] Alter the story line to pragmatically preview Emily Carter's character in it. (Aug 30).
 
**Completion Deadline:** Aug.31

 
# **Member**
- Jival @JivalX (jival.x)
- Yash @YashMitttal (master_yashh)
- Rachit @rachitchaurasia (rachitchaurasia)
- Dev @DRG31 (_xdrgx)
- Aniket @aniketgupta17 (aniketgupta_41819)
- Maxwell (MaxwellSchroder) (@Magwell)
- Saakshi Gupta (saakshigupta2002) (@saakshigupta)
- Atharva Gupta (atharvagupta2003) (@atharva0179)
- Daksh Jain (Daksh2607) (@daksh_52443)
- Raghavendra Singh Gulia (RagGul)(tantrik8119)
- Gaurika Diwan(gaurikadiwan)(@gaurikadiwan_03168)
