### ISSUE TITLE
Integrate Spatial Components

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#117]
# **Description**
**Task:** Integrate Space
**Feature:** [Space Feature](#3 )

Integrate the Space Map buttons with existing inter-planetary travel code to ensure the game state is appropriately updated, and the transition to the selected planet is facilitated and the game area is loaded.   

**Note:** As of current the space minigame cannot be won, so it is skipped temporarily.
 
# **Dependencies**
- [x] The current planet must be loaded into the `GameState` to be accessed and created from (#125 ).
- [x] The transition screens for beginning and ending sequences must be implemented.
- [x] The mini-game integration must be finalised.

# **Milestones**
- [x] Refactor the current SpaceMap to begin the transition state. (Sep. 9)
- [x] Accept the transition request from the map and begin the sequence. (Sep. 11)
- [x] Begin the transitionary sequence and display the screen to the user. (Sep. 10)
- [x] Display the ending transitionary screen to the user. (Sep. 10)
- [x] Get the next planet to transition to. (Sep. 11)
- [x] Update the `GameState` of transition. (Sep. 11)
- [x] Transition to the target planet and create its GameArea.  (Sep. 13)
 
**Completion Deadline:** Sep. 13
 
# **Documentation**
[Planet Transition](https://github.com/UQcsse3200/2023-studio-2/wiki/Planet-Transition) 

# **Member**
- Henry Batt @henrybatt
