### ISSUE TITLE
Turrets

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#118]
# **Description**
For this feature we will be implementing turrets into the game. They will target enemies within the game world and fire projectiles at them. They will have a 'vision' radius around them and when an enemy enters a turrets vision it will turn to face the enemy and fire. For this we will use the `ProximityActivationComponent`. As an extension to this feature, if time permits, we will add an ammunition system which will be consumed when firing and will need refilling manually by the player. This adds more dynamic gameplay to the feature wherein players can't just set up turrets and forget about an extractor. Instead, they will be forced to go between each site to ensure their defenses are well maintained.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.

# **Dependencies**
- [x] [Proximity activation component](../wiki/proximity-activation-component)
- [x] [Enemy targeting system](#88) 
- [x] [Health bar component](../wiki/health-bar-component)
- [x] [Extractor resources](#50)
- [x] Inventory system

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #148
- [x] #154 (Sept 9)
- [x] #163 
- [x] #185  (Sept 9)
- [x] #150 (Sept 11)
- [x] #206 

**Completion Deadline:** Sep. 13

# **Extras (optional)**
- [ ] Different turret varieties (laser, fire, etc.)
- [x] Limited ammunition. Needs filling.
- [ ] Ammunition crate
- [ ] Scanning animations

# **Documentation**
- [Test Plan](https://github.com/UQcsse3200/2023-studio-2/wiki/Buildables-Team-Sprint-2-Test-Plan)
- [PlaceableEntity](https://github.com/UQcsse3200/2023-studio-2/wiki/PlaceableEntity)
- [Turret](https://github.com/UQcsse3200/2023-studio-2/wiki/Turret-(Game-Entity))
- Components
   - [FOV Component](https://github.com/UQcsse3200/2023-studio-2/wiki/FOV-Component)
   - [CostComponent](https://github.com/UQcsse3200/2023-studio-2/wiki/CostComponent)
- [StructureToolPicker](https://github.com/UQcsse3200/2023-studio-2/wiki/StructureToolPicker)
- [Tool](https://github.com/UQcsse3200/2023-studio-2/wiki/Tool)

# **Members**
Rowan (@rowan-gray) (Rowan Gray)
Yuvraj (@yuvrajsingh001) (Yuvraj Singh)
Khushi (@khushijain0302) (Khushi Jain)
Raghav (@NotRaghavAggarwal) (Raghav Aggarwal)
Yugansh (@Yugansh-Uq) (Yugansh Pancholi)

**Comment by khushijain0302** [comment]
Implement Ammunition System for Turrets  #206

**Comment by rowan-gray** [comment]
Completed yay
