### ISSUE TITLE
Ships & Extractors UI Task Ticket

### ISSUE THREAD

**Issue by mira-alford** [UQcsse3200/2023-studio-2#120]
# **Description**
**Task:** [Task Name](#3).
**Feature:** #160 

Description:
This task focuses on the various UI elements of the ship and extractor feature. This includes having indicators on the edge of the screen to inform the player of the locations of extractors. Adding extractor lights (indicating how many extractors are on a resource) the the resource bar and potentially generalising the resource bars to be used by other teams. Adding an indicator that ticks up on extractors to show what they are producing, when they produce it. And adding an indicator popup for interaction with nearby entities with the interaction component.

# **Dependencies**
TBD (Probably none)
- [x] Dependency 1 (#xx)
 
# **Milestones**
- [x] Finishing Extractor Resource Bars (Simple) (Sept. 3)
- [x] Interaction Popup (Text) (Sept. 3)
- [x] Interaction Popup (Fancy, Extra) (Sept. 10)
- [x] Extractors have a popup as they tick, showing their resource produced
- [x] Interaction Popup Documentation (Sept. 12)
 
**Extras**:
- [ ] Extractor Location Indicators Sprited (Sept. 5)
- [ ] Extractor Location Indicators (Sept. 10)
- [ ] Extractor Location Indicators Unit Tested & Docced (Sept. 12)

**Completion Deadline:** Sept. 14
 
# **Documentation**
- [Popups](https://github.com/UQcsse3200/2023-studio-2/wiki/Popup-Component)
-  [Resources](https://github.com/UQcsse3200/2023-studio-2/wiki/Resources)
# **Member**
- McArthur Alford (@McArthur-Alford) (Discord: McArthur)
-
