### ISSUE TITLE
Upgrade Tree

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#121]
# **Description**
The Upgrade Tree will be a fundamental part of upgrading things within the game. This will initially extend to upgrade weapons and a building hammer (to place or upgrade to stronger walls) but could include things like ship or extractor upgrades in the future. Upgrade purchases can be made with extracted ship resources and depend on the specific upgrade. See the [wiki page](https://github.com/UQcsse3200/2023-studio-2/wiki/UpgradeTree) for initial concept design.

# **SubFeatures/components**
- [x] [Improved Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/144)
- [x] [Upgrade Tree Structure](https://github.com/UQcsse3200/2023-studio-2/issues/132)
- [x] [Upgrade Tree GUI](https://github.com/UQcsse3200/2023-studio-2/issues/145)

# **Dependencies**
- [Ship Extractors](): In order to upgrade items the ship resource extractors must be present.
- [Improved Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/144): In order to upgrade weapons, we must have additional or upgraded weapons

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
TBD
- [x] (Sep. 3) - Upgrade Tree Design completed.
- [x] (Sep. 7) - Upgrade Tree Structure completed, & Existing weapons code refurbished.
- [x] (Sep. 11) - Weapon verity and usability improved. 
- [x] (Sep. 14) - Upgrade Tree GUI completed.

**Completion Deadline:** Sep. 14

# **Optional**
- Collaborate with **Team 7** team to place/upgrade stronger walls given the hammer has been upgraded within the upgrade tree.

# **Documentation**
- [Upgrade Trees](https://github.com/UQcsse3200/2023-studio-2/wiki/Upgrade-Tree)
- [Weapons](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)

# **Members**
Connor Golin (@connor-golin)
Daniel van Niekerk(@Daniel-vanNiekerk0)
