### ISSUE TITLE
Improved Player Feature

### ISSUE THREAD

**Issue by racheljadel** [UQcsse3200/2023-studio-2#122]
# **Description**
This feature aims to establish improved player appearance and animations, player inventory, improved player stats HUD and a player death event. These features are necessary to progress the player feature to a completed game mechanic.

## SubFeatures/components
**Improved Player Animations**
- Improve player sprite appearance
- Implement walking and dodging animations to player movement

**Upgraded Player Stats HUD**
- Create dodge cooldown bar to indicate cooldown time
- Improve player health UI
- Display current powerups in HUD
- Player ammunition count displayed in HUD

**Player Death**
- Design and implement player death screen which appears when player’s health reaches 0.
- Design and implement player death animation.
- Create player death event which returns user to the main menu screen or allows user to respawn.

**Player Inventory**
- Player can swap between builadables and weapons.

# **Dependencies**
The required dependencies for this feature are:
- Ammunition implementation in weapons feature

The potential dependencies for this feature are:
- The GameState team (player death, ending game)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

- [x] [Improved Player Animations](https://github.com/UQcsse3200/2023-studio-2/issues/146) (Sep. 10)
- [x] [Upgraded Player Stats HUD](https://github.com/UQcsse3200/2023-studio-2/issues/143) (Sep. 10)
- [x] [Player Death](https://github.com/UQcsse3200/2023-studio-2/issues/151) (Sep. 10)
- [x] [Player Inventory](https://github.com/UQcsse3200/2023-studio-2/issues/159) (Sep. 10)

**Completion Deadline:** (Sep. 12)

# **Extras (optional)**
- [ ] Add a pause button
- [ ] Adding multiple player skin options
- [ ] Multiple lives
- [ ] Show indication of low player health on player sprite

# **Documentation**
To be completed.

# **Members**
Aman Gupta (@aman-86) (Aman Gupta)
Damian Bellew (@Dammo3) (Damian Bellew)
Rachel Leathers (@racheljadel) (Rachel Leathers)
Kushagra Agrawal (@kushagra1912) (Kushagra Agrawal)
