### ISSUE TITLE
Ship and Extractors Mechanical Task 

### ISSUE THREAD

**Issue by Div1o1** [UQcsse3200/2023-studio-2#123]
# **Mechanical Tasks**
**Feature:**  #160 

This "mechanical ticket"  encompasses several tasks for implementing the mechanical functionality of extractors, extractor placement zones, UI associated to extract different types of resources, config file defining the player spawn point and resource limit to complete the level.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- Repair Minigame needs to be pushed to main
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Config File - Extraction production rate , Resource Limit, Level win conditions (Sept.  8)
- [x] Config File Testing and documentation (Sept. 10)
- [ ] Extractor Repair Minigame Testing (Sept. 12)
- [x] Extractor Placement UI. (Sept. 8)
- [x] Extractor Placement UI documentation and Wiki. (Sept. 8)
- [x] Implement Extractor Placing and update UI (Sept. 12)
- [x] Resource production rate balancing (Sept. 12)
 
**Completion Deadline:**  Sept. 12 - Tuesday 

# **Extras**
List of steps that could be added for this task.
- [x] Config File - Player Spawn, Ship Spawn
- [ ] Extractor Zones on the map

# **Documentation**
- [Configuration Files](../wiki/Creating-Entities-with-Configuration-Files)
- [Extractor Placement UI](https://github.com/UQcsse3200/2023-studio-2/wiki/Extractor-Placement-UI)
 
# **Member**
- Name (GitHub Username) (Discord Handle)
- Isaac (@Minirobbo) (Minirobbo)
- Divyanshu (@Div1o1) (Div1o1)

**Comment by Minirobbo** [comment]
Config file now encapsulates the entire level area. Each level uses the same base code but has a config file to customise each level. This also reduces code duplication for new levels

**Comment by Minirobbo** [comment]
Note that the config file tasks have now been encapsulated into a much bigger task #184. Deadlines wont be accurate anymore - all due on the 12th
