### ISSUE TITLE
Planet Decorator

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#124]
# Ticket Merged with (#125 )

-------------------------------------------------

# **Description**
**Task:** Planet Decorator.
**Feature:** [Space Transition](#126 )

Create a Planet decorator to encapsulate the `GameArea` for each planet with additional attributes such as planet name. This is the type for storage of all the planets into the `GameState`.

# **Dependencies**
- [x] Common `GameArea` that all planets inherit from must be designed to apply decorator around. To be implemented in collaboration with the Map Team. (#184 )

# **Milestones**
- [ ] Construct decorator framework. (Sep. 8)
- [ ] Add additional planet attributes as required. (Sep. 9)
- [ ] Write documentation on how the decorator framework behaves. (Sep. 9)
 
**Completion Deadline:** Sep. 9
 
# **Documentation**
*To be completed*
 
# **Member**
- Henry Batt @henrybatt

**Comment by henrybatt** [comment]
Merged with Planet Creation. Utilising screens to allow multi-gamearea planets.
