### ISSUE TITLE
Planet Creation

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#125]
# **Description**
**Task:** Planet Creation.
**Feature:** [Space Transition](#126 )

Create all of the GameAreas for the planets and apply their decorators before storing them in the `GameState` for access throughout the game.

Safely create the GameAreas for each Planet, apply attribute decorator, modify `GameStateObserver` to handle planets, and then store all Planets.

# **Dependencies**
- [x] The common GameArea from which all planet's game areas inherit must be designed. (#184 )

# **Milestones**
- [x] Construct planet screen framework. (Sep. 7)
- [x] Implement existing behaviour for each planet's screen behaviour (Based on MainGameScreen). (Sep. 8)
- [x] Implement the next planet in chain generation for traversing sequence. (Sep. 9)
- [x] Modify `GameStateObserver` to allow storing of the current planet. (Sep. 10)
- [x] Create the code framework to change the screen to the current planet. (Sep. 11)
- [x] Refactor code to utilise new screens in screen changes, and transitions. (Sep. 12)
- [x] Write documentation on planet screens. (Sep. 13)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
[Planet Screens](https://github.com/UQcsse3200/2023-studio-2/wiki/Planet-Screens)
 
# **Member**
- Henry Batt @henrybatt
