### ISSUE TITLE
Space Transition

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#126]
# **Description**
For this feature, we will be focusing on the visual UI elements of the planetary transitions. The goal is to make the transitionary period between planets as visually appealing as possible and add animations/details between game areas. The minigames to be played between planets will also be implemented, and the packaging of each planet's game area to be stored in the game state.

# **Dependencies**
- [x] Mini games must be designed for implementation (#8 )

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Design & implement a transition screen for beginning planetary travel. (Sep. 10)
- [x] Design & implement a transition screen for ending planetary travel. (Sep. 10)
- [x] Redesign the Space Map with enhanced visual appeal. (Sep. 9)
- [x] Implement mini-games into the transitionary period. (Sep. 11)
- [x] Integrate Space Map, transitionary code, and visual screens. (Sep. 13) (#117 )
- [x] Create the planet screens to display. (Sep. 12) (#125 )
- [x] Create the transition sequence and store the current planet into `GameState`. (Sep. 13) (#125 )

**Completion Deadline:** Sep. 13

# Extras (Optional)
* Lock planet travel behind checkpoints/milestones.
* Create multiple different transition scenes for variation.

# **Documentation**
[Planet Transition](https://github.com/UQcsse3200/2023-studio-2/wiki/Planet-Transition) 

# **Members**
- Thomas Day TDay1 tday1
- Henry Batt @henrybatt
- Shaivika Anand (shaivikaaaa) (shaivika21)
- Manandeep Singh (24msingh24) (manan0267)
- Vu Khanh Vy Ho (VuKhanhVyHo)

**Comment by henrybatt** [comment]
Please note that as of this moment, the minigame to transition between planets cannot be won and as such has been temporarily skipped as to ensure that you can still transition between planets
