### ISSUE TITLE
Small enemy enhancements and Boss enemy mechanics  (Sep. 13)

### ISSUE THREAD

**Issue by kk4w4i** [UQcsse3200/2023-studio-2#129]
# **Description**
This task focuses on enhancing the enemy mechanics by implementing item drops, completing the development of one boss enemy with a special attack and full animation, figuring out the delays for enemy death animations, and investigating scaling options for different enemy types.
 
# **Dependency** 
Some collaboration with the space team, map team and design committee.
 
# **Documentation**
TBD
 
# **Milestone**
- [x] Determine and implement delays for enemy death animations (Sept 8th)
- [x] implement item drop mechanics for enemies (Sept 8th)
- [x] Investigate and propose scaling options for different enemy types (Sept 8th)
- [x] Complete one boss enemy with one special attack and full animation (Sept 12th)
- [x] Junit tests (Sept 13th)
 
# **Members**
Firstname Surname (@github) (Discord Handle)
- Theodore Kim (@thoemodachi) (thoemodachi)
- Ojaswin Kohli (@OjaswinKohli) (ojaswinkohli)
- Aryaman (@Aryamant21) (at007)
