### ISSUE TITLE
Player Feature

### ISSUE THREAD

**Issue by racheljadel** [UQcsse3200/2023-studio-2#13]
# **Description**
This feature aims to establish core player movement mechanics, foundational statistics, initial weapon capabilities, basic player visuals, and fundamental power-ups. These elements are designed to provide players with core functionality that they will experience at the start of the game.

## SubFeatures/components
**Base Player Movement**
- Implement 8-Directional player movement for the Player.
- Integrate a dodge feature, enabling the player to execute a swift directional move granting a short-term immunity.

**Base Assets**
- Create player sprites for each movement direction.
- Design the base weapon: a baseball bat.
- Conceptualize and design the initial power-up.

**Base Weapon/Attack**
- Implement the base weapon: a baseball bat.
- Establish weapon attributes: Damage, Cooldown/Reload time, Knockback effects.
- Incorporate an attack button for player interaction.

**Base Player Statistics**
- Implement tracking for player health and immunity status.
- Implement a Player state variable to keep track of actions - eg. interacting, dodging, shooting, and player's facing direction.

**Base Powerups**
- Design and implement the primary class for power-ups.
- Introduce a movement power-up that increases the player's speed.
- Initially set the power-up to spawn at a random location on the map, with potential future integration by the mini-game team.

# **Dependencies**
The required dependencies for this feature are:
- The provided game engine

The potential dependencies for this feature are:
- The Enemy team (Player-Enemy collisions)
- The Map team (Player spawning)
- The Minigame team (Powerups spawning)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] [Base Movement](https://github.com/UQcsse3200/2023-studio-2/issues/25) (Aug. 24)
- [x] [Base Player Statistics](https://github.com/UQcsse3200/2023-studio-2/issues/45) (Aug. 26)
- [x] [Base Powerups](https://github.com/UQcsse3200/2023-studio-2/issues/20) (Aug. 28)
- [x] [Base Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/35) (Aug. 28)
- [x] [Base Assets](https://github.com/UQcsse3200/2023-studio-2/issues/32) (Player, Weapon(s), Powerup(s)) (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Add walking animations for the player.
- [ ] Design and integrate a secondary weapon and its upgrade mechanics.
- [ ] Craft GUI elements: Player's health, stamina, and ammo indicators.
- [ ] Introduce player armour mechanics.
- [ ] Add extra power-ups for the player.
- [ ] Create animations for the new player power-ups.

# **Documentation**
To be completed.

# **Members**
Aman Gupta (@aman-86) (Aman Gupta)
Connor Golin (@connor-golin) (Connor Golin)
Daniel van Niekerk (@Daniel-vanNiekerk0) (Daniel van Niekerk)
Damian Bellew (@Dammo3) (Damian Bellew)
Rachel Leathers (@racheljadel) (Rachel Leathers)
Kushagra Agrawal (@kushagra1912) (Kushagra Agrawal)
