### ISSUE TITLE
Additional animations and adjustments to animations (Sep. 13)

### ISSUE THREAD

**Issue by kk4w4i** [UQcsse3200/2023-studio-2#131]
# **Description**
Aim to fine tune animations for enemy objects by smoothing out the transition across different playback loops. Fix issue that is causing glitching to death animation. Ultimately we want to make the enemy more realistic and adaptive with the current game. Hence we can also make the enemy behaviour more unpredictable, varied their actions in game.

# **Dependency** 
Art visual design team

# **Documentation**
TBA

# **Milestone**
- [x] Bidirectional chasing for 2 enemies (Sep 8)
- [x] Fix death animation glitch(Sep 8)
- [x] Implement facing direction (Sep 8)
- [x] Make change trolls design to match with theme(Sep 13)
- [x] Modified wandertask   (Sep 13)

# **Extras**
- [x] Make extra sprites   

# **Members**
- Trong Vuong (@samv26) (samv_v)
