### ISSUE TITLE
Upgrade Tree Structure

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#132]
# **Description**
**Task:** [Upgrade Tree Structure](https://github.com/UQcsse3200/2023-studio-2/issues/new?assignees=&labels=task&projects=&template=task-ticket.md&title=).
**Feature:** [Upgrade Trees](https://github.com/UQcsse3200/2023-studio-2/issues/121)

This task ticket aims to implement the back end of the Upgrade Tree, which includes handling weapon/hammer upgrades and their associated data structures.

# **Dependencies**

- [x] [Improved Weapons]() - required in order to upgrade weapons
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] (Sep. 2) - Upgrade tree designed and documented in wiki.
- [x] (Sep. 4) - Data structures implemented.
- [x] (Sep. 7) - Upgrade Tree Structure tested and wiki updated.
- [x] (Sep. 9) - Upgrade resource cost integrated with extractor resources. 
- [x] (Sep. 9) - Building hammer level integrated with Structure picker level.
- [x] (Sep. 13) - Testing and wiki documentation finalised.
 
**Completion Deadline:** Sep. 7
 
# **Documentation**
- [Upgrade Trees wiki page]()
 
# **Member**
Connor Golin (@connor-golin)
