### ISSUE TITLE
Ship and Extractors Visual Updates

### ISSUE THREAD

**Issue by neil-nb** [UQcsse3200/2023-studio-2#133]
# **Description**
**Task:** [Ship and Extractors Visual Updates](#3).
**Feature:** #160 

Fixing the visual aspects of the ship and extractors such as the refining of sprites and the creation of animations for both the ship and the extractors. This includes an animation for the blasting off of the ship at the end of the level. Time permitting, it is also a goal to make the extractors deployable by the player, outside of a given radius of another extractor. This deployment would be an animated orbital drop.

 # **Dependencies**
- [x] The selection menu for the placing of the extractors must first be finalized before animating the extractors' descent from space can begin 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Developing ship sprite (Sept. 5)
- [x] Remaking extractor sprite (Sept. 5)
- [x] Remaking broken extractor sprite (Sept. 6)
- [x] Making frames of extractor animation (Sept. 8)
- [x] Adding animation to extractors to 
       indicate use/resource type (Sept. 13)
- [x] Ship blast-off animation (Sep. 13)
- [x] (Extra) Deployment of the extractors by the player
       This includes the potential animation of orbital drop (Sep. 14)
 - [x] Updates to the ship and extractors documented on wiki (Sep. 12)
    
# **Documentation**
- [Ship and Extractors](https://github.com/UQcsse3200/2023-studio-2/wiki/Ship-and-Extractors)
 
# **Member**
- Neil Barigye, Discord: NickBattle1#9383  Github: @neil-nb
- Tarushi, Discord: tarushigera Github: Tarushi263
