### ISSUE TITLE
Improving Core Companion Feature

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#135]
# **Description**
This feature ticket in sprint 2 will finalise the core components and functionality that will make the companion whole. It will polish off the movement and look of the companion. 
The companion will be able to provide useful alerts, and go into different modes like attack or defend depending on what the player wants. Furthermore, the companion will be playable depending on the game mode chosen.

## SubFeature/component (optional)
- (#136 )t: Fix the current movement to be smooth. Should be visually appealing. Fix the current bug of pushing the player and phasing through some walls
- (#137 ): Make the companion animated, changing its view and skin depending on which direction it is going. Furthermore, adding some basic animations for 'strike' and 'sprint' effects would be nice
- (#225): Create and design a Death Screen for companion.
-(#140 ): Add in different kind of pre-set modes the companion can be in, such as 'normal/passive', 'attack' ,'defect' etc. Allow the modes to be activatable by key press initially, and then by game state and player interaction
- (#141): The companion pops up useful alerts above itself to show important game state information. it should be callable by anything in the game state.

# **Dependencies**
None

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Sep. 8) Updated companion movement to be autonomous
- [ ] Goal 2 (Sep. 11) Allow 1 or 2 player option in the main menu
- [ ] Goal 3 (Sep. X) Get animated movement/direction finished.
- [ ] Goal 4 (Sep. X) Different types of companion modes finished

**Completion Deadline:** Thursday 3pm Sep 15.

# **Extras (optional)**
- [] Health boost: Allow the player to have some ability to improve the health status of the companion.  

# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion

# **Members**
- Name (GitHub Username) (Discord Handle) -- only one is needed if they are the same.
- Maxwell (MaxwellSchroder) (@Magwell)
- Saakshi Gupta (saakshigupta2002) (@saakshigupta)
- Atharva Gupta (atharvagupta2003) (@atharva0179)
- Daksh Jain (Daksh2607) (@daksh_52443)
- Raghavendra Singh Gulia (RagGul)(tantrik8119)
- Gaurika Diwan(gaurikadiwan)(@gaurikadiwan_03168)
