### ISSUE TITLE
Companion Improved Movement

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#136]
# **Description**
Task: (#136)
Feature: (#135)

The companion should be able to move around the player in a seemingly autonomous fashion. it should avoid objects, and constantly move.

## SubFeature/component (optional)
None

## **Examples (optional)**
- **1 or 2 player**: If the player selects 2 player, this autonomous movement will not be in effect. However, the movement will be implemented first.
- Example: The companion will come within a maximum radius but not get so close to the player, breaking a set minimum radius

# **Dependencies**
None, but later on will rely on the 1/2 player option ticket

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 2 (Sep. 7) Improve the gravity between the player and the companion
- [ ] Goal 3 (Sep 8. ) Smooth out the movement patterns, and stop the companion phasing through wall or pushing the player
- [ ] Goal 4 (Sep. 8) Push the completed functionality into main.

**Completion Deadline:** Sep. 8

# **Documentation**
General companion documentation: [Companion](https://github.com/UQcsse3200/2023-studio-2/wiki/Companion)

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Maxwell (MaxwellSchroder) (@MaxwellSchroder )
- Atharva Gupta (atharvagupta2003) (@atharva0179)

**Comment by MaxwellSchroder** [comment]
We are going to implement this later, in sprint 3
