### ISSUE TITLE
Companion 1 or 2 player button

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#138]
# **Description**
Task: (#138)
Feature: (#135)

This button should adjust the companion to be in autonomous mode, or in playable mode.
 
## **Example (optional)**
- **2 player mode** You essentially have different controls, but it operates exactly how the player works
- **Single player mode** The companion is autonomous, and autonomously moves and interacts with the world

# **Dependencies**
- [Companion autonomous movement](#136 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Sep. 9) Get button on the menu page for 1 or 2 player options
- [ ] Step 2 (Sep. 10) Refactor parts of codebase to work autonomously or controlled
- [ ] Step 3 (Sep. 11) Link the buttons to different companion functionality
- [ ] Step 4 (Sep. 11) Push to main
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
General companion documentation: [Companion](https://github.com/UQcsse3200/2023-studio-2/wiki/Companion)

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Maxwell (MaxwellSchroder) (@MaxwellSchroder )
