### ISSUE TITLE
Elevate Game Introduction for Next Planet's Narrative and add new Game-Over and Completion Screens

### ISSUE THREAD

**Issue by YashMitttal** [UQcsse3200/2023-studio-2#139]
# **Description**
**Task:** Enhance the game's introductory sequence and prepare it for the next planet's storyline.

**Feature:** Introduction and initial progression

In this task, we will be working on extending the game's introduction sequence and preparing it to continue the storyline on the next planet. This includes designing and implementing captivating visual and narrative elements to engage players and set the stage for the upcoming gameplay.

## Example 
- **Introduction Enhancement**: Expand the existing introduction sequence by introducing new visual assets, dialogues, and transitions to immerse players in the game's world.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Storyline Extension
- [x] Expand the introduction with new visual assets
- [x] Visual enhancements for the next planet
- [x] Add Game-Over Screen
- [x] Add Level-Completion Screen
- [x] Main Menu Screen Overhaul
- [x] Implement additional dialogues and narrative elements
- [x]  Controls Screen Creation

**Completion Deadline:** September 14

# **Documentation**
- https://github.com/UQcsse3200/2023-studio-2/wiki/STORY-SCREEN-DOCUMENTATION
- https://github.com/UQcsse3200/2023-studio-2/wiki/Story-Display-using-Initial-Screen
- https://github.com/UQcsse3200/2023-studio-2/wiki/Controls-Screen
- https://github.com/UQcsse3200/2023-studio-2/wiki/MAIN-MENU-AND-SETTING-MENU-DISPLAY-CHANGES

# **Members**

- Yash Mittal (@YashMitttal} (s4823869)
- Aniket Gupta (@aniketgupta17) (s4824063)
- Jival Kapoor (@JivalX) (s4824576)
