### ISSUE TITLE
Placing & picking up wall

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#14]
# **Description**
**Task:** [Player can place a wall object].
**Feature:** [Barricades/Wall](#6 )

In this subfeature, players will be able to strategically place wall objects within the game world. These wall objects serve as barricades to prevent enemies from advancing and damaging critical structures like the Ship/Extractor. This feature enhances gameplay by allowing players to create defensive barriers and control enemy movement.

# **Dependencies**
Implement wall ticket()
Wall Sprite (#9)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Listening for a click (Aug. 26)
- [x] Calculating which tile player clicked on (Aug. 26)
- [x] Spawning the wall object where the player clicked (Aug. 27)
- [x]  Pickup up walls when the player right clicks (Aug. 28)
- [x] Add documentation(Aug 28)
 
**Completion Deadline:** Aug. 28

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub [khushijain0302](https://github.com/khushijain0302))

**Comment by rowan-gray** [comment]
Completed.
