### ISSUE TITLE
Companion Modes

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#140]
# **Description**
Task: (#138)
Feature: (#135)
Add in different types of general modes for the companion to be in, such as attack or defend. Something should visually change when it is in a different mode, and it should behave differently.

 
## **Example (optional)**
- **Attack** The companion is actively seeking the closest enemies and going up or trying to kill them
- **Defend** the companions main objective is to heal and protect the player

# **Dependencies**
None
- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)

 
# **Milestones**
List of steps that need to be completed for this task.
Something like Define the modes we want, create a general class to invoke the changes, link the general changing to the companion, link keyboard input to the companion, add timers.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
General companion documentation: [Companion](https://github.com/UQcsse3200/2023-studio-2/wiki/Companion)
 
# **Member**
- Name (GitHub Username) (Slack Handle)

**Comment by MaxwellSchroder** [comment]
This ticket has been updated into a new ticket format #168
