### ISSUE TITLE
Adding properties to terrains

### ISSUE THREAD

**Issue by zombiechook** [UQcsse3200/2023-studio-2#142]
### Description
The focus of this issue is to add special properties to the ground textures that change how the game functions in some way. For example, a texture for mud would have a property that slows the player down when they walk over it

### Milestones

- [x]  Goal 1 (Sep. 6) Define custom properties in Tiled
- [x]  Goal 2 (Sep. 11) Implement speed modification
- [x]  Goal 3 (Sep. 13) Finalise code, push to main

- [ ]  Bonus - One-way collision boxes for certain tiles

Completion Deadline: August 31st
### Members
- Mitchell Hall (@s4697858 ) (Mitchell Hall)
