### ISSUE TITLE
GUI Component Implementation For Player

### ISSUE THREAD

**Issue by aman-86** [UQcsse3200/2023-studio-2#143]
# **Description**
**Task:** Gui Component Design For Player
**Feature:** [Improved player Feature](https://github.com/UQcsse3200/2023-studio-2/issues/122)

The task is meant to design GUI component for player. this will include the following component such as  - player Health Bar, Player's Dodge Bar Cool-down, Displaying Power-ups.

# **Dependencies**
May need help of extractor's team. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 - Displaying power-ups(Sep. 4)
- [x] Step 2 - Implementing Player Health GUI Component(Sep. 6)
- [x] Step 3 - Implementing Player's Dodge Bar Cooldown(Sep. 12)
- [x] step 4 - jUnit testing(Sep. 13)  
- [x] step 5 - Update java Doc(Sep. 12) 
- [x] step 6 - update Wiki
 
**Completion Deadline:** Sep 14
 
# **Documentation**

TBA
 
# **Member**
- (@aman-86)(Aman Gupta)
