### ISSUE TITLE
Improved Weapons

### ISSUE THREAD

**Issue by Daniel-vanNiekerk0** [UQcsse3200/2023-studio-2#144]
# **Description**
**Task:** Improved Weapons
**Feature:** [Upgrade Trees](https://github.com/UQcsse3200/2023-studio-2/issues/121)

Improved Weapons will be an extension of [Weapons 1](https://github.com/UQcsse3200/2023-studio-2/issues/35). Weapons 2 aims to make the implementation of weapons more functional and diverse. This task aims to improve on how weapons look by improving animations, and how weapons are used through key binds, weapons stats (ammunition and use cooldowns) and weapon equitability (working with (@kushagra1912) task ticket). Additionally it will expand upon weapon availability by introducing more weapons and having them accessible through the upgrade tree.

# **Dependencies**
- [Upgrade Tree Structure](https://github.com/UQcsse3200/2023-studio-2/issues/132) In order to be implemented into the upgrade tree
- [Player Inventory](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Inventory#159)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Restructuring of weapons code to make use of config files (Aug. 4)
- [x] Better Animations (Aug. 6)
- [x] Weapon Stats and prototype swapping capability (Sep. 8)
- [x] More Weapons (Sep. 11)
- [x] Bug Fixing Code (Sep. 12)
- [x] Manual Testing for Weapons (Sep. 13)
 
**Completion Deadline:** Sep. 14

# **Documentation**
- [Weapon Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)
 
# **Member**
- Daniel van Niekerk(@Daniel-vanNiekerk0) (Daniel van Niekerk)
