### ISSUE TITLE
Upgrade Tree GUI

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#145]
# **Description**
**Task:** [Upgrade Tree GUI](#3).
**Feature:** [Upgrade Trees](https://github.com/UQcsse3200/2023-studio-2/issues/121)

The aim of this ticket is to implement the Graphical User Interface relating to Upgrade Trees. The user will be able to access the weapon tree through an Interactable or through a button on screen. They will be able to see future weapons/hammer upgrades and their associated cost.

# **Dependencies**

- [Upgrade Tree Structure](https://github.com/UQcsse3200/2023-studio-2/issues/132): The Upgrade Tree's structure must be present in order to create a user interface for it.
- [Improved Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/144): In order to upgrade weapons, we must have additional or upgraded weapons.

# **Milestones**
List of steps that need to be completed for this task.
- [x] (Sep. 3) - Upgrade Tree concept design completed and documented in wiki.
- [x] Sep. 7) - [Upgrade Tree Structure](https://github.com/UQcsse3200/2023-studio-2/issues/132) completed.
- [x] (Sep. 11) - Upgrade Tree GUI completed.
- [x] (Sep. 12) - Upgrade Tree GUI tested and documented on wiki page.
 
**Completion Deadline:** Sep. 15

 
# **Documentation**
- [Upgrade Trees wiki.](https://github.com/UQcsse3200/2023-studio-2/wiki/UpgradeTree)
 
# **Member**
- Connor Golin (@connor-golin)
