### ISSUE TITLE
Spawning enemy spawners on the map

### ISSUE THREAD

**Issue by kk4w4i** [UQcsse3200/2023-studio-2#147]
# **Description**
This collaboration ticket will ensure that the enemies spawn in waves using a time ticking spawner, that handles a time delay to separate wave intervals. Spawners will be placed in locations desired by the map team and have the enemies chasing the specified target upon spawn.  
 
## **Example**
- **Waves**: For sprint 2 the map team have designed 3 waves for the EarthGameArea.
- Wave 1: 10 melee enemies
- Wave 2: 10 melee enemies, 5 ranged enemies
- Wave 3: 10 melee enemies, 10 ranged enemies

# **Dependencies**
This is a collaboration ticket between the Enemy Team and the Map Team. Further discussion between story and ship and extractor team may take place, depending on the progress.

- [x] Enemy Improvements (#128)
- [x] Fine-tuning Map (#119)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Enemy team demonstrate spawner implementation (Sep. 3)
- [x] Add spawnDelay to the SpawnerComponent (Sep. 6)
- [x] Map team implement spawners on the map (Sep. 7)
- [x] Implement the waves (Sep. 10)
 
**Completion Deadline:**
10th September 2023 

# **Documentation**
TBA
 
# **Member**
- Name (GitHub Username) (Discord Handle)
- Kintaro (kk4w4i) (0xkin)
- Manvi (ManviNarang01) (nowimhaunted.)
- Sam (SamarthDevVaish) (Erina_Exotic)
