### ISSUE TITLE
Turret class basic implementation (Sept 6)

### ISSUE THREAD

**Issue by NotRaghavAggarwal** [UQcsse3200/2023-studio-2#148]
# **Description**
**Task:** Turret Class.
**Feature:** [Turrets](#118)

Implement a Turret Class into the game engine, which will extend the Entity class. It will abstract the addition of components into the class itself so every Turret will have identical components regardless of where it is created. The Turret class will have a Physics Component and a Collider Component to prevent other entities from going through the Turret. It will need to implement a Combat Stats Component for damage.

# **Dependencies**
- [x] #118 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design class interface (Sep. 4)
- [x] Implement class methods (Sep. 6)
- [x] Add Javadoc comments 
- [x] Add documentation (Sep. 7)
 
**Completion Deadline:** September 7

# **Documentation**
- [Turret](https://github.com/UQcsse3200/2023-studio-2/wiki/Turret-(Game-Entity))
 
# **Member**
- Raghav (@NotRaghavAggarwal) (Raghav Aggarwal)
