### ISSUE TITLE
Turrets shoot enemies

### ISSUE THREAD

**Issue by yuvrajsingh001** [UQcsse3200/2023-studio-2#150]
# **Description**
**Task:** Turrets shoot enemies (#150)
**Feature:** [Turrets](https://github.com/UQcsse3200/2023-studio-2/issues/118)

Implement a Field of view component. This component will inherit `ProximityActivationComponent` (PAC) and add event handler to shoot enemies when they enter the specified FOV (within the radius from PAC) of the turret. This will be made possible by passing a FOV value while adding the component. Depending on this FOV value the turrets would rotate 360/FOV times (after a small interval) to cover their entire surroundings.
 
## **Example**
- **Part**: If and enemy enters the proximity of the turret and the turret is facing enemy's direction (FOV), only then the turret would shoot the enemy.
- **FOV Benefits**: Can implement turrets with different attack styles (not always 360).

# **Dependencies**

- [x] #148
- [x] #154
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create basic FOV component and wiki (Sept. 7)
- [x] Functionality for rotation (Sept. 9)
- [x] Shooting enemies and unit testing (Sept. 11)
 
**Completion Deadline:** Sept. 11

# **Documentation**
- [Turret](https://github.com/UQcsse3200/2023-studio-2/wiki/Turret-(Game-Entity))
- [FOV Component](https://github.com/UQcsse3200/2023-studio-2/wiki/FOV-Component)
 
# **Member**
- Yuvraj (@yuvrajsingh001) (Yuvraj Singh)
