### ISSUE TITLE
Player Death

### ISSUE THREAD

**Issue by racheljadel** [UQcsse3200/2023-studio-2#151]
# **Description**
**Task:** Player Death
**Feature:** [Improved Player Feature](https://github.com/UQcsse3200/2023-studio-2/issues/122)

This task aims to implement a player death event which is triggered when the player's health reaches zero. This event will involve a death animation of the player and a 'game-over' death screen, which should return the player to the main menu screen (restarting the level).

# **Dependencies**
No dependencies for this task

# **Milestones**
List of steps that need to be completed for this task.
- [x] (Sep. 6) - Designed player death animation and player death screen
- [x] (Sep. 6) - Created a death event triggered by health reaching zero
- [x] (Sep. 8) - Unit testing created for player death.
- [x] (Sep. 10) - Player death screen, animation and event implemented and tested.
- [x] (Sep. 10) - Updated documentation of player death on Wiki.
 
**Completion Deadline:** Sep. 10

# **Documentation**
To be completed.
 
# **Members**
Rachel Leathers (@racheljadel) (Rachel Leathers)
