### ISSUE TITLE
New Space map

### ISSUE THREAD

**Issue by TDay1** [UQcsse3200/2023-studio-2#152]
# **Description**
**Task:**
**Feature:** #5 

In the last sprint, a rudimentary space map was created. However, it is not implemented correctly and its design does not fit with the theme of the rest of the game. As such a new one will be implemented that better suites the requirements of the game.
 
## **Example (optional)**
- **Switch planets**: Upon clicking a planet.
- **Display planets**: Rather than displaying buttons, display aesthetically pleasing icons.
- **Clickable planets** When a player hovers over a planet, an animation should play and when a planet is clicked, the user should be taken to that planet.

# **Dependencies**
 
# **Milestones**
- [x] Design and implement new design(Friday Sep. 8)
- [x] Integrate display with main view (Monday Sep. 11
- [x] Complete documentation and integration (Wednesday. 13)
 
**Completion Deadline:** Sep. 13

# **Documentation**
TBD
 
# **Member**
- Thomas Day (@TDay1) (Tom Day)
