### ISSUE TITLE
Ship upgrades for the Space minigame

### ISSUE THREAD

**Issue by TDay1** [UQcsse3200/2023-studio-2#153]
# **Description**
**Task:** Ship upgrades for the Space minigame
**Feature:** #3 

When a player wished to travel through space they must complete the "space minigame" which consists of flying a ship through an asteroid maze. To add depth and gameplay to this minigame, the space team will implement a mechanism to upgrade ships with new abilities.

# **Dependencies**

- [x] #8 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Determine the possible upgrades and how they are unlocked (Sep. 6) (Vy and Foref)
- [x] Set up the upgrade shop where player can take the desired items to upgrade their ship(Sep. 10) (Vy)
- [x] Implement items and enable the player to take the item to upgrade their ships (Sep 12) (Foref)
- [x] Documentation about the mechanism (Sep. 12) (Vy)
 
**Completion Deadline:** Sep. 13
 
# **Documentation**
[Travelling between planets mechanism](https://github.com/UQcsse3200/2023-studio-2/wiki/Travelling-between-planets)

# **Member**
- Vu Khanh Vy Ho (@VuKhanhVyHo)
- Zhen Feng Ting (@Foref )

**Comment by Foref** [comment]
Created upgrades that can be picked up by the ship in the shopArea.

Currently implemented healthupgrade. Uses new interaction key "F" near the upgrade to pick it up.
The upgraded state will be reflected on a display.
