### ISSUE TITLE
Placing and picking up turrets

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#154]
# **Description**
**Task:** [Placing and picking up turrets](#154).
**Feature:** [Turrets](#118)

Implement the ability to place and pick up turrets. This should be done via a reusable component/class which will allow placing and picking up for any future placeable items.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Plan the design to implement (Sept. 5)
- [x] Implement placing (Sept. 7)
- [x] Implement picking up (Sept. 8)
- [x] Write tests (Sept. 13)
- [x] Write documentation (Sept. 13)
 
**Completion Deadline:** Sept. 13
 
# **Plan**
BuildInventoryComponent will be added to the player and will facilitate the creation of placeable items.
```mermaid
classDiagram
    class PlaceableEntity {
        <<inherits>>
        +placed()
        +removed()
    }
    class Entity

    class BuildInventoryComponent {
        - items : List<PlaceableItem>
        - selectedIndex : int
        + setSelectedIndex(index : int) void
        + createSelectedItem() PlaceableEntity
    }

    class PlaceableItem {
        <<interface>>
        + PlaceableEntity createEntity()
    }

    Entity <|-- PlaceableEntity
    PlaceableEntity o-- PlaceableItem
    PlaceableEntity <-- BuildInventoryComponent
```

```mermaid
sequenceDiagram
    PlayerActions ->>+ BuildInventoryComponent: setSelectedIndex(0)
    PlayerActions ->>+ BuildInventoryComponent: placeableEntity = createSelectedItem()
    PlayerActions ->>+ StructurePlacementService: placeStructureAt(placeableEntity, new GridPoint2(0,0))
    StructurePlacementService ->>+ PlaceableEntity: placed()
    PlayerActions ->>+ StructurePlacementService: removeStructureAt(new GridPoint2(0,0))
    StructurePlacementService ->>+ PlaceableEntity: removed()
```

# **Documentation**
- [StructureToolPicker](https://github.com/UQcsse3200/2023-studio-2/wiki/StructureToolPicker)
- [Tool](https://github.com/UQcsse3200/2023-studio-2/wiki/Tool)
 
# **Member**
- Rowan (@rowan-gray)

**Comment by rowan-gray** [comment]
Plan created.

**Comment by rowan-gray** [comment]
Implement placing completed.

**Comment by rowan-gray** [comment]
Implemented picking up completed.

**Comment by rowan-gray** [comment]
Completed.
