### ISSUE TITLE
Fix collision boxes of environmental obstacles

### ISSUE THREAD

**Issue by ArmandoLiebenberg** [UQcsse3200/2023-studio-2#157]
### Description
The collision boxes of some of the environmental objects are very wonky. Particularly for the ones that are larger than one tile. Need to find some sort of extendable solution for this.

### Milestones

- [x]  Goal 1 (Sep. 9) Develop collision boxes
- [ ]  Goal 2 (Sep. 11) Testing, debugging, work with the building team
- [ ]  Goal 3 (Sep. 13) Finalise code, push to main

Completion Deadline: September 14th
### Members
- Jordan Singh (@rike568) (Jordan Singh)
- Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)

**Comment by ArmandoLiebenberg** [comment]
Made some minor tweaks to improve collisions. Couldn't see a path to work on it further. Closing as semi complete. Might be looked at in a later sprint.
