### ISSUE TITLE
Implement Screen for Space Minigame

### ISSUE THREAD

**Issue by 24msingh24** [UQcsse3200/2023-studio-2#158]
# **Description**
Description:
Create an interactive screen that appears when the player clicks on the "Space Minigame" button, indicating that the game has started. 

**Task:** 
As a player, the player will be able to see a visually appealing  screen when they start the space minigame, and then would click on the button to enter into the game

**Feature:**
#126 

# **About**
- When the "Space Minigame" button is clicked, a screen should appear immediately.
- The screen should display a text 
message, giving the impression of launching into space.
- After that, the player should be seamlessly taken to the space minigame interface.
 
## **Example (optional)**

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create the initial code for the screen
- [x] Add the necessary text/message and visual elements
- [x] Ensure seamless transition from the screen to the space minigame interface.
 
**Completion Deadline:** Sep 12

 
# **Documentation**
- to be added
 
# **Member**
- Manandeep Singh (24msingh23)
