### ISSUE TITLE
Player Inventory

### ISSUE THREAD

**Issue by kushagra1912** [UQcsse3200/2023-studio-2#159]
# **Description**
**Task:** Player Inventory
**Feature:** [Improved Player Feature] (#122) 

The task is to implement player inventory to allow the player to swap between buildables and weapons.
 
# **Dependencies**
No dependencies for this task.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implementation of Inventory Component (Sep. 6)
- [x] Unit Tests Created for player inventory (Sep. 8)
- [x] Updated Documentation for player inventory on the wiki (Sep. 10)
 
**Completion Deadline:** Sep. 10
 
# **Documentation**
To be Completed.
 
# **Member**
Kushagra Agrawal (@kushagra1912) (Kushagra Agrawal)
