### ISSUE TITLE
Extractor production, UI and general game level enhancements

### ISSUE THREAD

**Issue by Minirobbo** [UQcsse3200/2023-studio-2#160]
# **Description**
Our team 'Holy Ship' is currently working on a variety of important tasks. In the visuals department, we're improving Extractor Animations, creating a Blast-off sequence, and enhancing the Ship Sprite. We also have an additional task related to Deployment. In the UI area, we're working on things like refining Extractor Arrows, completing resource bars and adding an Interaction Popup. We're also addressing an extra task for the Extractor Resource Tick. On the mechanical side, we're collaborating with the Map/Story team to develop Extractor zones, Player spawn points, and Extractor placement & UI. Lastly, we're prioritizing Resource Balancing, Limits, and Documentation to ensure a balanced and well-documented gaming experience. These tasks are aimed at improving the game's visuals, user interface, and mechanics while seamlessly integrating them into the game's narrative and world.

## SubFeature/Component (Optional)

Ship and Extractors Visual Updates:

- Developing ship sprite and remaking extractor sprite.
- Remaking broken extractor sprite.
- Creating frames for extractor animation.
- Adding animation to extractors for resource indication.
- Ship blast-off animation.
- (Extra) Player deployment of extractors, potentially including orbital drop animation.
- Wiki documentation updates for the ship and extractors.

Ships & Extractors UI Task Ticket:

- Extractor Arrows.
- Finish resource bars.
- Interaction Popups.
- Extractor Resource Tick (Extra).

Ship and Extractors Mechanical Task:

-  Config File, Testing, and documentation.
-  Extractor Placement UI, documentation and Wiki.
-  Implement Extractor Placing and update UI.
-  Resource production rate balancing.

# **Dependencies**
Art and design committee.

# **Milestones**
- [x] Ship and Extractors Visual Updates #133 (Sep. 14)
- [x] Ship and Extractors Mechanical Task #123 (Sep. 14)
- [x] Ships & Extractors UI Task Ticket #120 (Sep. 14)

**Completion Deadline:** Sep. 14

# **Documentation**
See milestones for task-specific documentation.

# **Members**
- Name (GitHub Username) (Discord Handle)
- Isaac @Minirobbo
- McArthur @McArthur-Alford McArthur
- Tarushi @Tarushi263 tarushigera
- Neil Barigye @neil-nb nickbattle1#9383
- Divyanshu @Div1o1 zenith3122
- Abhijith Varma Gadiraju @abhijithvarma03 Abhijith#0137
