### ISSUE TITLE
Add Turret Assets

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#161]
# **Description**
**Task:** [Turret Assets](#3).
**Feature:** [Turrets]( #118)
This task involves designing and creating visual assets for turrets in the game.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1:Design turret sprites for different types of turrets (e.g., machine gun, laser, rocket).(Sept 9th)
- [ ] Step 2:Ensure assets follow the game's art style and dimensions.(Sept 9th)
- [ ] Step 3:Organize assets in the game's asset directory.(Sept 9th)
- [ ] Step 4:Update the game's documentation to include information about the new turret assets.(Sept 9th)
 
**Completion Deadline:** Sept 10th

# **Documentation**

 
# **Member**
@khushijain0302

**Comment by rowan-gray** [comment]
This ticket is no longer being completed. We will revisit it in Sprint 3 or Sprint 4, time permitting.
