### ISSUE TITLE
Health and damage (config files)

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#163]
# **Description**
**Task:** [Health and damage (config files)](#3).
**Feature:** [Turrets](#118)

In our game, we need to define the health and damage properties of different types of turrets. This will allow us to balance gameplay and create a more dynamic gaming experience.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Create Config Files and define Turret Types(Sept 9)
- [x] Step 2: Set Default Values(Sept 9)
- [x] Step 3:Testing(Sept 9)
- [x] Step 4:Documentation (Sept 9)
 
**Completion Deadline:** Sept 10
- [Turret](https://github.com/UQcsse3200/2023-studio-2/wiki/Turret-(Game-Entity))
 
# **Member**
@khushijain0302
