### ISSUE TITLE
Create Ending Transition Screen for Space Mini Game

### ISSUE THREAD

**Issue by shaivikaaaa** [UQcsse3200/2023-studio-2#165]
# **Description**
Create a transition screen that appears when the player clicks on the "Exit" button, indicating that the game has ended. This transition screen should involve a spaceship animation. At a later date, this animation will appear when the space minigame is won or lost.

Task:
As a player, the player will be able to see a visually appealing transition screen when they start the space minigame, so they know that the game has ended.

# **Feature Ticket**
https://github.com/UQcsse3200/2023-studio-2/issues/126

# **About**

When the "Exit" button is clicked, a transition screen should appear immediately.
The transition screen should display a spaceship animation, giving the impression of launching back from the space.
The transition screen should include a text message or visual indicator that informs the player that the game has ended.
The transition screen should last for a reasonable duration (e.g., 3-5 seconds) before transitioning to the actual space minigame.
After the transition screen, the player should be seamlessly taken back to the Main Menu Display screen
 
Example (optional)

Dependencies

N/A

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design the ending screen
- [x] Implement transition logic
- [x] Add spaceship animation
- [x]  Display victory message
 
**Completion Deadline:** Sep 08

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Shaivika Anand (shaivika21)
