### ISSUE TITLE
Designing of new map

### ISSUE THREAD

**Issue by ArmandoLiebenberg** [UQcsse3200/2023-studio-2#166]
### Description
Map 2 for the game

Description from story team:
_"Your ship lands on a lush planet, seemingly untouched by the virus. However, strange plants and creatures inhabit this world. Exploring its dense forests and vibrant meadows, you collect samples that might hold the key to the cure. But danger lurks in the form of alien predators and treacherous terrain. You'll need to solve puzzles to decode the alien plant's properties and unlock its potential for a cure. At the end of the level, you'll choose a companion from the planet to join your team - a botanist who can help you understand the alien flora."_

### Milestones

- [x]  Goal 1 (Sep. 9) demo for new map
- [x]  Goal 2 (Sep. 11) gather feedback on map design, talk to story team
- [x]  Goal 3 (Sep. 13) Finalise map, push to main
- [ ]  Bonus: Fix up map 1 art style to be more consistent with other teams

Completion Deadline: September 14th
### Members
- Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)
