### ISSUE TITLE
Add layering to obstacles

### ISSUE THREAD

**Issue by Anshuman0157** [UQcsse3200/2023-studio-2#167]
### Description
Currently, the obstacles lack the visual distinction of the player character moving behind or in front of them, causing a lack of depth perception. The goal is to modify these obstacles so that it's visually evident when the player character moves behind specific environmental objects.

### Milestones

- [x]  Goal 1 (Sep. 8): Evaluate Obstacle Layering Needs
- [x]  Goal 2 (Sep. 10): Implement Layering Effects
- [ ] Goal 3 (Sep. 14): Documentation and Testing

Completion Deadline: September 14th
### Members
- Anshuman Misra (@Anshuman0157 ) (Anshuman Misra)
- Raghav Aggarwal (@NotRaghavAggarwal) (Raghav Aggarwal)
