### ISSUE TITLE
Companion Attack and Defence Mode

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#168]
# **Description**
**Task:** #168
**Feature** (#135)
This is implementing distinct modes within the companion. They will initially be activated by key press, but will later be activated by some game state event. The attack mode involves the player being able to attack with a meelee weapon and move faster.
The defence mode allows the companion to bring up a shield and protect itself and the player from oncoming long range weapons.

# **Dependencies**
- [x] Dependency 1 (#136 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Sep 8) Set up key bind press
- [ ] Step 2 (Sep 9) Create 'mode' functionality and structure 
- [ ] Step 3 (Sep 10) Create shield defensive logic, Create meelee effect damaging objects in forward direction
- [ ] Step 4 (Sep 11) Polish and push to main
 
**Completion Deadline:** Sep. 13
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion

 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Atharva Gupta (atharvagupta2003) (@atharva0179)
- Maxwell (MaxwellSchroder) (@Magwell)

**Comment by MaxwellSchroder** [comment]
Made redundant by new task tickets more specific for defence
