### ISSUE TITLE
NPC Improvements Task

### ISSUE THREAD

**Issue by rachitchaurasia** [UQcsse3200/2023-studio-2#172]
# **Description**
**Task:** Enhance NPC Dialogues and Behaviors
**Feature:** NPC Improvements

In this task, Rachit Chaurasia and Dev Gupta will collaborate to enhance the Non-Player Character (NPC) interactions in the game. This includes improving NPC behaviors and dialogues to create more engaging and immersive interactions with the player. The goal is to make the NPCs feel more lifelike and responsive to the player's actions, ultimately contributing to an enhanced player experience.

# **Dependencies**
- None

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Review and analyze the existing NPC behaviors and dialogues 
- [x] Brainstorm and design improvements to NPC interactions 
- [x] Implement and test the enhanced NPC behaviors and dialogues 
- [x] Update documentation to reflect the changes made to NPC interactions 
 
**Completion Deadline:** Sept. 14
 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-2/wiki/Botanist-NPC

# **Member**
- Name (GitHub Username) (Slack Handle)
- Rachit Chaurasia (@rachitchaurasia) (s4823870)
- Dev Gupta (@DRG31) (xdrgx)
