### ISSUE TITLE
Implement Wall Object

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#18]
# **Description**
**Task:** Wall Class.
**Feature:** [Walls/barricades](#6)

Implement a wall object into the game engine which will extend the Entity class. It will abstract the addition of components into the class itself so every wall will have identical components regardless of where it is created. The wall class will add a Physics Component and a Collider Component to prevent other entities from going through the wall. The wall class will also add a Texture Component for the wall sprite/s. It will need to implement a Combat Stats Component for damage.

# **Dependencies**
- [x] #9 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design class interface (Aug. 19)
- [x] Implement JUnit tests (Aug. 21)
- [x] Add Javadoc comments (Aug. 23)
- [x] Implement class methods (Aug. 23)
- [x] Add health label (Aug. 23)
- [x] Add documentation (Aug. 25)
 
**Completion Deadline:** Aug. 25

# **Documentation**
- [Wall](../wiki/wall)
 
# **Member**
- Rowan (@rowan-gray) (rowan gray)
