### ISSUE TITLE
Extractor Repair Mini Game Develop

### ISSUE THREAD

**Issue by JunxianHuang** [UQcsse3200/2023-studio-2#183]
# **Description**
**Task:** [Extractor Repair Mini Game Develop](#3).
**Feature:** [Extractor Repair Mini Game Feature](#2)
Implement a click-to-repair mini-game where the player has to click on damaged parts and highlight them on the repair screen to increase the difficulty of the player in the main game. In the last sprint, this feature was not perfect, this time it will be optimized and new features will be added (game rules)

 
## **Example **
- **Tool **: For different parts of the different damage players will need to use different tools to repair
- **Bang**: Players using the wrong tool to repair will result in an "explosion" and receive a progress penalty

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 additional rules(Sep.7 )
- [ ] Step 2 mouse status(cursor) (Sep. 8)
- [ ] Step 3  Implementation of features(Sep. 11)
- [ ] Step 4 Jtests(Sep. 14)
 
**Completion Deadline:** Sep. 14

# **Documentation**
TBD
 
# **Member**
- Junxian Huang (@JunxianHuang)
- Zhen Feng Ting (@Foref)
- Isaac (@Minirobbo) (Minirobbo）
