### ISSUE TITLE
Base Planet GameArea Type

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#184]
# **Description**
**Task:**Base Planet GameArea Type.
**Feature:** [Feature which this tasks contributes to implementing](#119 )

All the planets for the game utilise similar, shared base functionality and design solutions. As such a common inheritance node must be designed to appropriately outline this behaviour and reduce code duplication. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design base game area class for all planets to be loaded into using json files.
- [x] Create data access objects for each entity type
- [x] Refactor factory methods to use DAO to load game area from any state
- [x] Refactor existing EarthGameArea to utilise this new framework
- [x] Write documentation outlining design.
- [x] Add testing for Assets and Game Areas
- [x] Add testing for factories using configs
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
https://github.com/UQcsse3200/2023-studio-2/wiki/Creating-Entities-with-Configuration-Files
 
# **Member**
- Heny Batt @henrybatt 
- Manvi Narang (@ManviNarang01) (Manvi Narang)
- Samarth Dev Vaish (@SamarthDevVaish) (Samarth Dev Vaish)
- Isaac Robinson @Minirobbo (Minirobbo)

**Comment by rowan-gray** [comment]
Don't forget to add Team 7 to the mix!!!
