### ISSUE TITLE
Interaction of turrets with enemies and player

### ISSUE THREAD

**Issue by Yugansh-Uq** [UQcsse3200/2023-studio-2#185]
# **Description**
**Task:** Interaction of Turrets(#185).
**Feature:** Turrets(#185)

In this feature of turrets, we will work on leveraging config files for healing of turrets using resources. Possibly as an extension, we will also be adding to turret assets more ammunition which might possibly be done using config files.
 
## **Example**
- We can view the health of turrets through health bar. When health drops significantly, the player can provide new health to the turrets using resources collected.
- We can also add more ammunition to turrets.
 
# **Dependencies**

- [x] Turret class basic implementation (#148)
- [x] Health and damage (config files) (#163)
- [x] Turrets shoot enemies (#150)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implementing necessary components and entities that give us the required output 

 
**Completion Deadline:** Sept 10, 2023

# **Documentation**
- [Turret](https://github.com/UQcsse3200/2023-studio-2/wiki/Turret-(Game-Entity))

# **Member**
- Yugansh (Yugansh-Uq)

**Comment by rowan-gray** [comment]
Please add the necessary labels and assign yourself @Yugansh-Uq .

**Comment by rowan-gray** [comment]
Completed.
