### ISSUE TITLE
Extractors in building UI

### ISSUE THREAD

**Issue by mira-alford** [UQcsse3200/2023-studio-2#187]
# **Description**
Collaboration ticket

The goal of this ticket is to unify the building of extractors with the buildable teams menu for placing buildings. This should mean that the user can select what they are building from the menu, and then be limited to only placing it in locations that produce resources. 

# **Dependencies**

- [x] [Building Menu](#154)
- [ ] Resource patches

# **Milestones**
- [x] Extractors are buildable
- [x] At most 4 extractors per resource can be built
- [x] Extractors can only be built in the appropriate locations 
- [ ] Extractors are assigned the resource they are built on top of
    - Not done, but all functionality is in place for once the resource patches are implemented. (waiting on dependency)
- [x] Make it so buildings cost resources
- [x] Unit tested extractor tool

# **Extras**
- [ ] Extractors fly down from space when built (@neil-nb)
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...

**Comment by rowan-gray** [comment]
Delayed some task to sprint 3, but the current implementation is functional
