### ISSUE TITLE
Ship/Extractor Entity Spawn and Collisions

### ISSUE THREAD

**Issue by neil-nb** [UQcsse3200/2023-studio-2#19]
# **Description**
**Feature:** #26

Initializing the ship and extractor positioning on the map to ensure a consistent gameplay experience for players. Additionally, collision detection will be implemented for interactions with the ship and the extractors. This is to prevent the player phasing through the ship or extractors, contributing to a more immersive and realistic in-game environment.

# **Dependencies**

- [x] The map needs to exist for there to be a coordinate to spawn at
 
# **Milestones**

- [x] Description on ship mentioning spawn documented on wiki (Aug. 22)
- [x] Extractor sprites chosen (Aug. 22)
- [x] Ship sprites chosen (Aug. 22)
- [x] Creation of entity (including hitboxes) (Aug. 24)
- [x] Unit tests of extractor health (Aug. 28)
- [x] Ship entity class implemented and tested (Aug. 30)

 
**Completion Deadline:** Aug. 31

 
# **Documentation**
[Ship and Extractors Wiki Page](https://github.com/UQcsse3200/2023-studio-2/wiki/Ship-and-Extractors)
 
# **Member**
- Neil (@neil-nb)
