### ISSUE TITLE
Equipped Hammer & Structure Picker Upgrades

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#191]
# **Description**
Collaboration ticket

The aim of this collaboration ticket is to integrate the equipped building hammer with the structure picker, and to ensure that when the hammer is upgraded within the Upgrade Tree, it enables the placement of more/upgraded building structures.

# **Dependencies**

- [x] [Player Inventory Component](#159)
- [x] [Building Placement Handlers](#71)
- [x] [Upgrade Tree Structure](#132)
- [x] [Wall Upgrades](#83)

# **Milestones**
- [x] 1. Equipped building hammer can place and remove walls.
- [x] 2. Structure Picker is integrated with the current equipped hammer.
- [x] 3. Hammer upgrades within the Upgrade Tree also level up the Structure Picker's amount of building placeables.

**Comment by rowan-gray** [comment]
Done and dusted 😃
