### ISSUE TITLE
Recreating Introduction to Game

### ISSUE THREAD

**Issue by neil-nb** [UQcsse3200/2023-studio-2#196]
# **Description**
**Task:** [Recreating Introduction to Game](#3).
**Feature:** [Sprint 2 Enhancements: NPC, Storyline, Game Over, and Load Functionality #134](#134)

Recreating the introductory 'cutscene' the player comes across when starting a new game. Potentially adding new details and ideas to the lore of the game. Potentially rewriting the introductory blurb and tweaking the UI of the game to make it more aesthetically pleasing.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Make script for 'cutscene' (Sep. 6)
- [x] Find viable and aesthetically pleasing fonts to use for cutscene and UI tweak (Sep. 7)
- [x] Make/Find art/images to use for 'cutscene' (Sep. 8)
- [x] Create 'scenes' with text overlay on the art/images (Sep. 8)

--EXTRA--
- [x] Rewrite blurb for conciseness and change font (Sep. 12)
- [x] Tweak lore of game (Sep. 12)
 
**Completion Deadline:** Sep. 15
 
# **Documentation**
- [Story Screen Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/STORY-SCREEN-DOCUMENTATION)
- [Story Outline](https://github.com/UQcsse3200/2023-studio-2/wiki/Story-Outline)
- [Main Menu and Setting Display Changes](https://github.com/UQcsse3200/2023-studio-2/wiki/MAIN-MENU-AND-SETTING-MENU-DISPLAY-CHANGES)
 
# **Member**
- Neil Barigye, Discord: NickBattle1#9383  Github: @neil-nb
- Yash Mittal (@YashMitttal) (s4823869)
