### ISSUE TITLE
Powerups

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#20]
# **Description**
**Task:** [Powerups](#20)
**Feature:** [Player Feature](https://github.com/UQcsse3200/2023-studio-2/issues/13)

The aim of this task is to provide the user with a more engaging experience with the game by implementing 'Powered up' abilities to the player.
`PowerupComponent` and `PowerupFactory` classes will be implemented, which will enable the ability to spawn a powerup within the game map. Each powerup will provide unique enhancements to the player. Once activated, powerups have a set duration or effect. When the duration or effect ends, the player may revert to their standard capabilities until another powerup is engaged.
 
## **Examples**
- **Movement Powerup**: The player acquires a movement powerup, which grants increased movement speed for a fixed duration.
- **Health Powerup**: The player acquires a health powerup which restores the player to full health.

# **Dependencies**
- [x] #25 is required to modify the player movement system for new powerups (e.g. Movement Powerups), as well as to ensure that players can navigate the map to acquire new powerups.

 
# **Milestones**
List of steps that need to be completed for this task:
- [x] (Aug. 24) - Unit tests for `Powerup` class created.
- [x] (Aug. 24) - Initial documentation created on wiki.
- [x] (Aug. 25) - `Powerup` class implemented and tested.
- [x] (Aug. 25) - Randomly spawned initial power-up implemented.
- [x] (Aug. 29) - Documentation of `Powerup` updated on wiki.
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- Located on the [Wiki page.](https://github.com/UQcsse3200/2023-studio-2/wiki/Powerups)

 
# **Member**
- Connor Golin (@connor-golin) (Connor Golin)
