### ISSUE TITLE
Implement Ammunition System for Turrets 

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#206]
# **Description**
**Task:** [Ammunition for Turrets](#3).
**Feature:** [Turrets](#118 )

In this task, we will implement an ammunition system for turrets. Currently, when a player fires a turret, ammunition is consumed, and when it runs out, the turret becomes inactive until it's refilled using resources. To accomplish this, we'll need to integrate an interaction component to handle ammunition refilling, update the configuration file to include maximum ammunition limits, and ensure that turret ammunition is correctly deducted and refill.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement interaction component for ammunition refilling.
- [x] Update configuration file to include maximum ammunition limits.
- [x] Implement turret ammunition deduction and refilling logic
- [x] Testing
- [x] Documentation

# **Documentation**
- [Turret](https://github.com/UQcsse3200/2023-studio-2/wiki/Turret-(Game-Entity))

# **Member**
@khushijain0302
