### ISSUE TITLE
Adjacent wall/gate textures join together

### ISSUE THREAD

**Issue by NotRaghavAggarwal** [UQcsse3200/2023-studio-2#21]
# **Description**
Feature #6 

Adjacent wall/gate textures and collision shapes join together. This ensures natural transition between the textures and the walls block entities from passing through. This ensures that the game looks more real and logical.

## **Example**
- When two walls/gates are adjacent and placed next to each other, they should combine and form a more prominent wall/gate twice the size of one wall/gate. 

# **Dependencies**
- #9
- #18 
- #23 

# **Milestones**
List steps that need to be completed for this task.
- [x] Create AtlasRenderComponent
- [x] Create a method to find a walls neighbours
- [x] Use AtlasRenderComponent to change texture depending on neighbours
- [x] Change hitbox depending on neighbours
- [x] Implement JUnit Testing
- [x] CheckStyle and add Documentation 

**Completion Deadline:** Aug. 28

# **Documentation**
- [AtlasRenderComponent](../wiki/Atlas-Render-Component)
- [JoinableComponent](../wiki/Joinable-Component)

# **Members**
- Raghav (@NotRaghavAggarwal) (Raghav Aggarwal)

**Comment by rowan-gray** [comment]
Functionality implemented in cf082f11f8bc8c95f2110fcd42204ede88e84714

**Comment by rowan-gray** [comment]
Documentation and testing complete.
