### ISSUE TITLE
Improve Companion StatsDisplay

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#219]
# **Description**
**Task:** Improve Companion StatsDisplay
**Feature:** #135 
The companion statsDisplay is currently below the player. We want to move the companion stats to a different portion of the screen and consider them to completely separate entities by the players.

# **Dependencies**
None in this sprint
UI already set up

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Sep 14) Adjust the location of the Companion Health UI component on the screen to be more suitable
- [ ] Step 2 (Sep 14) Add the 'boost' property to the UI section responsible for companion
- [] Step 3 (Sep 14) Add other interesting game states to UI
 
**Completion Deadline:** Sep. 14
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
- Improved UI designs: https://github.com/UQcsse3200/2023-studio-2/wiki/Companion-Alert-Documentation
 
# **Member**
- Maxwell (MaxwellSchroder) (@MaxwellSchroder )
