### ISSUE TITLE
Extractor Status + Production

### ISSUE THREAD

**Issue by mira-alford** [UQcsse3200/2023-studio-2#22]
# **Description**
**Feature:** #26 

Implement the functionality of extractors. Extractors passively produce a specific resource every n seconds, sending it to the ship entity. Extractors have a health component and as such can be damaged by enemies, and when health is below 0 will stop producing resources. Broken extractors can be interacted with to activate the repair minigame. 

# **Dependencies**
- [x] Global resource store + api (#5)
- [x] Ship resource tracking (#24)
- [ ] Repair minigame (#37)
- [x] Interaction Component (#72)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial creation of extractor entity created and documented on wiki - 20th
- [x] Unit tests implemented for extractors - 21st
- [x] Extractors track health and can be damaged. - 24th
- [x] Interaction with extractor when broken repairs to full health. - 27th
- [x] Extractors inform ship of new resources on a timer. - 24th
- [x] Extractor production is influenced by their damage. - 27th
- [x] Extractor List in UI with Health/Production/Position information - 29th
- [x] Extractors indicate damage visually through sprite changes or UI element (healthbar) - 29th
- [x] Documentation of extractors. - 29th

**Completion Deadline:** Aug. 30
 
# **Documentation**
- [InteractionController and Interactable Component - extractor repair](https://github.com/UQcsse3200/2023-studio-2/wiki/Entity-Interactions)
- [Damage Texture Component - extractor sprite changes](https://github.com/UQcsse3200/2023-studio-2/wiki/Damage-Texture-Component)
- [Managing Game State - Updating ship with new resources](https://github.com/UQcsse3200/2023-studio-2/wiki/Managing-Game-State)
 
# **Member**
- Name (Github Username) (Discord Handle)
- McArthur (@McArthur-Alford) (McArthur)
- Isaac (@Minirobbo) (Minirobbo)

**Comment by Minirobbo** [comment]
@neil-nb Were you able to upload the sprites for the extractors and committ it? I have stand-in sprites for now, but they aren't copyright free or anything. I will be finishing up the testing and docs in the next few days. I ended up doing the tasks in a slightly different order but it shouldn't affect any other dependancies

**Comment by Minirobbo** [comment]
Done for sprint 1 - Repair minigame didnt finish their dependancy, but a placeholder minigame was used.
