### ISSUE TITLE
Companion Boost Modification into Attack and Defence Toggles

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#220]
# **Description**
**Task:** Companion Boost Modification into Attack and Defence Toggles
**Feature:** #135 

Change the boost to be a toggle. Then add a defence mode. Display this information on a UI component on the screen.

# **Dependencies**
#219 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep 13) Modify the b command to turn on or off an attack mode. Therefore, there is only attack and normal
- [x] Step 2 (Sep 14) Show the mode on the UI
- [x] Step 3 (Sep 14) Add another key to go into defence mode for the companion. 

 
**Completion Deadline:** Sep. 14
 
# **Documentation**
https://github.com/UQcsse3200/2023-studio-2/wiki/Companion

# **Member**
- Maxwell (MaxwellSchroder) (@MaxwellSchroder )

**Comment by MaxwellSchroder** [comment]
Was implemented. And defence mode now a specific task ticket
