### ISSUE TITLE
Improve Companion Alerts

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#221]
# **Description**
**Task:** Improve Companion Alerts #221
**Feature:** #384 
The companion alerts are currently on a fixed position on screen. Let's make it track the companion to be more useful.

# **Dependencies**
#219 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Oct 1) Set up the location tracker of the companions location
- [ ] Step 2 (Oct 1) Calculate a fixed offset for the UI component.
- [] Step 3 (Oct 1) Put the Alert next to companion
- [ ] Step 4 (Oct 1) Add a timer to remove that alert after a given amount of time.
 
**Completion Deadline:** Sep. 14
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
- Impoved alerts: https://github.com/UQcsse3200/2023-studio-2/wiki/Companion-Alert-Documentation
 
# **Member**
- Maxwell (MaxwellSchroder) (@MaxwellSchroder )

**Comment by MaxwellSchroder** [comment]
functionality needed to be improved for sprint 3 and look nice with better UI

**Comment by MaxwellSchroder** [comment]
This feature was never completed fully. It proved more difficult than we thought. This is because it is easy to find the in-game positon (x,y) but hard to find the screen position of the companion. Therefore, it's quite difficult to place UI objects at the screen position of the ccompnaion. Once we can do that, this feature is much easier. Still in development for sprint 4...
