### ISSUE TITLE
Companion Death Screen

### ISSUE THREAD

**Issue by atharvagupta2003** [UQcsse3200/2023-studio-2#225]
Description
Task: Display a death screen after companion's death
Feature: #135 

Display's a death screen when companion's health reaches zero.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (sep 14) Implementation of companiondeathscreenactions 
- [ ] Step 2 (sep 14) Implementation of companiondeathscreendisplay
- [ ] Step 3 (sep 14) designing a UI death screen
- [ ] Step 4 (sep 14) addition of companiondeathscreen in game screens
 
Completion Deadline: sep 14
 
# **Documentation**
pending
 
# **Member**
- Atharva Gupta (atharvagupta2003) (@atharva0179)
