### ISSUE TITLE
Creation of Portal and Secret Area

### ISSUE THREAD

**Issue by rike568** [UQcsse3200/2023-studio-2#226]
# **Description**

This will be the creating and implementing a portal in the game which will teleport the player to a secret area. This will be done by gathering the assets required for the portal, implementing the code, adding a new secret area in which the player will be teleported too and creating tests that make sure the code is fully functional. The addition of the portal and secret area will allow the player to feel the terror and excitement of being teleported to a completely unknown area and fighting against hoards of enemies in a very compact area.
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] #4
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Gathering of Portal Assets (Sept. 7)
- [x] Implementation of Portal and Teleport (Sept. 9)
- [x] Adding Secret Area to Current Map (Sept. 11)
- [x] Creation of Tests (Sept. 13)
 
**Completion Deadline:** Sept. 13

# **Member**
- Jordan Singh (@rike568) (Jordan Singh)
- Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)
