### ISSUE TITLE
Implementing Gate Object

### ISSUE THREAD

**Issue by Yugansh-Uq** [UQcsse3200/2023-studio-2#23]
# **Description**
We will inherit from wall class to build gate entity. We will give it a condition and might add proximity component which will enable the gate to open when the player is nearby and close when not. Also add collider component for enemies. 

# **Example**

The concept of a gate in the wall will be useful when we are attacked by enemies and we lose one of our resources. The player can go back to the extractor, create a closed room with walls of appropriate strength and a gate in it. The player can then revive the resource in peace without being attacked by enemies. But this part has a twist as walls have definite strength so that player cannot stay there indefinitely. He/She needs to finish the mini-game that needs to be played in order to revive the resource quickly.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] #Implementing Wall Object 18 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design gate class (Inheriting wall object)
- [x] Implement JUnit Test
- [x] Implementing class methods 
- [x] Implement ProximityActivationComponent to open and close when player enters proximity
- [x] Add documentation

 
**Completion Deadline:** Aug. 28

# **Documentation**
- [ProximityActivationComponent](../wiki/proximity-activation-component)
- [Gate](../wiki/gates)

# **Members**
Yugansh (@Yugansh-Uq)
Rowan (@rowan-gray)

**Comment by lorenzopolicar** [comment]
Just make sure to add in a description - this can be brief.

**Comment by rowan-gray** [comment]
Implement interaction with the player (Open and Close gate) completed in commit 8c33ddb8842850e37d8c8bf420676962aa8a4ed8

**Comment by rowan-gray** [comment]
Revised deadline to be 28th of August (previously 25th)
