### ISSUE TITLE
Controls Screen Creation

### ISSUE THREAD

**Issue by JivalX** [UQcsse3200/2023-studio-2#230]
# **Description**
**Task:** [Creating controls screen]
**Feature:** [Controls Screen Creation](#139)

Added a Controls button in Settings screen which displays a list of controls available to the player. 
 

# **Dependencies**
None 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create ControlsScreen and its Actions and Display classes (Sep. 12)
- [x] Add Controls button and functionality in settings screen and reposition it (Sep. 12)
- [x] Add suitable asset images (Sep. 13)

 
**Completion Deadline:** Sep. 14

 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-2/wiki/Controls-Screen
 
# **Member**
- Yash Mittal (@YashMitttal} (s4823869)
- Jival (@JivalX) (s4824576)
- Aniket Gupta (@aniketgupta17) (s4824063)
