### ISSUE TITLE
Ship resource displays

### ISSUE THREAD

**Issue by abhijithvarma03** [UQcsse3200/2023-studio-2#24]
# **Description**
**Feature:** #26 

The task "Ship Resource Displays" involves creating a system to manage and display various types of resources on the ship, tracking their availability, and providing information on when it is feasible to leave the planet based on available resources. This system will provide essential information for the player to make informed decisions about embarking on the next level and ensure the ship's sustainability.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Extractors and ship sprites must be implemented (#19 )
- [x] Resource replenishment system. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Visual representation of resource bar and Program for resource tracking and calculation on the ship-20/08/ - 23/08/23
- [x] Integration of resource tracking, and UI elements - 27/08/23

 
**Completion Deadline:** Aug. 31

 
# **Documentation**
- [Main description of feature](../wiki/Resources)
 
# **Member**
- Abhijith Varma Gadiraju (@abhijithvarma03) (Abhijith Varma Gadiraju)
- Divyanshu (@Div1o1 ) 
- McArthur-Alford (@McArthur-Alford )
