### ISSUE TITLE
Creating Potion Collector And Spawning Potions

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#248]
# **Description**
**Task:** Creating Companion Platform And Spawning Potions
**Feature:** #135 

Creating a entity which can be approached on the map. It will allow you to interact with the laboratory showing different potions.
Furthermore, potions are going to be spawned around the place. 

# **Dependencies**

- [ ] Potions being created #229 
- [ ] Lab window #175 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 10) - Initialising the platform
- [x] Step 2 (Sep. 12) - Connecting the potions to the lab window
- [x] Step 3 (Sep. 14) - Spawning potions on the map

 
**Completion Deadline:** Sep 14
 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-2/wiki/Companion

# **Member**
- Atharva Gupta (atharvagupta2003) (@atharva0179)
