### ISSUE TITLE
Companion Potion Effects

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#249]
# **Description**
**Task:** Potion Effects
**Feature:** #135 

Implementing the effects on the companion and player when companion toggles the laboratory inventory and creates particular potions.    

# **Dependencies**

- [ ] Potions being created #229 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Sep. 11) - Defining the effects needed by each potion
- [ ] Step 2 (Sep. 12) - Create different effects and triggers across entities
- [ ] Step 3 (Sep. 14) - Effect player as well as companion

 
**Completion Deadline:** Sep 14
 
# **Documentation**
- https://github.com/UQcsse3200/2023-studio-2/wiki/Companion

# **Member**
- Atharva Gupta (atharvagupta2003) (@atharva0179)
