### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by kushagra1912** [UQcsse3200/2023-studio-2#25]
# **Description**
**Task:** [Player Movement](#25)
**Feature:** [Player Feature](#13)

Implement base movement, including dodge and diagonal movement in the `KeyboardPlayerInputComponent` and `Vector2Utils` classes. The dodge will be a fast movement activated on the press of the “Space” key and will grant the player temporary protection and temporarily prohibit the player’s attack button. The diagonal movement will be activated when two directional keys are pressed simultaneously, moving the player at the same speed as the original four directional movements.

## **Example**
- **Dodge Benefits**: Players can dodge to avoid enemy attacks or projectiles. The Dodge button is available every 5 seconds. The player is granted immunity whilst dodging (1 second). The player cannot attack or fire a weapon whilst dodging.
- **Diagonal Movement Benefits**: Currently, players move faster (approximately 1.41 speed), travelling diagonally due to two directional keys being simultaneously pressed (1 speed each), which is not logical for game mechanics. The diagonal movement will be normalised when two directional keys are both pressed.

# **Dependencies**
- [x] [Texture](https://github.com/UQcsse3200/2023-studio-2/issues/32) and [status](#45) of the player facing different directions need to be created 
- [x] Immunity [status](#45) of player needs to be created 
- [x] [Attack](#35) button needs to be created 

# **Milestones**
List of steps that need to be completed for this task.
- [x] (Aug. 19) - Initial documentation of player movement on the wiki.
- [x] (Aug. 21) - Dodge and diagonal movement created in Vector2Utils class.
- [x] (Aug. 21) - Keyboard buttons assigned to dodge and diagonal movement in KeyboardPlayerInputComponent.
- [x] (Aug. 22) - Unit testing created for player movement.
- [x] (Aug. 23) - Player movement implemented and tested.
- [x] (Aug. 23) - Updated documentation of player movement on Wiki.
 
**Completion Deadline:** Aug. 24

# **Documentation**
To be completed.
 
# **Members**
Kushagra Agrawal (@kushagra1912) (Kushagra Agrawal)
Rachel Leathers (@racheljadel) (Rachel Leathers)
Aman Gupta (@aman-86 )Aman Gupta)
