### ISSUE TITLE
Refined Player

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#265]
# **Description**
The aim of this feature is to improve:

- Player HUD
- Upgrade Tree
- Weapons
- Powerups

And also implement:
- Sound Effects
- Player Lives

## SubFeatures/components
**Upgrade Tree**
- Implement line colour changes between locked and unlocked nodes (e.g. green-green for unlocked, red-red for locked).
- Visual feedback on a currently equipped item for each slot (e.g. highlighted nodes for equipped)
- Modifying the available materials display to be dynamic.
- Update the window background to be more in line with the Game Design UI goals.
- Refine building hammer tree to support extractors and additional buildables.
- Tooltips: Hover over a node to see its stats, e.g. attack speed/damage etc.

**Weapons**
- Better visuals - holding sprite, Firing animation, Particle effects
- Polished interactions with enemies and obstacles
- Even More Weapons
- Minor Functionality Improvements - Sounds, Ammo

**Player HUD**
- Stylised player HUD, with appearance cohesive with rest of the game
- Health bar display
- Dodge cooldown display
- Player lives (new feature) display 
- Current planet display, more stylised and possibly including current planet sprite

**Sound effects**
- Player walking.
- Player dodging.
- Player has low health.
- Player death screen.
- Player Power Ups 
- Upgrade Tree

**Player Lives**
- Implement player lives stats and variable.
- Create new death screens based on lives left.
- Link the "respawn" button on the death screen to the current game level.
- Ensure the player cannot respawn and must restart game when player's lives reaches zero.

**Powerups**
- Collaboration with Team 2 (Enemy Team).
- Create new powerups "Extra Life", "Double Cross", "Temporary Immunity" and "Damage Increase" which only spawn when an enemy is killed (either 1/15 or 1/6 chance), and "Snap" which spawns when a boss is killed.

# **Dependencies**
- [Player Death](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Death)

# **Milestones**
- [x] (Sep. 28) : [Improved Upgrade Tree](https://github.com/UQcsse3200/2023-studio-2/issues/266) completed.
- [x] (Sep. 28): [Improved Player HUD](https://github.com/UQcsse3200/2023-studio-2/issues/269) completed.
- [x] (Sep. 28): [Player Lives](https://github.com/UQcsse3200/2023-studio-2/issues/276) completed.
- [x] (Sep. 28): [Improved Powerups](https://github.com/UQcsse3200/2023-studio-2/issues/293) 
- [x] (Sep. 28): [Sound Effects](https://github.com/UQcsse3200/2023-studio-2/issues/282) 
- [x] (Oct 3.): [Refined Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/283)

**Completion Deadline:** (Oct. 5)

# **Extras (optional)**
- [ ] Mech suit + Explosive Weapon

# **Documentation**
- [x] [Upgrade Tree](https://github.com/UQcsse3200/2023-studio-2/wiki/Upgrade-Tree)
- [x] [Weapons](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)
- [x] [Powerups](https://github.com/UQcsse3200/2023-studio-2/wiki/Powerups)
- [x] [Sound Effects](https://github.com/UQcsse3200/2023-studio-2/wiki/Sound-Effectsl)

# **Members**
Connor Golin (@connor-golin)
Aman Gupta (@aman-86) (Aman Gupta)
Damian Bellew (@Dammo3) (Damian Bellew)
Daniel van Niekerk(@Daniel-vanNiekerk0)
Rachel Leathers (@racheljadel) (Rachel Leathers)
Kushagra Agrawal (@kushagra1912) (Kushagra Agrawal)
