### ISSUE TITLE
Improved Upgrade Tree

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#266]
# **Description**
**Task:** [Improved Upgrade Tree]().
**Feature:** [Refined Player](#265)

The aim of this task ticket is to improve the base functional Upgrade Tree to enhance user experience. Changes include visual differentiation between node states, improved feedback for equipped items, a dynamic materials display, background UI enhancements, expanded tree capabilities, and informative tooltips for nodes.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] (Sep. 20) - Design / Test Plans created: Dynamic displaying of materials, Equipped items, and line colours designed.
- [x] (Sep. 21) - [Line colour changes](https://github.com/UQcsse3200/2023-studio-2/commit/7f82c1fb5209e1566a92d807d306406ae71bc377) between locked and unlocked nodes, and [dynamic displaying](https://github.com/UQcsse3200/2023-studio-2/commit/e0f09a16203f77e3e13e07cf3f413888c48e8869) of materials complete.
- [x] (Sep. 23) - Equipped weapon/hammer visuals implemented.
- [x] (Sep. 26) - Building hammer upgrades with extractor and new [buildables](#191) implemented.
- [x] (Sep. 27) - Tooltips design and test plan documented on wiki.
- [x] (Sep. 27) - Tooltips implemented
- [x] (Sep. 30) - Background implemented using existing design committee skin, general code/tests polishing complete.
- [x] Sep. 31) - Wiki documentation, Test plan, and UML diagram updated.
 
# **Dependencies**
Buildables & Extractor team: 
- [x] Discussions of balancing of hammer upgrades to cater to the overall game design goals.
- [x] Integrating new buildables (structure picker) into the hammer tree.

**Completion Deadline:** Oct. 5

# **Documentation**
- [Upgrade Tree](https://github.com/UQcsse3200/2023-studio-2/wiki/Upgrade-Tree)
 
# **Member**
- Connor Golin (@connor-golin)
