### ISSUE TITLE
MapConfig Testing and Improvements

### ISSUE THREAD

**Issue by Minirobbo** [UQcsse3200/2023-studio-2#267]
# **Description**
**Feature:** #313 

This task aims to improve the overall useability of the config files with the MapGameArea. It will add tests to ensure entities are being loaded correctly. Additionally, providing functionality to improve other teams experiences for creating new maps and areas.

The MapConfigLoader aims to use folders to store levels, instead of large, hard to test .json files. It will allow for logging and breaks up the loading into parts which can easily be traced to find errors (e.g. when a entities .json file is invalid).

The Saving and loading will build on this by implementing methods to save all the entities and game state to .json files and then seamlessly reload them every time you reload the level.

# **Dependencies**

- None at present
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create MapConfigLoader to allow ease of loading and debugging failed loads. (Sep 17)
- [x] Add tests for MapGameArea to check for loading of entities from config file. (Sep 19)
- [x] Add ability for game saving and loading (Sep 29)
- [x] Improve Sonarcloud code smells and test coverage for Config-related code. (Oct 1)
- [x] Complete documentation for all new code and updating old documentation (Oct 3)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- See [here](https://github.com/UQcsse3200/2023-studio-2/issues/346)
 
# **Member**
- Name (GitHub Username) (Discord Handle)
- Isaac Robinson @Minirobbo (Minirobbo)
