### ISSUE TITLE
Improved Player HUD

### ISSUE THREAD

**Issue by Dammo3** [UQcsse3200/2023-studio-2#269]
# **Description**
**Task:** [Improved Player HUD](#269).
**Feature:** [Refined Player](#265)

Improving the existing player HUD. Create a more stylised appearance which matches other existing UI components (e.g. resource bars). The new HUD will include:
- Health bar display
- Dodge cooldown display
- Player lives (new feature) display
- Current weapon ammo (new feature) display
- Current planet display, more stylised and possibly including current planet sprite

# **Dependencies**
This task depends on the implementation of player lives this sprint
- [x] Player Lives required to be implemented to display information (#276)
- [x] Implementation of ammo in weapons (#283)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design new player HUD (Sep. 19)
- [x] Implement planet image and name display (Sep 23)
- [x] Implement the health and dodge displays (Sep. 25)
- [x] Implement the player lives (Sep. 27)
- [x] Implement ammo display (Sep. 29)
- [x] Fix code smells and completed testing (Oct. 2)
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
tbd
 
# **Member**
Damian Bellew (@Dammo3) (Damian Bellew)
