### ISSUE TITLE
Player can repair walls/gates

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#27]
# **Description**
**Task:** [Players can repair walls](#3).
**Feature:** [Barricades/Wall](#6 )

This subfeature focuses on enabling players to repair damaged walls in the game, enhancing the defensive capabilities of the barricades/walls and prolonging their effectiveness against enemy advances. Repairing walls adds depth to the gameplay by allowing players to maintain defences and protect critical assets, such as the Ship/Extractor.
 

# **Dependencies**
Implement wall ticket(#18 )
Wall Sprite (#9 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Implement Wall Repair Mechanics (Aug. 21)
- [x] Step 2: Wall Repair Logic Integration (Aug. 21)
- [x] Step 3: Player Resources and Feedback (Aug. 22)
- [x] Step 4: Testing and Balancing (Aug. 22)
 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Wall](../wiki/wall)
- [Gate](../wiki/gates)
 
# **Member**
- Khushi Jain(@khushijain0302)

**Comment by rowan-gray** [comment]
Complete
