### ISSUE TITLE
Player Moving Slower

### ISSUE THREAD

**Issue by ManviNarang01** [UQcsse3200/2023-studio-2#271]
# **Description**
The objective of this task is to induce a gradual deceleration effect on the player's movement when navigating particular designated freezing areas on the ice map. This is planned to simulate the challenging conditions of icy terrain, introducing a layer of realism and strategic user experience when moving through the game.

# **Dependencies**

-  #270 Advanced Map Mechanics
-  #309 Player starts taking damage over time 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Modify the speed of the player to be slower throughput initially.(Sep 29)
- [x] Add the gradual slowing of the player. (Sep. 30)
- [x] Introduce the condition of gradual slowing on certain freezing areas. (Oct. 1)
- [x] Finalize the code, push to main (Oct. 3)
 
**Completion Deadline:** October 3rd.

 
# **Member**
- Manvi Narang ( @ManviNarang01 ) (Manvi Narang)
