### ISSUE TITLE
Designing New Maps

### ISSUE THREAD

**Issue by ManviNarang01** [UQcsse3200/2023-studio-2#272]
### Description
Map 3(ice map) and Map 4(fire map) for the game

Description from story team:
-Map 3: "Upon landing, an NPC greets you and shares tales of the planet's unforgiving cold. He equips you with a specialized coat to withstand the extreme temperatures. However, you discover that straying too far from a fire-like component on the map results in your health depleting over time. The head NPC of this planet challenges you to defeat a formidable boss and promises assistance upon your victory. With the boss vanquished, you earn the NPC's support and acquire the Water element, he then guides you towards the next planet."

-Map 4: "In this harsh environment, you meet a mysterious wizard who recognizes your unwavering determination to save Earth. The wizard guides you on your quest for the Fire element and reveals a path to obtain the final cosmic element. After a grueling final boss battle, you claim the Fire element. The wizard reappears, presenting a choice: either revive Earth or make Solarium Ignis a new home for humanity. As you make your decision, the wizard shows you haunting visuals of Earth's devastation. You choose to begin anew on Solarium Ignis." 

### Dependencies
#270 Advanced Map Mechanics 

### Milestones

- [x]  Goal 1 (Sep. 22) demo for new map
- [x]  Goal 2 (Sep. 23) gather feedback on map design, talk to story team
- [x]  Goal 3 (Sep. 27) Finalize the map, push to main

Completion Deadline: September 27th
### Members
-Manvi Narang(@ManviNarang01) (Manvi Narang)
-Samarth Dev Vaish (@SamarthDevVaish) (Samarth Dev Vaish)
