### ISSUE TITLE
Unifying The Game

### ISSUE THREAD

**Issue by neil-nb** [UQcsse3200/2023-studio-2#274]
# **Description**
**Feature:** [Unifying The Game](#274)

I plan to unify the game. My main focus for this sprint is to ensure that the design for all the facets of the game, from enemies to the map and transition between areas (among many other things) is homogenous. My goal is to make it such that the game looks like its own standalone game and not like a game comprised of many elements from other games put together. I also, if I have the ability to, will work with the story team to make a more comprehensive story and more in-depth lore. In summary, my role this sprint is to guide the game towards allowing for a more pleasant experience playing it.

# **Dependencies**
The dependencies I have on this sprint are not ticket-based, but rather co-operation based. I require teams to co-operate with me, or nothing can get done (I can't change the sprite of an enemy if the enemy team refuses to let me, for example).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix ship sprite (again...) and resize hitbox (Sept. 18)
- [x] Fix laboratory's hitbox (Sept. 18)
- [x] Fix companion sprite (Sept. 20)
- [x] Remake astronaut NPC sprite (Sept. 19)
- [x] Make sprites for the Story Team (Sept. 20)
- [x] Make Verdant Haven sprite (Sept. 22)
- [x] Resize enemy sprites and hitboxes, remake bull sprite (Sept. 30)
- [x] Remake main menu screen (Sept. 21)
- [x] Make animated flowers (Sept. 22)

**Completion Deadline:** Oct. 5

 
# **Documentation**
- [Main Menu Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/MAIN-MENU-AND-SETTING-MENU-DISPLAY-CHANGES)
- [Enemy Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Enemies'-Features)
 
# **Member**
- Neil Barigye, Discord: NickBattle1#9383 Github: @neil-nb

**Comment by neil-nb** [comment]
I want to say right now, this is a very overzealous idea of what I could get done in the given timeframe. There is a high likelihood I will make most of these into collaboration tickets (due to their nature), and some may already be being performed by the relevant teams. Additionally, I will add realistic due dates for these as necessary, and I will continue to modify this list as the sprint progresses, making some things extras, and even adding things if I am on top of things.

**Comment by connor-golin** [comment]
Note, player team is working on new player HUD (and updating the current health bar), so dont worry about ' Tweak health stats (bar vs number, etc) () '
