### ISSUE TITLE
Player Lives

### ISSUE THREAD

**Issue by racheljadel** [UQcsse3200/2023-studio-2#276]
# **Description**
**Task:** Player Lives
**Feature:** [Refined Player Feature](https://github.com/UQcsse3200/2023-studio-2/issues/265)

This task aims to implement player lives which will impact the player's death event and the options available to the player after death. Players will initially be given three lives, and with each death, the number of player lives decreases by one. If the player has lives remaining, they are given the choice to restart the level or exit to the main menu. If the player has no lives left, they are only given the option to exit to the main menu and must restart the whole game from the beginning.

# **Dependencies**
- [Player Death](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Death)

# **Milestones**
List of steps that need to be completed for this task.
- [x] (Sep. 18) - Designed player death screens for different lives available.
- [x] (Sep. 20) - Created player lives variable (accessible from multiple classes).
- [x] (Sep. 23) - Link "respawn" button on death screen to correct game level. 
- [x] (Sep. 25) - Unit testing created for player lives.
- [x] (Sep. 26) - Player lives implemented and tested.
- [x] (Sep. 27) - Updated documentation of player lives on wiki.
 
**Completion Deadline:** Sep. 28

# **Extras (optional)**
- [x] Extra life powerups.

# **Documentation**
- [x] [Player Lives Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Lives)
 
# **Members**
Rachel Leathers (@racheljadel) (Rachel Leathers)
