### ISSUE TITLE
Player Sound Effects

### ISSUE THREAD

**Issue by aman-86** [UQcsse3200/2023-studio-2#282]
# **Description**
**Task:** Player Sound Effect
**Feature:** [Refined Player](https://github.com/UQcsse3200/2023-studio-2/issues/265)

This task is meant to to add and update the Player's Sound effects such as creating sound effects while player Health is low,  making subtle walking sound effects, making subtle dodging sound effects, adding death sound effects, etc.
 
## **Example **

- Walking sound - sound effects for player's subtle movement will make the game more interesting. 
- dodging sound - sound of player's dodging will eventually enhance the dodging functionality and the user's experience. 

# **Dependencies**
might need help of Story Team

e.g.
- [x] audio contrast matching with Game theme.  
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Sound effects Player's Low Health (Sep. 20)
- [x] Sound of Player's Dodging (Sep. 21)
- [x] Adding Death sound effects (Sep. 22)
- [x] Adding subtle Walking sound effects (Sep. 23)
- [x] Adding Power-Ups sound effects (Sep. 24)
- [x] Adding sound effects for Upgrade Tree (Sep. 24)
- [x] Adding Java Doc (Sep. 24)
- [x] Updating wiki page (Sep. 24)
- [x] Adding JUnit Testing (Sep. 25) 

**Completion Deadline:** (Sep 28)

# **Documentation**

[Sound Effects](https://github.com/UQcsse3200/2023-studio-2/wiki/Sound-Effects)
 
# **Member**
- Name (@aman-86) (Aman Gupta)

**Comment by aman-86** [comment]
All milestones done in this task ticket.
