### ISSUE TITLE
Refined Weapons

### ISSUE THREAD

**Issue by Daniel-vanNiekerk0** [UQcsse3200/2023-studio-2#283]
# **Description**
**Task:** Refined Weapons
**Refined Player** [Refined Player](https://github.com/UQcsse3200/2023-studio-2/issues/265)

Refined Weapons will be an extension of [Improved Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/144) and will primarily focus on improving and refining already implemented functionality, this will be to:
 - Improve animations further of both attacking and ranged projectiles
 - A better visual holding sprite
 - More verity of weapons along with a focus on on theming them to the game
 
The secondary focus will be to add minor functionality features to weapons being:
 - Ammo functionality
 - Weapon Sounds
 - Firing animation
 - *Optionally an explosive weapon

# **Dependencies**
- As weapons 3 aims to primarily to be an improvement to weapons the main dependency is the existing [weapons implementation](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)

# **Milestones**
List of steps that need to be completed for this task. 
- [x] Implement Minor Functionality (Sep. 20)
- [x] Improve visual holding sprite (Sep. 20)
- [x] Improve animations of existing weapons (Oc.t 1)
- [x] Improve weapon verity keeping each weapon up to a high level of polish (Oct. 3)
 
**Completion Deadline:** Oct. 5

# **Documentation**
- [Weapon Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)
 
# **Member**
- Daniel van Niekerk(@Daniel-vanNiekerk0) (Daniel van Niekerk)
