### ISSUE TITLE
Implement Additional NPC Behaviors and Dialogues

### ISSUE THREAD

**Issue by rachitchaurasia** [UQcsse3200/2023-studio-2#284]
# **Description**
**Task:** Implement new NPCs & add Additional NPC Behaviors and Dialogues.
**Feature:** NPC Improvements.

Implement additional behaviors and dialogues for Non-Player Characters (NPCs) to enhance player interactions. This task involves extending the existing NPC behavior system to include more diverse and engaging interactions with NPCs. It includes creating new dialogue options, actions, and responses for NPCs to make the gameplay experience more immersive and enjoyable.

## **Dependencies**

None

## **Milestones**
List of steps that need to be completed for this task:

- [x] Define additional NPC behaviors and dialogues 
- [x] Implement NPC interactions based on defined behaviors 
- [x] Test and refine NPC interactions for quality and engagement 
- [x] Define additional NPC dialogues according to the story line 

**Completion Deadline:** September 28

# **Documentation**

- [NPC Workflow ](https://github.com/UQcsse3200/2023-studio-2/wiki/NPC's-For-Story-Line)

# **Members**
- Rachit Chaurasia (@rachitchaurasia) (s4823870)
- Dev Gupta (@DRG31) (xdrgx)
- Yash Mittal (@YashMitttal) (s4823869)

**Comment by rachitchaurasia** [comment]
All set.
