### ISSUE TITLE
Create New NPC Entities

### ISSUE THREAD

**Issue by rachitchaurasia** [UQcsse3200/2023-studio-2#285]
# **Description**
**Task:** Create New NPC Entities.
**Feature:** NPC Improvements.

Create new NPC entities to be added to the game. These entities will represent characters or creatures within the game world and will play a role in enhancing player interactions. Each NPC entity should have its own characteristics, behaviors, and interactions with the player.

## **Dependencies**
TBD

## **Milestones**
List of steps that need to be completed for this task:

- [x] Design and define the characteristics of new NPC entities 
- [x] Create and implement the NPC entities in the game 
- [x] Add relevant TextureAtlas with their spritesheets
- [x] Add AnimationController Class for NPCs

**Completion Deadline:** September 28

# **Documentation**

- [NPC Workflow ](https://github.com/UQcsse3200/2023-studio-2/wiki/NPC's-For-Story-Line)

# **Members**
- Rachit Chaurasia (@rachitchaurasia) (s4823870)
- Dev Gupta (@DRG31) (xdrgx)

**Comment by rachitchaurasia** [comment]
Implemented all NPCs into their specific map areas.
