### ISSUE TITLE
Enemies damage the walls/gates

### ISSUE THREAD

**Issue by yuvrajsingh001** [UQcsse3200/2023-studio-2#29]
# **Description**
**Task:** [Enemies damage the walls/gates](#9)
**Feature:** [Walls & Gates](https://github.com/UQcsse3200/2023-studio-2/issues/6)

This sub-feature focuses on allowing enemies to inflict damage to walls/gates in the game in order to attack turrets/extractors to affect players progress of collecting resources.
 

# **Dependencies**
- #9
- #18
- #14

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Implement Wall Damage Mechanics (Aug. 24)
- [x] Step 2: Wall Damage Logic Integration (Aug. 24)
- [x] Step 3: Wall Strength Management (Aug. 25)
- [x] Step 4: Testing and Balancing (Aug. 25)
 
**Completion Deadline:** Aug. 26

 
# **Documentation**
- _to be completed_
 
# **Member**
- Yuvraj Singh (@yuvrajsingh001)

**Comment by rowan-gray** [comment]
Completed
