### ISSUE TITLE
Sliding on frozen map

### ISSUE THREAD

**Issue by zombiechook** [UQcsse3200/2023-studio-2#291]
### Description
This issue will add a mechanic where the player will experience ice physics when walking over certain tiles. This will be implemented on the ice map, on tiles defined in the .tsx file.

### Milestones

- [x]  Goal 1 (Sep. 22) Implement ice physics in player movement
- [x]  Goal 2 (Sep. 26) Make the player slide on particular tiles
- [x]  Goal 3 (Oct. 3) Finalise code, push to main

Completion Deadline: October 3rd
### Members
- Mitchell Hall (@s4697858 ) (Mitchell Hall)
