### ISSUE TITLE
Integrating maps to link with game

### ISSUE THREAD

**Issue by Anshuman0157** [UQcsse3200/2023-studio-2#292]
### Description
This task involves the integration of all maps into the existing game environment to ensure seamless gameplay and consistency with the current assets and mechanics.

### Dependencies
Optimization of code, particularly converting the EarthGameArea into a base class that can be inherited by other planets.

### Milestones

- [x]  Goal 1 (Sep. 22) Map Integration 
- [x]  Goal 2 (Sep. 26) Asset Compatibility
- [x]  Goal 3 (Oct. 3) Gameplay Linkage

Completion Deadline: October 3rd

### Members
- Anshuman Misra (@Anshuman0157 ) (Anshuman Misra)
