### ISSUE TITLE
Improved Powerups

### ISSUE THREAD

**Issue by racheljadel** [UQcsse3200/2023-studio-2#293]
# **Description**
**Task:** Improved Powerups
**Feature:** [Refined Player Feature](https://github.com/UQcsse3200/2023-studio-2/issues/265)

This task aims to improve the powerup feature by implementing various new powerups. 
- `Extra Life`:  Player can get an extra life up to four lives.  There will be a 1/15 chance of an enemy dropping this powerup.
- `Double Cross`: A random enemy will start helping the player for 12s, after which this enemy will die. There will be a 1/6 chance of an enemy dropping this powerup.
- `Temporary Immunity`: Player will gain immunity for 6s. There will be a 1/15 chance of an enemy dropping this powerup.
- `Damage Increase`: Players damage will increase 2x for 12s. There will be a 1/6 chance of an enemy dropping this powerup.
- `Snap`: 50% of the total enemies will be killed. Only spawned when a boss is skilled.

# **Dependencies**
- [Existing Powerups](https://github.com/UQcsse3200/2023-studio-2/wiki/Powerups)
- [Player Lives](https://github.com/UQcsse3200/2023-studio-2/issues/276)

# **Milestones**
List of steps that need to be completed for this task.
- [x] (Sep. 25) - Create new powerups in relevant classes.
- [x] (Oct. 1) - Unit testing created for new powerups.
- [x] (Oct. 2) - Create UI elements like particles and new assets.
- [x] (Oct. 2) - New powerups implemented and tested.
- [x] (Oct. 3) - Updated documentation of powerups on wiki.
 
**Completion Deadline:** Oct. 3

# **Documentation**
- [x] [Powerups](https://github.com/UQcsse3200/2023-studio-2/wiki/Powerups) 

# **Members**
Rachel Leathers (@racheljadel) (Rachel Leathers)
Kushagra Agrawal (@kushagra1912) (Kushagra Agrawal)
Aryaman Tiwari (@Aryamant21)(Aryaman Tiwari)
