### ISSUE TITLE
Heat emitting entities in map

### ISSUE THREAD

**Issue by ArmandoLiebenberg** [UQcsse3200/2023-studio-2#296]
# **Description**
Task: Heat emitting entities in map
Feature: #296

A cold / heat system for the player, for the ice map. This would be a gauge similar to a healthbar that when bottomed out would place a Damage over Time effect on the player. This would be combined with either buildable heat emitters, or natural steam geysers that would allow the player to heat back up.

# **Dependencies**
Cooperation with the Player And possibly the buildables team

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Discuss with the relevant teams (Aug. 22)
- [ ] Create a collaboration ticket (Aug. 22)
- [ ] Implement cold meter system (Aug. 30)
- [ ] Implement steam geyser map entity (Aug. 30)
- [ ] Testing and bugfixing (Oct. 2)
 
**Completion Deadline:** Oct. 2nd

# **Member**
Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)
