### ISSUE TITLE
Customer graphics effects (shaders)

### ISSUE THREAD

**Issue by ArmandoLiebenberg** [UQcsse3200/2023-studio-2#297]
# **Description**
Task:  Customer graphics effects (shaders)
Feature: #297 

Investigate the possibility of interesting rendering effects that synergise with the gameplay.  This would be post processing effects through a shader that operates on the framebuffer.
 
## **Example**
For example custom weather effects, visual item effects, low health visual effects, etc.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Investigate possibly of custom effects in the game engine provided (Aug. 18)
- [x] Research possible effects and build some code as a framework for implementing these (Aug. 20)
- [ ] Implement one or two of these effects, work on a collaboration ticket if these effects synergise with other game features (Aug. 22)
- [ ] Testing and debugging (Aug. 23)
 
**Completion Deadline:** Sept 23th

# **Member**
Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)

**Comment by ArmandoLiebenberg** [comment]
Cannot progress further on feature. Closing task ticket now as incomplete
