### ISSUE TITLE
Pathfinding AI task to be implemented and working for all enemies  (Oct. 4)

### ISSUE THREAD

**Issue by kk4w4i** [UQcsse3200/2023-studio-2#301]
# **Description**
This task will focus on the implementation of the pathfinder class. Prior to this sprint the class outlines the basic logic of the pathfinder. However the class is not catered to the grid layout of the map and is not used in any task in the AIcomponent.

This task will also look at additional functionalities missing from the enemy behvaiours, e.g. halt attack after entity is “disposed” or “broken”, stop moving when the entity dies.
 
# **Documentation**
TBD
 
# **Milestone**
- [x] Complete the pathfinding class. (Sept 22th)
- [x] Create the pathfinding task. (Sept 29th)
- [x] Implement missing behaviors of the enemies (Oct 2)
- [x] Junit tests and functionality testing. (Oct. 2)
 
# **Members**
Firstname Surname (@github) (Discord Handle)
- Theodore Kim (@thoemodachi) (thoemodachi)
- Milo Hunter (@mhUnt3rS) (iavfjbdb#8394)
- Kintaro Kawai (@kk4w4i) (0xkin)
- Ojaswin Kohli (@OjaswinKohli) (ojaswinkohli)
