### ISSUE TITLE
Adding secret areas to 2 new maps

### ISSUE THREAD

**Issue by rike568** [UQcsse3200/2023-studio-2#308]
# **Description**
**Task:** Adding Secret Areas to 2 New Maps
**Feature:** Advanced Map Mechanics #270 

Designing and implementing two new secret areas that will be added to the two new maps that will be created in this sprint. By adding secret areas to the maps, we allow the player to feel a greater sense of exploration when playing the game. Secret areas also allow the plater to use a portal to be transported to the secret area, which creates a exciting and sci-fi like experience. 
 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- #272

e.g.
- [x] The two new maps need to be created before adding the secret areas.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find Assets (Sep. 26)
- [x] Implement Assets (Sep. 29)
- [x] Create new Secret Areas (Oct. 1)
- [x] Add maps to game (Oct. 3)
 
**Completion Deadline:** 5 October 2023
 
# **Member**
- Jordan Singh (@rike568) (Jordan Singh)

**Comment by rike568** [comment]
# **Description**
**Task:** Adding Secret Areas to 2 New Maps
**Feature:** Advanced Map Mechanics #270 

Designing and implementing two new secret areas that will be added to the two new maps that will be created in this sprint. By adding secret areas to the maps, we allow the player to feel a greater sense of exploration when playing the game. Secret areas also allow the plater to use a portal to be transported to the secret area, which creates a exciting and sci-fi like experience. 
 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- #272

e.g.
- [ ] The two new maps need to be created before adding the secret areas.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Find Assets (Sep. 26)
- [ ] Implement Assets(Sep. 29)
- [ ] Create new Secret Areas (Oct. 1)
- [ ] Add maps to game (Oct. 3)
 
**Completion Deadline:** 5 October 2023
 
# **Member**
- Jordan Singh (@rike568) (Jordan Singh)
