### ISSUE TITLE
Player starts taking damage over time

### ISSUE THREAD

**Issue by rike568** [UQcsse3200/2023-studio-2#309]
# **Description**
**Task:** Player Takes Damage Over Time in Advanced Maps
**Feature:** Advanced Map Mechanics #270 

Implementing a design in which in the advanced maps that will be created, that player will start taking environmental damage over time. For the two new maps, one of which will be Ice themed and the other Fire themed, will allow the player to take frozen damage, and heat damage respectively. This will grant the player a greater sense of immersion, and increase the tension whilst playing the game.
 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create new Component to be added to Player Entity(Sep. 26)
- [x] Create new EnvrionmentalDamageComponent to be added to Map (Sep. 29)
- [ ] Integrate with Heater and Cooler Entity so the Player doesn't take damage in certain areas (Oct. 1)
- [ ] Create Tests (Oct. 3)
 
**Completion Deadline:** 5 October 2023
 
# **Member**
- Anshuman Misra (@Anshuman0157 ) (Anshuman Misra)
- Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)
