### ISSUE TITLE
Bug Team Feature Ticket

### ISSUE THREAD

**Issue by mira-alford** [UQcsse3200/2023-studio-2#313]
# **Description**
The plan is to squash a lot of bugs. Some standouts are the: Frequent crashing, inconsistent hitboxes, enemies moving on death, death screen not working, etc.
Additionally, cleanup of the previous sprints features, particularly placing extractors and the level configuration needs to be polished.

# **Dependencies**- 
- No dependencies, this is upstream from almost every other change.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Finish cleaning up the final required extractor features
- [x] Fix the major bugs preventing a playthrough of the game
- [x] Add saving and loading and remove legacy level code

# **Documentation**
No primary documentation, though it can be found in the feature tickets. Additionally various documentation pages and javadocs will be improved as part of bugfixing and code smell cleanup.

# **Members**
- McArthur (@McArthur-Alford )
- Isaac (@Minirobbo

**Comment by mira-alford** [comment]
Pretty much finished
