### ISSUE TITLE
Tutorial Map

### ISSUE THREAD

**Issue by NotRaghavAggarwal** [UQcsse3200/2023-studio-2#319]
# **Description**
**Implementing Map Feature**
**Feature:** #315 (Game Tutorial)

Implement a new map for the tutorial of the game

# **Milestones**
- [x] Get Assets from Map Team 1
- [x] Make a map
- [x] Implement the map in the new Flow/ Config Files
- [x] Add Components for tutorial
- [x] JavaDoc/Wiki

**Completion Deadline:** Aug. ##

# **Documentation**
-Generates a new map by clicking on the tutorial button on the main screen, which has dialogue boxes to tell the player what to do and how to use different controls and available functions on the screen.

# **Member**
- Raghav (@NotRaghavAggarwal ) (Raghav Aggarwal)

**Comment by rowan-gray** [comment]
Completed
