### ISSUE TITLE
Player Assets

### ISSUE THREAD

**Issue by aman-86** [UQcsse3200/2023-studio-2#32]
### **Description**

Task: [Player Assets](https://github.com/UQcsse3200/2023-studio-2/issues/32#20)
Feature: [Player Feature](https://github.com/UQcsse3200/2023-studio-2/issues/13)

The aim of this sub-feature is to design and implement initial assets including and relating to the player, including weapons, and powerups.
This includes creating multiple frames for the Player and Weapon(s) based on the latest movement direction given by `KeyboardPlayerInputComponent`.

### **Example**
- Players Movement - The player will be provided with visual feedback on which way the player is moving as they will see a different sprite for each movement direction (8 Directional movement).
- Attack - The player is provided with visual feedback with an attack in the direction the player is facing.

### **Dependencies**
- [Player Movement](https://github.com/UQcsse3200/2023-studio-2/issues/25) is required in order to test the Player sprite(s).
- [Player Weapons(s)](https://github.com/UQcsse3200/2023-studio-2/issues/35) is required in order to test the Weapon sprite(s).
- [Powerup(s)](https://github.com/UQcsse3200/2023-studio-2/issues/20) is required in order to test the Powerup sprite(s). 

### **Milestones**
- [x] (Aug. 22) - Initial asset designs created and documented on the wiki.
- [x] (Aug. 27) - Player, Weapon, and Powerup assets tested.
- [x] (Aug. 28) - Final documentation of all assets updated on the wiki.

Completion Deadline: Aug. 29

### **Documentation**

- TBD

### **Member**

- Aman Gupta (@aman-86 ) (Aman Gupta)
- Connor Golin (@connor-golin) (Connor Golin)
- Rachel Leathers (@racheljadel) (Rachel Leathers)
