### ISSUE TITLE
Ship Mechanics, Test Cases and Debugging Aspects

### ISSUE THREAD

**Issue by Tarushi263** [UQcsse3200/2023-studio-2#323]
# **Description**
Implementing the launch of the ship, and blast-off animation, and working on the test cases.
A structured debugging process, which may involve logging, testing, and code review, is crucial to ensure that the ship mechanics work seamlessly and that gameplay is free from disruptive bugs, leading to a more enjoyable gaming experience.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Ship Mechanics (Sept. 24)
- [x] Modifying Functionality of Ship Interaction Popup (Sept. 25)
- [x] Fixed Tree Visual Bug #340 (Sept. 27) 
- [x]  Fixed Intro Window Resize Bug #332 (Sept. 27)
- [x]  Slowed down extractor resource production rate (#363) (Sept. 27)
 
**Completion Deadline:** Sept. 27
 
# **Documentation**
TBD
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Tarushi (@Tarushi263) (tarushigera)
