### ISSUE TITLE
Finalise implementation for the Upgrade Space

### ISSUE THREAD

**Issue by AnshulDadhwal** [UQcsse3200/2023-studio-2#324]
# **Description**
Finalise the implementation for the upgrade space

# **Dependencies**
 Currently not
# **Milestones**
- [x] Implement mechanism to get back to the current minigame
- [x] Implement the update mechanism for the spaceship
- [x] Implement the display UI for SpaceShip stat
- [x] Documentation
 
**Completion Deadline:** Oct. 3

# **Member:** 
Vu Khanh Vy Ho ( @VuKhanhVyHo )
Zhen Feng Ting ( @Foref )
