### ISSUE TITLE
Tutorial Interface

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#325]
# **Tutorial Interface**
**Task:** [Design a user tutorial interface](#3).
**Feature:** [Game Tutorial](#315 )

This ticket aims to design a user tutorial interface for the game, aiming to enhance the overall gaming experience by providing players with essential information and guidance on how to play the game effectively. The user tutorial will be presented as a pop-up window that appears at the beginning of the game or can be accessed from the game's main menu.

###  Components:

- User Tutorial Interface Design
- Design of Tutorial Content Layout
- Visual Style and Graphics
- Navigation and Interactive Elements

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: User Tutorial Interface Concept Design
- [x] Step 2: Interface Prototype
- [x] Wiki Documentation

 # **Deadlines**
List of steps that need to be completed for this task.
- [x] Step 1: Call a new Screen using the buttons on the main menu screen.
- [x] Step 2: Add required entities 
- [ ] Step 3: Call it before the main game.

# **Member**
Raghav Aggarwal @NotRaghavAggarwal- Raghav Aggarwal

**Comment by rowan-gray** [comment]
Delayed until next sprint

**Comment by NotRaghavAggarwal** [comment]
Halfway Implemented, Not Complete.

**Comment by rowan-gray** [comment]
Scrapped for this sprint
