### ISSUE TITLE
Game Tutorial Content 

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#326]
### **Game Tutorial Content** 
**Task:** [Game Tutorial Content Creation](#3).
**Feature:** [Game Tutorial](#315 )

The objective of this ticket is to create informative tutorial content and text that will be displayed within the game tutorial interface. The content will effectively guide players on how to play the game, covering essential gameplay elements, controls, and mechanics. 

### **Components:**
- Text and Descriptions
- Visual Assets
- Interactive Elements

# **Milestones**
List of steps that need to be completed for this task.
- [x] Goal 1:Content Outline and Structure
- [x] Goal 2:Tutorial content text
- [x] Goal 3:Visual Assets Integration
- [x] Goal 4:Documentation
  
# **Member**
- Khushi Jain @khushijain0302 
- Raghav Aggarwal @NotRaghavAggarwal Raghav
- Yash Mittal (@YashMitttal} (s4823869)
- Rachit Chaurasia (@rachitchaurasia) (s4823870)

**Comment by NotRaghavAggarwal** [comment]
Completed
