### ISSUE TITLE
Game Tutorial Triggers Implementation

### ISSUE THREAD

**Issue by khushijain0302** [UQcsse3200/2023-studio-2#327]
### **Triggers Implementation**
**Task:** [Game Tutorial Triggers Implementation](#3).
**Feature:** [Game Tutorial](#315 )

The aim of this ticket is to implement triggers within the game that will determine when and how the tutorial is displayed to players.
  
# **Milestones**
List of steps that need to be completed for this task.
- [x] Goal 1:Trigger Design and Integration with Game Logic
- [ ] Goal 2: Testing and Documentation
- [ ] Goal 3: Feedback and optimization
 
# **Member**
@khushijain0302

**Comment by rowan-gray** [comment]
Delayed until next sprint

**Comment by rowan-gray** [comment]
Scrapped for this sprint
