### ISSUE TITLE
Planet Screen: Multiple Game Areas

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#329]
# **Description**
**Task:** [Planet Screen: Multiple Game Areas].
**Feature:** [Space + Planet Updating] (#417)

A singular planet should have the ability to support multiple separate game areas that act as additional places to explore, such as caves or mountaintops, as such the Planet Screen needs to be updated to facilitate this and to make it as simple and user-friendly as possible.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Remove depreciated `EarthGameArea` and only use `MapGameAreas` (Sep. 15)
- [x] Design framework to create additional game areas. (Sep. 16)
- [x] Create storage method for game areas and their lookup values (names of areas. (Sep. 16) 
- [x] Implement helper methods to make it easy to create additional game areas. (Sep. 17)
 
**Completion Deadline:** Sep. 17

 
# **Documentation**
This documentation is extended upon from the last sprint to reflect new changes and additions.
- [Planet Screen](https://github.com/UQcsse3200/2023-studio-2/wiki/Planet-Screens)
 
# **Member**
- Henry Batt @henrybatt
