### ISSUE TITLE
Gathering Assets First Level - Map

### ISSUE THREAD

**Issue by rike568** [UQcsse3200/2023-studio-2#33]
# **Description**
The purpose of this is to gather assets that can deeply immerse the player into the world of the game. The map will use assets to form the base environment in which the player roams around in. The assets will need to be in sync with direction of the game to create a cohesive story.

# **Dependencies**
- The direction of the story as chosen by the Story Team

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 (Aug. 19) Team to gather various assets individually
- [x] Goal 2 (Aug. 22) Discussion of assets the best fit theme of the game
- [x] Goal 3 (Aug. 23) Team to gather assets similar to design agreed upon
- [x] Goal 4 (Aug. 24) Finalisation of assets

**Completion Deadline:** Aug. 25

# **Documentation**
- TBD

# **Members**
- Jordan Singh (@rike568) (Jordan Singh)
- Mitchell Hall (@s4697858 ) (Mitchell Hall)
- Anshuman Misra (@Anshuman0157 ) (Anshuman Misra)
- Samarth Dev Vaish (@SamarthDevVaish) (Samarth Dev Vaish)
- Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)
- Manvi Narang(@ManviNarang01) (Manvi Narang)
