### ISSUE TITLE
Enemy Sounds Effects 

### ISSUE THREAD

**Issue by aman-86** [UQcsse3200/2023-studio-2#334]
# **Description**
**Task:** [Enemy Sound Effects]
**Feature:** [Refined Player](#241 ) / [Enemy](#265 )

This is a collaboration Tasks ticket between Player and Enemy Team, which is meant to implement Enemy Sound Effects. This will add multiple sounds effects for different types of enemies. 
 
# **Dependencies**

- [x] (#265  )
- [x] (#299   )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create generic sound component (Sep. 23)
- [x] Add boss enemy death sound effects (Sep. 23)
- [x] Add boos enemy spawn sound effects (Sep. 26)
- [x] Add java doc(Sep. 27)
- [x] Add Junit testing (Sep. 30)

**Completion Deadline:** Sep. 3

 
# **Documentation**
- [Sound Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Sound-Component)
 
# **Member**
- (aman-86) (Aman Gupta)
- Rowan (@rowan-gray)
