### ISSUE TITLE
Companion Sound Effects

### ISSUE THREAD

**Issue by aman-86** [UQcsse3200/2023-studio-2#335]
# **Description**
**Task:** Companion Sound Effects
**Feature:**  [Refined Player](#265) / [Companion]( #238 )

This is a collaboration Tasks ticket between Player and Companion Team, which is meant to implement Companion Sound Effects. This will add multiple sounds effects for companion. 
 
# **Dependencies**

- [x]  (#265 )
- [x]  (#238 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add companion walking  sound effects (Sep. 23)
- [x] Add java doc(Sep. 27)
- [x] Add JUnit testing (Sep. 30)

**Completion Deadline:** Sep. 3

 
# **Documentation**
- [Main description of feature] - TBD
- [JavaDoc] - TBD
 
# **Member**
-  (aman-86) (Aman Gupta)
- Atharva (@atharvagupta2003)
