### ISSUE TITLE
Unify Powerups & Potions

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#344]
# **Description**
**Task:** [Unify Powerups & Potions]().

The aim of this collaborative ticket is to reduce code duplication by unifying powerups and potions. This will ensure code is more easily maintained and modular.
 
# **Dependencies**

- PowerupComponent, PowerupFactory
- PotionComponent, PotionFactory
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] (Sep. 26): PotionComponent merged into PowerupComponent.
- [x] (Sep. 26): Redundant Potion classes removed.
- [x] (Sep. 27): Related Potion unit testing merged into Powerup tests. 

 
**Completion Deadline:** Sep. 30

 
# **Member**
- Name (GitHub Username) (Slack Handle)
Connor (@connor-golin)
Atharva (@atharvagupta2003)
