### ISSUE TITLE
Game Saving and Loading

### ISSUE THREAD

**Issue by Minirobbo** [UQcsse3200/2023-studio-2#346]
# **Description**
**Feature:** #267

This collaboration is to design and implement a saving and loading mechanism - building upon the config system created in the previous sprint. All entities in a game area should be saved to a file and this file can be reloaded to allow for exiting and reenturing areas or reloading a game. Additionally, the global state needs to be saved to allow for global saving and loading, i.e what current level the player is on, etc.

# **Dependencies**

- None at this time
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Saveable Component to attach to all entities
- [x] Create Method to collect all entities and use saveable components to save game area to file
- [x] Implement Saveable Component onto some / all current entities.
- [x] Implement ability to save global game state to provide game saving and loading.
- [x] Create interface for loading in previous saves.
- [x] Documentation on use for other developers.
- [ ] Testing for classes to ensure correct saving / loading
 
**Completion Deadline:** Oct 1.
 
# **Documentation**
- [Saveable Component](../wiki/Saveable-Component)
- [Loading Config Files with json](../wiki/Loading-Configuration-classes-with-json)
- [Game and Entity Config files](../wiki/Game-and-Entity-Configuration-Files)
 
# **Member**
- Name (GitHub Username) (Discord Handle)
- Isaac R @Minirobbo Minirobbo
- Henry @henrybatt Henry
