### ISSUE TITLE
Player Weapon/s

### ISSUE THREAD

**Issue by Daniel-vanNiekerk0** [UQcsse3200/2023-studio-2#35]
# **Description**
**Task:** [Player Weapon](#3).
**Feature:** [Player Feature](#2)

This task will be the core implementation of weapons for the player, this includes the creation of a base class with required attributes and functions for weapons, the class will be usable for both melee and ranged weapons. Along with this will be the concrete implementation of an initial melee weapon (and if permitted a ranged weapon).

## **Example**
- **Melee Weapons**: The player will be able create a projectile that travels in an arc damaging enemies
- **Non-Melee Weapon**: The player will be able to spawn a projectile that affects enemies upon contact.

# **Dependencies**
- [x] Player Stats (# ) These will be used for attack calculations
 
# **Milestones**
- [x] (Aug. 23) - Creation of base weapon factory used to create entities
- [x] (Aug. 26) - Creation of component to respond to player attacks 
- [x] (Aug. 28) - Implementation of First projectile and melee weapon projectile movements.
- [x] (Aug. 30) - Finalising Testing of weapon implementation
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Player Weapon Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)
 
# **Member**
- Name (@Daniel-vanNiekerk0) (Daniel van Niekerk)
