### ISSUE TITLE
Particle Effects System

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#350]
# **Description**
The goal for this feature is to implement a generic and reusable Particle Effect system which can be used throughout the game to provide further depth to the visual style.

## **Examples**
- **Explosion** - particle effects will allow for explosions to be created which could be used for future Turret variants or landmines in the future.
- **Enemy Death** - particle effects could be used to provide more visual variety in enemy deaths.

## **Plan**
This system will use the LibGDX ParticleEffect class for drawing particles. This also allows us to use the pre-existing particle editor tool.

The plan is to add a LoadParticleEffects method to the ServiceLocator so that it can be loaded the same way that other assets can be. Loading particle effects will also need to be added to the GameArea and its config file to allow them to be loaded through configs using the current system.

A component/set of components will then be used to be able to begin and stop each effect. An event driven system will be used to allow other components to start a particle while maintaining a level of abstraction. This will ensure dependencies remain low.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Add LoadParticleEffects to the ServiceLocator
- [x] Allow for a list of particle effects to be loaded via the GameArea config files
- [x] Implement a ParticleComponent to allow for particles to be triggered
- [x] Implement a particle effect into the game as a proof of concept
- [x] Testing
- [x] Javadoc's
- [x] Documentation

**Completion Deadline:** Sep. 29

# **Documentation**
- [Particle Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Particle-Effects)

# **Members**
- Rowan Gray (@rowan-gray)

**Comment by rowan-gray** [comment]
Idk why I closed this since I still need to do testing and documentation

**Comment by rowan-gray** [comment]
Completed
