### ISSUE TITLE
Sound Component

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#351]
# **Description**
The goal for this feature is to implement a generic and reusable Sound Effect system which can be used throughout the game to provide further depth.

## **Examples**
- **Walking sound** - a walking sound can be played whenever the player moves
- **Enemy sounds** - enemies can make sounds when they attack or have idle sounds

## **Plan**
This system will use the LibGDX Sound class for managing the playback of sounds.

A component/set of components will then be used to be able to begin and stop each sound. An event driven system will be used to allow other components to start a sound while maintaining a level of abstraction. This will ensure dependencies remain low.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Add a SoundsConfig file which can be used to define which sounds can be played.
- [x] Implement a SoundComponent to allow for sounds to be triggered
- [x] Add the SoundsConfig to the different entity config files which will play sounds.
- [x] Refactor the existing player sounds to utilise the new component
- [x] Testing
- [x] Javadoc's
- [x] Documentation

**Completion Deadline:** Sep. 29

# **Documentation**
- [Sound Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Sound-Component)

# **Members**
- Rowan Gray (@rowan-gray)
- Yugansh Pancholi (@Yugansh-Uq)

**Comment by rowan-gray** [comment]
Testing done in pull request https://github.com/UQcsse3200/2023-studio-2/pull/377

**Comment by rowan-gray** [comment]
Completed
