### ISSUE TITLE
Extractor Particle Effects

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#352]
# **Description**
**Feature:** [Extractors](#50)

The goal of this ticket is to implement mining particle effects when the extractor is running. This will provide more visual clarity for the user and make the extractor more engaging to interact with.
 
# **Dependencies**
- [x] #350
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a rubble particle effect
- [x] Implement the rubble particle effect into the game using the ParticleComponent
- [x] Make the rubble particle effect only play when the extractor is turned on
 
**Completion Deadline:** Oct. 1
 
# **Documentation**
- [Extractor](../wiki/Ship-and-Extractors)
 
# **Member**
- Rowan Gray (@rowan-gray)
- McArthur Alford (@McArthur-Alford)

**Comment by rowan-gray** [comment]
Delayed until Sprint 4 due to time constraints and since this isn't a vital part of game play. Other tickets took priority.

**Comment by rowan-gray** [comment]
Completed and merged with pull request https://github.com/UQcsse3200/2023-studio-2/pull/497.
