### ISSUE TITLE
Explosives

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#353]
# **Description**
The goal of this feature is to implement explosives which can be set off in a variety of ways. This will add more depth to the game loop since it will provide additional ways to protect yourself and the extractors against enemies, however, they will also use up the same resource (fuel) which the player requires to escape the planet. This means the player will have to decide on a good tradeoff between protecting the extractors and themselves and delaying their escape or saving their fuel to leave sooner.

## SubFeature/component (optional)
- Explosive Barrels - these will be barrels full of fuel which can be detonated by the flaming boomerang or set off by surrounding explosives.
- Landmines - these will be hidden explosives which set off when an enemy steps over it.
- Grenades - these will be a throwable explosive which will set off after an elapsed time.

# **Dependencies**
- #350 
- #351

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create an explosion component which will damage surrounding entities when triggered. It should allow for custom size and damage for different explosives.
- [x] Implement the particle effects which the explosion component can trigger.
- [x] Implement the sound effects which the explosion component can trigger.
- [x] Create a config file for the different explosives.
- [x] Implement the different explosive structures the player can place/throw.
    - [x] #362
    - [x] #361
    - [x] #360
- [x] Create the assets for the different explosives.
- [x] Javadocs
- [x] Testing
- [x] Documentation

**Completion Deadline:** Oct. 3

# **Documentation**
- [Explosive Gameplay](https://github.com/UQcsse3200/2023-studio-2/wiki/Explosives-Gameplay)
- [Explosive Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Explosive-Component)
- [Sound Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Sound-Component)
- [Particle Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Particle-Effects)

# **Members**
- Rowan Gray (@rowan-gray)
- Yugansh Pancholi (@Yugansh-Uq)

**Comment by rowan-gray** [comment]
Completed
