### ISSUE TITLE
Wall Sound Effects 

### ISSUE THREAD

**Issue by aman-86** [UQcsse3200/2023-studio-2#358]
# **Description**
**Task:** Wall sound Effects
**Feature:** [Refined Player](#265 ) / [Sound Component](#351 )

This task is meant to to add and update the Walls's Sound effects such as creating sound effects while walls heal,  sound effects of turrets, etc. 
 

# **Dependencies**

- [x] Refined Player (#265 )
- [x] Sound Component (#351 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add Wall heal Sound Effects (Sep. 27)
- [x] Add Java docs (Sep. 29)
- [x] Add JUnit Tests  (Sep. 30)
 
**Completion Deadline:** Sep. 3

 
# **Documentation**
- [Sound Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Sound-Component)

# **Member**
-  (aman-86) (Aman Gupta)
-  (@Yugansh-Uq) (Yugansh Pancholi)
