### ISSUE TITLE
Grenade

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#360]
# **Description**
**Feature:** #353 

The purpose of this task ticket is to implement a player throwable explosive in the form of a grenade which will explode after a predefined period of time has elapsed. This grenade will have the ability to set off surrounding explosives, such as explosive barrels, to add further depth to the feature.

# **Dependencies**
- [x] [ExplosiveComponent](#353)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new weapon which will spawn a grenade and launch it in the direction of the click.
- [x] Implement Grenade assets
    - [x] Explosion sound
    - [x] Explosion effect
    - [x] Grenade image
- [x] Make it so that the grenade will detonate after a delay using the ExplosiveComponent.
 
**Completion Deadline:** Oct. 2

# **Documentation**
- [Explosive Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Explosive-Component)
- [Explosive Gameplay](https://github.com/UQcsse3200/2023-studio-2/wiki/Explosives-Gameplay)
 
# **Member**
- Rowan (@rowan-gray)
- Connor (@connor-golin)
- Yugansh (@Yugansh-Uq)

**Comment by rowan-gray** [comment]
Completed
