### ISSUE TITLE
Landmine

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#361]
# **Description**
**Feature:** #353 

The purpose of this task ticket is to implement a placeable landmine explosive which will explode when an enemy steps over it. The landmine will have the ability to set off surrounding explosives, such as explosive barrels, to add further depth to the feature (e.g. setting up booby traps for the enemies).

# **Dependencies**
- [x] [ExplosiveComponent](#353)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new placeable structure for the landmine.
- [x] Find and implement landmine assets.
    - [x] Explosion sound
    - [x] Explosion effect
    - [x] Landmine animation (blinking light)
- [x] Make it so that the landmine will detonate when an entity steps on it.
 
**Completion Deadline:** Oct. 2

# **Documentation**
- [Explosive Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Explosive-Component)
- [Explosive Gameplay](https://github.com/UQcsse3200/2023-studio-2/wiki/Explosives-Gameplay)
- [Proximity Trigger Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Proximity-Trigger-Component)
 
# **Member**
- Rowan (@rowan-gray)
- Yugansh (@Yugansh-Uq)

**Comment by rowan-gray** [comment]
Completed
