### ISSUE TITLE
Explosive Barrel

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#362]
# **Description**
**Feature:** #353 

The purpose of this task ticket is to implement a placeable explosive barrel which will explode when another explosive is detonated near it. The explosive barrel will have the ability to set off surrounding explosives, such as other explosive barrels, to allow explosions to chain and add further depth to the feature (e.g. setting up booby traps for the enemies).

# **Dependencies**
- [x] [ExplosiveComponent](#353)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new placeable structure for the explosive barrel.
- [x] Find and implement explosive barrel assets.
    - [x] Explosion sound
    - [x] Explosion effect
    - [x] Explosive barrel image 
- [x] Make it so that the explosive barrel will detonate when surrounding explosives detonate.
 
**Completion Deadline:** Oct. 2

# **Documentation**
- [Explosive Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Explosive-Component)
- [Explosive Gameplay](https://github.com/UQcsse3200/2023-studio-2/wiki/Explosives-Gameplay)
 
# **Member**
- Rowan (@rowan-gray)
- Yugansh (@Yugansh-Uq)

**Comment by rowan-gray** [comment]
Completed
