### ISSUE TITLE
Extractor/Buildables upgrades

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#366]
# **Description**
**Task:** [Extractor/Buildables upgrades]().
**Feature:** [Refined Player](#265)

The aim of this collaborative ticket is to enhance the current StructurePicker and Upgrade Tree functionalities to maintain game progression and balance. This will involve coordination among the Extractors, Buildables, and Player teams to discuss and implement balance adjustments relating to base weapons, extractors, and buildables.

Currently, you can upgrade your hammer within the tree to level up the Structure picker (unlocking more buildables) - however, this does not integrate well, as multiple buildables are unlocked at once rather than one at a time. Therefore, individual nodes containing each buildable (Walls, Gates, Turrets) will be individually unlockable through the upgrade tree.

# **Dependencies**

- [x] [Buildables implemented](https://github.com/UQcsse3200/2023-studio-2/issues/6)
- [x] [Upgrade tree implemented](https://github.com/UQcsse3200/2023-studio-2/issues/121)
- [x] [Extractors implemented](https://github.com/UQcsse3200/2023-studio-2/issues/160)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Extractor progression finalised with Team 5 discussions (Sep. 24)
- [x] Buildables progression finalised with Team 7 discussions (Sep. 24)
- [x] StructurePicker class and config files modified to store unlocked buildables (Sep. 25)
- [x] Unlockable buildables (Walls, Gates, Turrets) integrated with Upgrade Tree (Sep. 27)
- [x] Buildables redundant code (levelling system) removed. (Sep. 29) 
 
**Completion Deadline:** Sep. 28

# **Documentation**
- [Upgrade Tree](https://github.com/UQcsse3200/2023-studio-2/wiki/Upgrade-Tree)
- [StructureToolPicker](https://github.com/UQcsse3200/2023-studio-2/wiki/StructureToolPicker)
 
# **Members**
- Connor (@connor-golin)
- Rowan (@rowan-gray)
- McArthur (@McArthur-Alford)

**Comment by rowan-gray** [comment]
Completed
