### ISSUE TITLE
Explosives - Upgrade Tree integration

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#367]
# **Description**
**Task:** [Improved Upgrade Tree](#266).
**Feature:** [Refined Player](#265)

The aim of this task ticket is to integrate newly created explosive weapons and buildables into the Upgrade Tree. This will require discussions on implementation, balancing and progression with Team 7.

# **Dependencies**

Explosives (#353)  (Buildables, Weapon) will be required in order to be integrated with the Upgrade Tree:
- [x] Explosive Barrel
- [x] Landmine
- [x] Grenade

 
# **Milestones**
- [x] Explosive Barrel and Landmine Implemented as buildables (Sep. 27)
- [x] Explosive Barrel and Landmine integrated with upgrade tree (Sep. 28)
- [x] Grenade parabolic path weapon controller created (Sep. 30)
- [x] ExplosionComponent added with grenade to explode after its duration ends (Sep. 30)
- [x] Grenade added to Upgrade Tree (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Upgrade Tree](https://github.com/UQcsse3200/2023-studio-2/wiki/Upgrade-Tree)
 
# **Member**
- Connor (@connor-golin)
- Rowan (@rowan-gray)
- Daniel (@Daniel-vanNiekerk0)

**Comment by rowan-gray** [comment]
Completed
