### ISSUE TITLE
Extractor Repair Mini Game Feature

### ISSUE THREAD

**Issue by JunxianHuang** [UQcsse3200/2023-studio-2#37]
# **Description**
This feature seeks to implement a minigame based on Clicking for Repairing where the player is expected to click on the damaged part that will be highlighted on the repair interface for increasing the difficulty for the player in the main game. Although this is easy for the player, like those found in among us mini-games, it increases the player's tension (they need to complete the repair as quickly as possible because they don't have time to worry about anything else while they're repairing it and they have to do it or they will not get their necessary resources from it).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Simple game model  (Aug. 20)
- [x] Extra rules (E.g. Punishment when a player makes a mistake）(Aug. 23)
- [x] Implementation of additional in-game features（E.g. Progress bar） Aug. 26)
- [x] Implementation of additional out-game features （E.g. Progress saved）(Aug. 27)
- [x] JUnit Tests (Aug. 28)

**Completion Deadline:** Aug. 30

# **Documentation**
[ExtractorMinigameWindow.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/ExtractorMinigameWindow.java)

 [ExtractorMiniGameArea.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/areas/ExtractorMiniGameArea.java)

[ExtractorMiniGameScreen.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/screens/ExtractorMiniGameScreen.java)

partly in[StructureFactory.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/entities/factories/StructureFactory.java)

[ExtinguisherInputComponent.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/input/ExtinguisherInputComponent.java)

[FireInputComponent.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/input/FireInputComponent.java)

[HoleInputComponent.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/input/HoleInputComponent.java)

[SpannerInputComponent.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/input/SpannerInputComponent.java)

[ExtractorRepairPartComponent.java](https://github.com/UQcsse3200/2023-studio-2/blob/4a419f32f3c15b008141d348d5cc6cca439e193c/source/core/src/main/com/csse3200/game/components/ExtractorRepairPartComponent.java)

# **Junit test**

[ExtractorWindowTest.java](source/core/src/test/com/csse3200/game/ExtractorWindowTest.java)

[ExtractorGameAreaTest.java](source/core/src/test/com/csse3200/game/areas/ExtractorGameAreaTest.java)

[ExtractorScreenTest.java](source/core/src/test/com/csse3200/game/screens/ExtractorScreenTest.java)

[ExtinguisherInputComponentTest.java](source/core/src/test/com/csse3200/game/input/ExtinguisherInputComponentTest.java)

[FireInputComponentTest.java](source/core/src/test/com/csse3200/game/input/FireInputComponentTest.java)

[HoleInputComponentTest.java](source/core/src/test/com/csse3200/game/input/HoleInputComponentTest.java)

[SpannerInputComponentTest.java](source/core/src/test/com/csse3200/game/input/SpannerInputComponentTest.java)

# **Members**
-Anshul Dadhwal (@AnshulDadhwal)
-Zhen Feng Ting (@Foref)
-Manpreet Singh (@Manpreetingh)
-Arsh Upadhyaya (@mr-popo123)
-Junxian Huang (@JunxianHuang)
