### ISSUE TITLE
Player Hotbar UI

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#371]
# **Description**
**Task:** [Player Hotbar UI]().
**Feature:** [Refined Player](#265)

The aim of this task ticket is to implement an `InventoryDisplayComponent` to provide players with a visual representation of their equipped weapons in the inventory. The `InventoryDisplayComponent` inherits from `UIComponent` and populates a table with buttons representing each weapon. Each button provides visual cues about the weapon's status, whether it's currently equipped or not. Listeners are added to handle inventory changes and update the UI accordingly.

# **Dependencies**
- [x] `InventoryComponent` class and associated weapon configs.

# **Milestones**
- [x] Design and inspiration documented on wiki (Sep. 30).
- [x] Implement event listeners for inventory changes (Sep. 30).
- [x] Table populated with weapon buttons and equipped status visuals (Sep. 30).
- [x] `InventoryDisplayComponent` [unit tests and visual testing](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Inventory-Testing-Plan#test-plan-for-inventorydisplaycomponent) complete and documented on wiki (Oct. 1).

**Completion Deadline:** Oct. 2

# **Documentation**
- [Player Inventory](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Inventory)

# **Member**
- Connor Golin (@connor-golin)
