### ISSUE TITLE
Design Companion Asset and Initialise

### ISSUE THREAD

**Issue by atharvagupta2003** [UQcsse3200/2023-studio-2#38]
# **Description**
This task is to gather assets that can deeply immerse the user further in the game through a visually appealing companion. The assets of the companion need to match in style of the assets of the environment. This will change from each environment. Furthermore, the asset must be placed on the map.
 
# **Dependencies**
- [] Map (#4 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Download any sprite/entity skin (Aug. 19)
- [ ] Create companion entity with location on map (Aug. 20)
- [ ] Give companion entity a visual skin/avatar that has been downloaded (Aug. 23)
- [ ] Run game and show map with entity on it (Aug. 24)
 
**Completion Deadline:** Aug. 24
 
# **Documentation**
- TBD
 
# **Member**
- Maxwell (MaxwellSchroder) (@MagWell)
- Saakshi Gupta (saakshigupta2002) (@saakshigupta)
- Daksh Jain (Daksh2607) (@daksh_52443)

**Comment by MaxwellSchroder** [comment]
Lets reduce the number of team members working on this to 2, ideally
