### ISSUE TITLE
Companion Defence and Shields

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#383]
# **Description**
Task: (#383)
Feature: (#384)

The companion should be able to easily switch into defence mode, which gives it the ability to have a floating shield rotate around the companion. This shield will deal damage to close enemies, and in future versions will heal the player passively when it is being used (on).

 
## **Example (optional)**
- **Defend** the companions main objective is to protect the player

# **Dependencies**
NONE
 
# **Milestones**
List of steps that need to be completed for this task.
Something like Define the modes we want, create a general class to invoke the changes, link the general changing to the companion, link keyboard input to the companion, add timers.
- [x] Step 1 (Oct. 1) Define what the companion defence mode should be
- [x] Step 2 (Oct. 2) Implement the mode in the config file, to be saveable.
- [x] Step 3 (Oct. 3) Implement the shield functionality and let it get placed on the map.
 
**Completion Deadline:** 3pm Oct 4.

Milestones were not met, due to a change in design choices. Time was a massive factor, and there were merge conflicts when using the players weapons class. Therefore, we created our own CompanionWeaponConfig, CompanionWeaponTargetComponent, ComponionWeaponFactory, etc.

- [] Step 1 (Oct. 1) Define what the companion defence mode should be
- [] Step 2 (Oct. 2) Implement the defence shield mode, however it encounters merge conflicts
- [] Step 3 (Oct. 3) Adjust the defence shield mode to use the new CompanionWeaponFactory and not a dedicated ShieldFactory. Required some re-factorisation of the existing code, because it was designed for one potion
- [] Step 4 (Oct 4) Call the creation of the shield whenever you enter "Defence" mode
Deadline 2pm Oct 4.
 
# **Documentation**
General companion documentation: [Companion](https://github.com/UQcsse3200/2023-studio-2/wiki/Companion)

 
# **Member**
- Gaurika diwan(@gaurikadiwan )
- Maxwell Schroder (@MaxwellSchroder)
