### ISSUE TITLE
Companion Elevated In-Game Interaction

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#384]
# **Description**
Feature ticket of sprint 3 adds in new functionality never seen before in the game, and it will elevate the usefulness of the companion.

## SubFeature/component (optional)
We are finishing the updated alerts UI to track the companion in real time and look more animated. (#221)
We are adding in more laboratory features such as more potions and different effects (#368)
Defence and Shields (#383)
Armour
Healing the player

# **Dependencies**
None

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 (Sep 25) Assign tasks between team members.
- [x] Goal 2 (Oct. 1) Finish off the updated UI and alerts
- [x] Goal 3 (Oct. 2) Finish Defence and Shield
- [x] Goal 4 (Oct 3-4) Minor bug fixed and changes before finishing sprint 3

**Completion Deadline:** Thursday 3pm Oct 5.

# **Extras (optional)**

# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion

# **Members**
- Name (GitHub Username) (Discord Handle) -- only one is needed if they are the same.
- Maxwell (MaxwellSchroder) (@Magwell)
- Saakshi Gupta (saakshigupta2002) (@saakshigupta)
- Atharva Gupta (atharvagupta2003) (@atharva0179)
- Daksh Jain (Daksh2607) (@daksh_52443)
- Raghavendra Singh Gulia (RagGul)(tantrik8119)
- Gaurika Diwan(gaurikadiwan)(@gaurikadiwan_03168)

**Comment by MaxwellSchroder** [comment]
Finished sprint 3 and implemented desired features
