### ISSUE TITLE
Companion Health Potion Throwing

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#388]
# **Description**
**Task:** Companion Death Potion Throwing
**Feature:** #384 
This implementation adds weapon for the companion and it can shoot out death potion(a poisonous potion with mass killing effect).

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct 3) Implementation of weapon classes and attack factory
- [x] Step 2 (Oct 3) creation of atlas file and png for death potion 
- [] Step 3 (Oct 4) implementing a target algorithim to trace out the position of enemies
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
- Atharva Gupta (atharvagupta2003) (@atharva0179)
- Daksh Jain (Daksh2607) (@daksh_52443)
