### ISSUE TITLE
Companion Movement

### ISSUE THREAD

**Issue by atharvagupta2003** [UQcsse3200/2023-studio-2#39]
# **Description**
**Task:** [Companion Movement](#3).
**Feature:** [Basic Companion Initialisation](#2)

Implimenting basic movement on the map for the companion entity. It should move around a given point on the map, but never cross over that point. It should maintain a minimum distance and a maximum distance, and have a seemingly random path within that area. 
 

# **Dependencies**
- [] Map (#4 )
- [] Companion (#38 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 - Establish minimum and maximum distance to an arbitrary point on map (Aug. 26)
- [ ] Step 2 - Create autonomous movement of the companion within a the bounds (Aug. 28)
- [ ] Step 3 - Create speed variables to adjust the companions speed (Aug. 29) 
**Completion Deadline:** Aug. 29

# **Documentation**
- TDB
 
# **Member**
- Maxwell (MaxwellSchroder) (@MagWell)
- Atharva Gupta (atharvagupta2003) (@atharva0179)
