### ISSUE TITLE
Adjust Companion UI

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#391]
# **Description**
**Task:** Adjust Companion UI
**Feature:** #384 
The companion UI is not consistent with the game theme. Must be modified and changed.

# **Dependencies**
NONE
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct 3) Determine the location of the new UI component, and get some basic placement of objects for the companion there
- [x] Step 2 (Oct 3) Add in adjustable health bars to match the theme
- [ ] Step 3 (optional Oct 4) Add in sprites for attack and defence mode (Never completed, was not that important and did not add signficant value to the game)

 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
- 
 
# **Member**
- Maxwell (MaxwellSchroder) (@MaxwellSchroder )
