### ISSUE TITLE
New Boss Creation

### ISSUE THREAD

**Issue by Thoemodachi** [UQcsse3200/2023-studio-2#394]
# **Description**
Creation of three new bosses for implementation: Summoner Boss, Ranged Attack Boss, and final boss, GOD.
Summoner Boss:
- Will summon minions onto the field that attack the player. Minions are its main source of damage to player.

Ranged Attack Boss:
- Sprays projectiles towards the player's direction periodically. Player must dodge the attacks in order to get in vicinity with the boss.

Final Boss (GOD):
- Combination of projectile attacks and melee attacks, releases many projectiles in a spiral, very difficult to defeat.

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Ranged Boss (Oct. 4)
- [x] Summoner Boss(Oct. 4)
- [x] Final Boss (GOD) (Oct. 4)
- [x] JUnit Tests and Test Plan (Oct. 5)
- [x] Documentation (Oct. 5)
 
**Completion Deadline:** Oct. 5
 
# **Documentation**
- TBA
 
# **Member**
- Theodore Kim (@Thoemodachi) (thoemodachi)
- Trong Vuong (@samv26) (samv_v)
- Milo Hunter (@mhUnt3rS) (iavfjbdb#8394)
