### ISSUE TITLE
Instructor NPC for TutorialGameArea

### ISSUE THREAD

**Issue by rachitchaurasia** [UQcsse3200/2023-studio-2#401]
# **Description**
**Task:** [Implement Instructor NPC for Tutorial]().

The instructor NPC will appear when the player enters the tutorial area. It will provide tips, objectives, and guidance as the player learns the game mechanics. The instructor should move around the tutorial area, occasionally speak to the player, demonstrate mechanics, and generally assist the player in learning.
 
## **Example (optional usecases)**

- **Dialogue:** When player enters new area, instructor says "Welcome to the training grounds. I'll be your guide as you learn the basics."

- **Movement:** Instructor walks next to player, then moves to platform and says "Use 'W','A','S','D' to move around."

# **Dependencies**

- [x] Tutorial game area designed 
- [x]  NPC dialogue system
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design and define the characteristics of Instructor NPC
- [x] Add relevant TextureAtlas with their spritesheets
- [x] Add AnimationController Class for the NPC
- [x] Write Dialogues for Interaction
- [x] Integrate the dialogue system.
 
# **Documentation**
- [Tutorial Screen](https://github.com/UQcsse3200/2023-studio-2/wiki/Tutorial-Screen)

 
# **Member**

- Yash Mittal (@YashMitttal} (s4823869)
- Rachit Chaurasia (@rachitchaurasia) (s4823870)
- Raghav (@NotRaghavAggarwal ) (Raghav Aggarwal)
- Khushi (@khushijain0302)  (Khushi Jain)

**Comment by rachitchaurasia** [comment]
Completed and merged feature/tut2 into main.
