### ISSUE TITLE
Integrate companion and NPC with player

### ISSUE THREAD

**Issue by JivalX** [UQcsse3200/2023-studio-2#402]
# **Description**
**Task:** [Integrate companion and NPC with player]().
**Feature:** [Improved Interaction with Companion and NPCs](#278)

Enhance the gameplay between the player, companion, and non-player characters (NPCs) by modifying their follow components and adjusting the interaction distance. The goal is to create a smoother and more realistic interaction experience, where companions and NPCs can follow the player more effectively and engage in meaningful interactions within a specified range and bugs related to companion are fixed.

## **Dependencies**

- none

# **Milestones**
List of steps that need to be completed for this task.
- [x] Analyze current player-companion-NPC interaction
- [x] Implement improved follow components
- [x] Adjust interaction distance parameters

**Completion Deadline:** oct 4.

# **Documentation**
- [Test Plan](https://github.com/UQcsse3200/2023-studio-2/wiki/FollowComponent-Test-Plan)

 
# **Member**
- Yash Mittal (@YashMitttal) (s4823869)
- Dev Gupta (@DRG31) (xdrgx)
- Raghavendra (@RagGul ) (s48245755)

**Comment by rachitchaurasia** [comment]
All done
