### ISSUE TITLE
Implementation of new assets

### ISSUE THREAD

**Issue by Anshuman0157** [UQcsse3200/2023-studio-2#41]
# **Description**

The objective of the this task is to integrate newly acquired assets into the game environment to enhance the immersive experience for players. These assets should align with the theme of 'Escape earth' and contribute to the overall cohesiveness of the game world.
 
# **Dependencies**

1. Gathered assets from the #33 
2. Design and theme guidelines provided by the design committee
 
#**Milestones**

- [x] Goal 1: (Aug 25) Individual Asset Assessment and Preparation
- [x] Goal 2: (Aug 28) Integration of Assets Similar to Design 
- [x] Goal 3: (Aug 30) Asset Finalization and Testing

**Completion Deadline:** August 31
 

# **Documentation**

TBD

# **Member**

- Jordan Singh (@rike568) (Jordan Singh)
- Mitchell Hall (@s4697858 ) (Mitchell Hall)
- Anshuman Misra (@Anshuman0157 ) (Anshuman Misra)
- Samarth Dev Vaish (@SamarthDevVaish) (Samarth Dev Vaish)
- Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)
- Manvi Narang(@ManviNarang01) (Manvi Narang)
