### ISSUE TITLE
Resource Fissures

### ISSUE THREAD

**Issue by mira-alford** [UQcsse3200/2023-studio-2#412]
# **Description**
The goal of this ticket is to add "resource fissures". These will be entities which can spawn in the world (as per the level config) and:
- Block placement of structures
- Allow the construction of extractors **exclusively** in their location
Resource fissures will visually demonstrate what resource they produce using  the particle effect component in collaboration with team 7. Extractors placed on them will then produce this resource.

# **Dependencies**
#350 Particle effect system

# **Milestones**
- [x] Fissures can be configured and spawn on the map as placeable entities (blocking construction)
- [x] Fissures are irremovable (a new type of placeable entity)
- [x] Fissures can be replaced with extractors
- [x] Fissures produce a particle effect visualizing their resource
- [x] Extractors take up mutiple build tiles representing their size more appropriately

# **Documentation**
- [Main description of feature](../wiki/Resource Fissures)
- [Particle Component](https://github.com/UQcsse3200/2023-studio-2/wiki/Particle-Effects)

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g. McArthur (@McArthur-Alford)

**Comment by rowan-gray** [comment]
Completed
