### ISSUE TITLE
Space + Planet Updating

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#417]
# **Description**
This feature is to finalise the significant features developed by the space team including the space map, travelling between planets, and planet screen. This includes updating the map to reflect the 4 planets and highlighting which planet is next in the chain to travel to. Refining and enhancing planetary travel to make it more intuitive and simpler to implement in other features. The planet screen needs to be extended to add saving and load support and the ability to connect multiple game areas into a single planet for an enhanced gameplay experience.

# **Task Milestones**
- [x] Update the space map. (Sep. 25) (#419)
- [x] Improve planet travelling interfacing to streamline usage. (Sep. 27) (#418)
- [x] Add multi-game area support. (Sep. 17) (#329)
- [x] Implement saving and load. (Oct. 3) (#346)

**Completion Deadline:** Oct. 04

# **Documentation**
Most documentation is rewrites and extensions of pre-existing documentation to reflect the new improvements and changes.
- [Planet Screen](https://github.com/UQcsse3200/2023-studio-2/wiki/Planet-Screens)
- [Planet Travelling](https://github.com/UQcsse3200/2023-studio-2/wiki/Planet-Transition)
- [Saving and Loading](https://github.com/UQcsse3200/2023-studio-2/wiki/Saving-and-Loading)
- [Space Map](https://github.com/UQcsse3200/2023-studio-2/wiki/Space-Map)

# **Members**
Henry Batt @henrybatt
