### ISSUE TITLE
Planet Travel Simplification + Extension

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#418]
# **Description**
**Task:** [Planet Travel Simplification + Extension].
**Feature:** [Space + Planet Updating] (#417)

The current planetary travel only has 3 simple methods to travel around planets being, calling up the full planet map + minigame experience, spawning the minigame, or using the return button components. Returning from the various status screens that are combined into the gameplay experience (such as player death screen or story intro) is a less streamlined experience where the game state needs to be interacted with, this makes it needlessly complex and as such additional methods to be utilised through the `PlanetTravel` system will be introduced.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add return to current planet method (Sep. 24)
- [x] Add go to next planet method (Sep. 25)
- [x] Add go to specific planet method based on given name (Sep. 25)
- [x] Refactor existing usage of old transition methods to use this new system. (Sep. 26)
 
**Completion Deadline:** Sep. 27

# **Documentation**
This documentation is extended upon from last sprint to reflect new changes and additions.
- [Planet Travelling](https://github.com/UQcsse3200/2023-studio-2/wiki/Planet-Transition)
 
# **Member**
- Henry Batt @henrybatt
