### ISSUE TITLE
Space Map Update

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#419]
# **Description**
**Task:** [Space Map Update].
**Feature:** [Space + Planet Updating] (#417)

The Planet Space Map needs to be updated to ensure it aligns with the planets and their sequence for the final gameplay reducing the current number from 9 to 4. The map also needs to enforce the gameplay sequence to not allow players to travel to any planet from the map and instead only travel to the next in the sequence. The current planet and the next one they can travel to also needs to be emphasised so the player can clearly see where they are and where they are going.
 
The pre-existing SpaceNagivationBackground that draws twinkling stars on a deep blue background will also be refactored to separate the stars into an additional component so they can be utilised in other places and make it easy to modify the regions where stars should not be drawn.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Cleanup the assets into separate directories to make them easier to navigate. (Sep. 19)
- [x] Update config files and paths to ensure new directory locations are loaded into the resource service. (Sep. 20)
- [x] Select 4 sprites for the intended planets. (Sep. 21)
- [x] Reduce the number of planets on the map and reformat their layout to be more appealing. (Sep. 21)
- [x] Separate stars from the background so they can be used elsewhere easily. (Sep. 22)
- [x] Recalculate the bounding regions where there are no stars so there aren't large dead spaces. (Sep. 23)
 
**Completion Deadline:** Sep. 25

# **Documentation**
- [Space Map](https://github.com/UQcsse3200/2023-studio-2/wiki/Space-Map)
 
# **Member**
- Henry Batt @henrybatt
