### ISSUE TITLE
Entity Service Game Crash

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#420]
# **Description**
**Task:** [Entity Service Game Crash].
**Feature:** [Bug Fixing]

As the game runs and additional entities are spawned the game will eventually crash due to a thrown error in the `EntityService`. This is due to the implementation of the Base Game Engine and its usage of nested iterators, one to go over all the entities, and then all the components in these entities. This violated the usage of the `Libgdx` framework which is not intended to support this due to their custom array framework and its memory allocation with iterators and as such this needs to be removed.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify the crash point and its reason. (Aforementioned nested iterators) (Oct. 1)
- [x] Research what causes this issue and why it was introduced. (Oct. 1)
- [x] Implement a fix to ensure this does not occur. (Oct. 1) 

**Completion Deadline:** Oct. 1

 
# **Documentation**
*No documentation for this bug fix*

# **Member**
- Henry Batt @henrybatt
