### ISSUE TITLE
Death potion effects

### ISSUE THREAD

**Issue by atharvagupta2003** [UQcsse3200/2023-studio-2#434]
# **Description**
**Task:** [Death potion effects](#3).
**Feature:** [Companion Elevated In-Game Interaction](#384)

A one paragraph description of the task on which you will work. It should briefly explain what will be done (e.g. "Implement an armour component"). This includes textual explanations of the work. (e.g. "`Armour` inherits from `Component` and will add an event handler to the player entity so that the armour takes damage rather than the player. Different types of armour will have different durability. Once the armour is broken (durability reaches zero), it will no longer take damage and more attacks on the player will cause it to lose health.")
 
## **Example (optional)**
- **Potion effects**: Companion can shoot death potions towards the enemies which works on a targeting functionality and disposes off all the enemies it targets.

# **Dependencies**
Unification of potion and powerups
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Integration of death potion in companion weapon classes (Sept 29)
- [x] ability to shoot the potion when attack mode is toggled (Sept 30)
- [x] Implementation of enemy targeting functionality (Oct 1)
 
**Completion Deadline:** Oct 1
 
# **Documentation**
https://github.com/UQcsse3200/2023-studio-2/wiki/Death-Potion 

# **Member**
- Atharva Gupta (atharvagupta2003) (@atharva0179))
