### ISSUE TITLE
Story Outline 

### ISSUE THREAD

**Issue by DRG31** [UQcsse3200/2023-studio-2#44]
# **Description**
This feature encompasses the initial stages of the game, from setting the tone with a captivating introduction to the challenges faced during Level 1 on the planet Verdant Haven. Players will be introduced to the post-apocalyptic world, interaction with different characters, gather resources, and build a foundation for their interstellar journey.

## **Examples**
As the player embarks, they'll experience a blend of storytelling, interactive dialogues, and resource management. The introduction sets the stage for the challenges ahead, while the following stages immerse players in a struggle for survival on an alien planet.
# **Dependencies**

- None

# **Milestones**

- [x] Design and implement a captivating introduction sequence
- [x] Communication between different characters 
- [x] Establish dialogues with NPCs

**Completion Deadline:** Aug. 31

# **Extras (optional)**
- [x] Beautifying the Main Menu screen
- [x] Beautifying the Settings Screen
- [x] Changing the overall game UI

# **Documentation**
- [Story Outline](https://github.com/UQcsse3200/2023-studio-2/wiki/Story-Outline)
- [Botanist NPC Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/Botanist-NPC)
- [Story Screen Implementation documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/STORY-SCREEN-DOCUMENTATION)
- [Main Menu and Setting Menu Display](https://github.com/UQcsse3200/2023-studio-2/wiki/MAIN-MENU-AND-SETTING-MENU-DISPLAY-CHANGES)
- [User Interface Change wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/User-Interface-Skin-Configuration)
- [TitleBox Implementation Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/TitleBox-Class-Documentation)

# **Members**
- Name (GitHub Username) (Slack Handle) 
- Yash Mittal (@YashMitttal} (s4823869)
- Rachit Chaurasia (@rachitchaurasia) (s4823870)
- Dev Gupta (@DRG31) (xdrgx)
- Aniket Gupta (@aniketgupta17) (s4824063)
- Jival Kapoor (@JivalX) (s4824576)

**Comment by YashMitttal** [comment]
Sprint 1 Milestones Achieved!
