### ISSUE TITLE
Homogenization of the Game

### ISSUE THREAD

**Issue by neil-nb** [UQcsse3200/2023-studio-2#443]
# **Description**
**Task:** Homogenization of the Game

This ticket focuses on improving the game's look and narrative. The settings menu background will get a new design for a better visual appeal. The main menu starting screen logo will be polished to look better. The NPC's introduction dialogue will be reworded for a more engaging story. All planet sprites will be remade to make them visually consistent and appealing. Various entity sprites, like player, companion, and NPC, will be remade both with and without helmets to keep visuals contextually sensible. In addition, animated flowers and fire will be integrated into maps. Additionally, some visual glitches will be fixed, like stars clipping the game's logo. This ticket aims to make the game look better and tell a more engaging story.

# **Dependencies**
This ticket's main dependency, as with the last issue, is a fluid collaboration between studio members, as without it, nothing can be successfully completed.

# Design items:

- [x] Update wikis with all the new relevant info, lore, and sprite designs (Oct. 19)

## Priorities:
- [x] #561 (Oct. 18)
- [x] Refine main menu starting screen logo (Oct. 15)
- [x] Change wording of introductory NPC dialogue (Oct. 17)
- [x] Remake all planet sprites (Oct. 12)
- [x] Ensure that NPC is static when staying still (Oct. 17)
- [x] Make NPC sprite for tutorial (if there will be an NPC for the tutorial) (Oct. 16)
- [x] Add helmet to companion sprite (Oct. 17)
- [x] Remake astronaut sprite and integrate into game (Flora Haven) (Oct. 17)
- [x] Remake player sprite with no helmet (Earth) (Oct. 17)
- [x] Remake companion sprite with no helmet (Earth) (Oct. 17)
- [x] Remake NPC sprite with no helmet (Earth) (Oct. 17)
- [x] Remake player sprite with helmet (Other) (Oct. 17)
- [x] Remake companion sprite with helmet (Other) (Oct. 17)
- [x] Remake NPC sprite with helmet (Other) (Oct. 17)
- [x] Fully implement sprites all sprites and relevant animations (Oct. 19)
- [x] Ensure Companion is static when staying still (Oct. 19)
- [x] Did the entirety of the contents of #560 alone 
- [x] #488

## Secondary Priorities:
- [x] Ensure stars cannot clip through letters of main menu (Oct. 17)
- [x] Make zombie enemy (Oct. 17)

## Tertiary Priorities:
- [x] Add planets, galaxies, and/or a sun to main menu (Oct. 16)
- [x] Change font/bolden health number and stamina value (Oct. 17)

# Extras:
- [x] Make settings sliders button into RightShip Sprite (Oct. 19) (See collab ticket)
- [x] Change text boxes design (Oct. 19) (See collab ticket)

**Completion Deadline:** Oct. 19
 
# **Documentation**
- [Map Overview - Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Map-Overview)
- [Main Menu and Settings Screen](https://github.com/UQcsse3200/2023-studio-2/wiki/MAIN-MENU-AND-SETTING-MENU-DISPLAY-CHANGES)
- [Dialogue Box](https://github.com/UQcsse3200/2023-studio-2/wiki/Dialogue-Box-For-NPC)
- [Initial Screen](https://github.com/UQcsse3200/2023-studio-2/wiki/Story-Display-using-Initial-Screen)
 
# **Member**
- Neil Barigye Git: @neil-nb

**Comment by neil-nb** [comment]
I will add dates for the tasks either tonight or tomorrow.
