### ISSUE TITLE
improve the planet travel mechanism

### ISSUE THREAD

**Issue by VuKhanhVyHo** [UQcsse3200/2023-studio-2#444]
# **Description**
Improve the Inter-planetary travel mechanism as it is essential to move to next planet as expect and spawn the correct minigame. 

# **Dependencies**
The completed minigames and maps. Currently unknown

# **Milestones**
List of steps that need to be completed for this task.
- [x] Spawn correct minigames (Oct 10)
- [x] Moving to next planet after complete the main game (Oct 12)
- [x] Finalize details (Oct 15)
 
**Completion Deadline:** Oct 18
 
# **Documentation**
 
# **Member**
- Vu khanh Vy Ho(@VuKhanhVyHo )
