### ISSUE TITLE
Companion Lab Upgradation

### ISSUE THREAD

**Issue by gaurikadiwan** [UQcsse3200/2023-studio-2#445]
# **Description**
**Task:** Companion Lab Final Upgrades
**Feature:** Companion (#446 )

This feature will adjust how the laboratory will work to get locked potions in the Lab. Players need to to kill the enemies to unlock specific powerups which will have a high effect in the game.

### Example

When an enemy is defeated, Health and Speed powerups will be dropped onto the map and can be collected by the companion. This will be added in the inventory.

Once picked up, the companions inventory will be updated to include that potion (if its unlocked). This update will reflect on the companions inventory UI on the screen.

The LabWindow includes a mechanism  to unlock locked potions as players accumulate powerups.

# **Milestones**

List of steps that need to be completed for this task.
- [x] Added powerups visible in the Window in resemblance with the game UI, collected by the Companion(9th Oct)
- [x] Create Inventory Component For laboratory(12th Oct)
- [x] The Locks to be present on PowerUps(13th Oct)
- [x] Bug Fixation for Spawn Power-up feature(15th Oct)

# **Dependencies**

-None

**Completion Deadline:** Oct 13
 
# **Documentation**

- TBD
 
# **Member**
--Atharva Gupta (atharvagupta2003) (@atharva0179)
