### ISSUE TITLE
Companion Down mode

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#447]
# **Description**
**Task:** Companion Death/Down Mode
**Feature:** #446

This task will polish how the companion "dies".
Instead of a full Death screen, which is similar to what happens to the player, companion will enter a "down" mode when health reaches 0.

When health reaches 0, the companion will go down.
Down = 
1. No movement. Stuck on map
2. Limited abilities. Cannot change into attack or defence mode, since it is in down mode
3. Cannot activate most powerups, besides Health, Speed, and Extra Life powerup.

How the companion is "revived" from the downed mode

The player will need to use an "Extra Life" powerup, and that will restore the companion back to normal mode, and give it full health.

**example**
Companion health goes to zero

Companion goes into down mode

A UI element for the Companion's mode (bottom left) refreshes saying "Down"

If the player has an extra life powerup (which it can brew at the laboratory), the player can activate it, and bring the companion back to life

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct 7 - 9 ) None
- [x] Step 2 (Oct 10 - 12 ) None
- [x] Step 3 (Oct 13 -16) Stop the companion from moving when it dies
- [x] Step 4 (Oct 17) Create new mode "Down" mode, and put it in companion actions
- [x] Step 5 (Oct 17) Update UI to show down mode
- [x] Step 6 Stop movement from keys on companion in down mode
- [x] Step 7 () Stop follow component in down mode
- [x] Step 8 () Stop the use of certain powerups in down mode
- [x] Step 9 () Configure Extra Life powerup to bring the companion back to full health and in normal mode
 
**Completion Deadline:** 3pm Oct. 18
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
- Maxwell (MaxwellSchroder) (@Magwell)
- Atharva Gupta (atharvagupta2003) (@atharva0179)
