### ISSUE TITLE
Companion AI Tasks within Modes

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#448]
# **Description**
**Task:** Companion AI Tasks within Mode
**Feature:** #446 
This task is creating AI tasks for the companion to do while in its Attack mode

**example**
Attack
- Autonomously move towards the nearest enemy
- attack the enemies with a ranged weapon

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Oct 15 ) Create AI task for attack mode 
- [ ] Step 2 (Oct 16 ) implementation of ranged weapons
- [ ] step 2 (Oct 17 ) create testing

 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
Atharva Gupta (atharvagupta2003) (@atharva0179)

**Comment by MaxwellSchroder** [comment]
Attack Ai task is completed
