### ISSUE TITLE
Companion Particle Effects

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#449]
# **Description**
**Task:** Companion Particle Effects
**Feature:** #446 
Add particle effects to the different sections which involve the companion. 

**example**
1. Death potion
Add a particle effect of "smoke" following the path of the death_potion as it bounces between enemies. This signifies the enemies which will be damaged when the death_potion explodes (timer ends)

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.

Subtask 1 - Death potion trail
- [x] Step 1 creating particle effects on lib gdx (Oct 9 ) 
- [x] Step 2 creating a new powerup controller to start and stop effects(Oct 10 ) 
- [x] Step 3 Implementing effects on killing the enemy(Oct 13 -16) 

**Completion Deadline:** Oct. 16
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
Atharva Gupta (atharvagupta2003) (@atharva0179)
