### ISSUE TITLE
Player Stats

### ISSUE THREAD

**Issue by Dammo3** [UQcsse3200/2023-studio-2#45]
# **Description**
**Task:** [Player Stats](#3).
**Feature:** [Player Feature](#2)

Implement the base player statistics, which can be modified by upgrades and power-ups. Upgrades will provide permanent changes to the player statistics, whereas power-ups will have a temporary effect on player statistics. Upgrades will be able to be made to baseline statistics, which are stored in the `player.json` file. Player statistics which will be modified include player health, base attack, speed, attack modifiers and immunity. 
 
# **Dependencies**
- [x] Implementation of changes to `CombatStatsComponent`
- [x] Integration with #20 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] (Aug. 21) - Unit tests created
- [x] (Aug. 28) - Player statistics implemented and tested
- [x] (Aug. 29) - Integrate changes with player powers
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
TBC
 
# **Member**
- Damian Bellew (@Dammo3) (Damian Bellew)
