### ISSUE TITLE
Companion Inventory UI Update

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#451]
# **Description**
**Task:** Companion Inventory UI Update
**Feature:** #446 

The button to open and close the inventory will remain.

We need the inventory UI component to actually update when the inventory count changes.

**example**
Normal game

Click inventory button, inventory UI open

Companion or player walks across powerup -> it adds the powerup to the inventory

Inventory UI is updated to include the recent powerup addition in the counts

If the inventory becomes empty (with powerup use), it shows a 0 count of powerups in the inventory

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct 7 - 9 ) NA
- [x] Step 2 Analyse codebase for how the inventory works, see what data structure stores the powerups
- [x] Step 3 Make sure the inventory is being updated when a new powerup is picked up, use logger to check
- [x] Step 4 After use of a powerup, when you close the inventory window and open it again, new counts are shown

OPTIONAL
- [ ] Step 5 Add triggers to the labels of the counts in the inventory window. Whenever the powerup inventory is updated, trigger a live refresh of the count values while the window is open.

**Completion Deadline:** Oct. 16
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
- Maxwell Schroder (@MaxwellSchroder)
- Saakshi Gupta (saakshigupta2002) (@saakshigupta)

**Comment by MaxwellSchroder** [comment]
Completed. Not doing the triggers for the live update, since closing and opening the window is good enough for now.
