### ISSUE TITLE
Companion Death Potion Update

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#452]
# **Description**
**Task:** Companion Death Potion Update
**Feature:** #446 
This task is an update of how the death potion disposes of enemies. Instead of directly disposing the enemies, it will be refactored just to deliver damage to the health of the enemies. This way, death animations can be activated. 

**example**
The companion activates the death potion. 

The death potion bounces between enemies and eventually blows up

All the entities which were targeted by the death potion will have their health reduced, and if their health goes to 0, then it will be handled on the entities end, and not directly disposed of.

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Refactoring the CompanionWeaponTargetComponent(Oct 10 ) 
- [x] Step 2 Implementing potion damage to avoid enemy disposal(Oct 12 ) 
- [x] Step 3 Testing and resolving the bugs
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
-Atharva Gupta (atharvagupta2003) (@atharva0179)
