### ISSUE TITLE
Companion New Sprites

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#453]
# **Description**
**Task:** Companion New Sprites
**Feature:** #446 
This task is twofold;
1. Update the laboratory sprite to be more in line with the game theme
2. Create unique companion sprites for fire and ice levels

**example**
Earth
- normal Emily carter 

Fire
- fire alternative Emily carter (Red)

Ice
- ice alternative Emily carter (Blue)

Lush
- normal Emily carter 

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
Subtask 1 - Update Laboratory Sprite
- [x] Step 1 (Oct 7 - 8 ) Find inspiration for a new laboratory look and create it in pixel art
- [x] #462

Subtask 2 - Create alternative Emily carter skins for fire and ice
- [ ] Step 1 (Oct 7-9 ) Create fire Emily carter skin, Create ice Emily carter skin
- [ ] Step 2 (Oct 10-13 ) Adjust so that correct skin to be loaded for each level.
- [ ] Step 3 (Oct 14-16  ) Merge into main

 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**

- Raghavendra ( RagGul)
