### ISSUE TITLE
Companion Powerups Effects

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#454]
# **Description**
**Task:** Companion New Sprites
**Feature:** #446 
This task is to make sure any powerup in the game is fully functioning, picked up on interaction and their effects to work on pressing key N. 

**example**
MANDATORY
Speed
- Increases the player and the companion speed for a set duration of time

Health
- Increases the player and the companion health 

Death
- Throws a death potion which tracks the nearest enemy. Bounces between the enemies, and then blows up after a set amount of time, dealing damage to those enemies.

OPTIONAL
Fire
- Fire level specific potion which applies fire effect and creates an explosion.

Ice
- Ice level specific potion which freezes the enemies

# **Dependencies**
NONE 

# **Milestones**
- [x] Step 1 - fixing bug of powerup spawn(Oct 7-9 ) 
- [x] Step 2 - picking up powerup updates inventory(Oct 10-13 ) 
- [x] Step 3 - apply effects without game to crash(Oct 14-16  ) 

 
**Completion Deadline:** Oct. 11
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
-Atharva Gupta (atharvagupta2003) (@atharva0179)
