### ISSUE TITLE
Refactor main menu and space navigation to use the same background.

### ISSUE THREAD

**Issue by TDay1** [UQcsse3200/2023-studio-2#456]
# **Description**
**Task:** Refactor main menu and space navigation to use the same background.
**Feature:** [Space Feature Finalisation](#552)

Currently there are two separate implementations of the animated starry background used on the main menu and the space navigation screen. To improve code quality and testability, these should be combined into one generalised class.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x]  New Space map (#152)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] New, shared class made (Oct. 11)
- [x] All screens that use the star background use the shared class (Oct. 11)
- [x] Implement tests for the new class (Oct. 12)
- [x] Document star background for further use (Oct.13)
 
**Completion Deadline:** Oct. 13
 
# **Documentation**
- [StarBackground class](https://github.com/UQcsse3200/2023-studio-2/wiki/Star-Background-Class)
 
# **Member**
- Thomas Day (TDay1) (Tom Day)
