### ISSUE TITLE
Polished Player

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#458]
# **Description**
The aim of this feature ticket is to polish the game in a variety of ways:
- [Polishing the HUD](https://github.com/UQcsse3200/2023-studio-2/issues/461)
- [Polishing Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/467)
- [Integrate saving/loading with Upgrade Tree](https://github.com/UQcsse3200/2023-studio-2/issues/513)
- [Integrate saving/loading with Player Inventory](https://github.com/UQcsse3200/2023-studio-2/issues/528)
- [Weapon/Tool hotbar improvements](https://github.com/UQcsse3200/2023-studio-2/issues/489)
- [Pause Game](https://github.com/UQcsse3200/2023-studio-2/issues/477)
- [Code smells and bugs](https://github.com/UQcsse3200/2023-studio-2/wiki/Code-smells-and-bugs)
- [Improve sound experience](https://github.com/UQcsse3200/2023-studio-2/issues/471)

## SubFeatures

**Polishing the player HUD:**
- Fixing stretched HUD assets used in the companion HUD elements
- Dynamic bar fill colours for health and dodge
- Fix for planet HUD element with new planet assets
- General removal of code smells

**Polishing Weapons:**
- Improve attack animation and holding sprite appearance
- Implement a Nuke and a melee weapon
- Implement Reload functionality
- Testing

**Pause Game**
- Create pause functionality that stops the game play while a menu is open
- Implement a pause button to replace the Exit button
- Pause button allows user to either return to game or exit to main menu
- Associated testing and wiki updates
- [Collaboration Ticket](https://github.com/UQcsse3200/2023-studio-2/issues/511) with Team 8 regarding merging functionalities

**Hotbar UI Improvements:** #489 
- Enhance the UI to offer a more accessible view of the user's unlocked items
- Rework weapon/tool keybindings
- Conduct testing and update appropriate wiki pages

**Code smells, coverage, and bugs**
- Address Sonarcloud bugs
- Address Entity disposal bugs
- Fix code smells associated with Player team classes
- Increase code coverage where possible.

**Integrate saving/loading with Upgrades and Player Inventory:** #513 #528 
- Implement saving and loading with the [SavableComponent](https://github.com/UQcsse3200/2023-studio-2/wiki/Saveable-Component)
- Update testing
- Update wiki documentation

## Dependencies

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] [Integrate save/load with Upgrades](https://github.com/UQcsse3200/2023-studio-2/issues/513)
- [x] [Hotbar UI Improvements](https://github.com/UQcsse3200/2023-studio-2/issues/489) (Oct. 16)
- [x] [Polished HUD elements implemented](https://github.com/UQcsse3200/2023-studio-2/issues/461) (Oct. 17)
- [x] [Polished Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/467) (Oct. 18)
- [x] [Pause Game](https://github.com/UQcsse3200/2023-studio-2/issues/477) (Oct. 18)
- [x] [Integrate save/load with Player Inventory](https://github.com/UQcsse3200/2023-studio-2/issues/528) (Oct. 18)
- [x] [Code smells and bugs](https://github.com/UQcsse3200/2023-studio-2/wiki/Code-smells-and-bugs) (Oct. 19)

**Completion Deadline:** Oct. 19

# **Documentation**
- [Weapons](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)
- [Upgrade Tree](https://github.com/UQcsse3200/2023-studio-2/wiki/Upgrade-Tree)
- [Player Inventory](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Inventory)
- [Pause Game](https://github.com/UQcsse3200/2023-studio-2/wiki/Pause-Game)
- [Code smells, coverage, and bugs](https://github.com/UQcsse3200/2023-studio-2/wiki/Code-smells-and-bugs)
- [Sound Effects](https://github.com/UQcsse3200/2023-studio-2/wiki/Sound-Effects)
- [Player HUD](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Heads-Up-Display-(HUD))

# **Members**
- Connor Golin (@connor-golin)
- Damian Bellew (@Dammo3) (Damian Bellew)
- Daniel van Niekerk (@Daniel-vanNiekerk0)
- Rachel Leathers (@racheljadel) (Rachel Leathers)
- Kushagra Agrawal (@kushagra1912 )(Kushagra Agrawal)
