### ISSUE TITLE
Polished HUD

### ISSUE THREAD

**Issue by Dammo3** [UQcsse3200/2023-studio-2#461]
# **Description**
**Task:** [Polished HUD](https://github.com/UQcsse3200/2023-studio-2/issues/461)
**Feature:** [Polished Player](https://github.com/UQcsse3200/2023-studio-2/issues/458)

Finalising polish on the Heads Up Display. This is to ensure the most seamless, cohesive HUD, between all elements, not just the top left of the heads up display. Improvements to the HUD include (but won't be limited to):

- Fixing stretched HUD assets used in the companion HUD elements
- Dynamic bar fill colours for health and dodge
- General removal of code smells 
- Fix issues with planet display since change of planet sprites 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Improve HUD Assets (Oct. 13)
- [x] Add dynamic colours to bars (Oct. 15)
- [x] Fix planet display (Oct. 16)
- [x] Work on removing code smells (Oct. 18)
 
**Completion Deadline:** Oct. 18

# **Documentation**
- [Player HUD Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Heads-Up-Display-(HUD))
 
# **Member**
Damian Bellew (@Dammo3) (Damian Bellew)
