### ISSUE TITLE
Cooling / Heat emitting entities in map

### ISSUE THREAD

**Issue by ArmandoLiebenberg** [UQcsse3200/2023-studio-2#465]
# **Description**
Task: Heat emitting entities in map
Feature: #296
A heat emitting entity that interacts with the player cold level feature

# **Dependencies**
Cooperation with the Player And possibly the buildables team

# **Milestones**
List of steps that need to be completed for this task.
- [x] Discuss with the relevant teams (Oct. 14)
- [x] Create a collaboration ticket (Oct. 15)
- [x] Implement cold meter system (Oct. 16)
- [x] Implement steam geyser map entity (Oct. 17)
- [x] Testing and bugfixing (Oct. 18)
 
**Completion Deadline:** Oct. 17th

# **Member**
Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)
