### ISSUE TITLE
Companion powerup crafting

### ISSUE THREAD

**Issue by kk4w4i** [UQcsse3200/2023-studio-2#466]
# **Description**
Creating new crafting feature for the companion through the laboratory. This will adjust the powerup dropping done by the enemies, and new functionality for the companion to walk away when crafting a specific powerup is selected. As well as new ui implementations for the laboratory and the companion inventory.

## **Examples **
- Health and Speed powerups are now the only dropped powerups and we can use them to craft more powerful powerups
- The crafting can be done by the player or if companion is alive it can make the companion go craft the powerup
- Powerups will take 10 seconds to make which requires the player to stay around the laboratory if they choose to make the powerups themselves, or they make the companion do the whole process automatically, giving the user a advantage for keeping the companion alive.

# **Dependencies**
- Enemy team will help with droping the correct powerups

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Make adjustments to current code to setup the feature(Oct. 11)
- [x] Create powerup ui for the player (Oct. 13)
- [x] Create the UI for companion inventory and laboratory(Oct. 13)
- [x] Implement powerup selection for play logic (Oct. 17) 
- [x] Implement crafting logic (Oct 17.)

**Completion Deadline:** Oct. 17

# **Documentation**
- [Powerups](https://github.com/UQcsse3200/2023-studio-2/wiki/Powerups)

# **Members**
- Name (GitHub Username) (Discord Handle)
- Atharva Gupta (atharvagupta2003) (@atharva0179)
- Kintaro Kawai (kk4w4i) (@0xkin)
