### ISSUE TITLE
Polished Weapons

### ISSUE THREAD

**Issue by Daniel-vanNiekerk0** [UQcsse3200/2023-studio-2#467]
# **Description**
**Task:** Polished Weapons
**Polished Player** [Polished Player](https://github.com/UQcsse3200/2023-studio-2/issues/458)

Polished Weapons will be an extension of[ Refined Weapons](https://github.com/UQcsse3200/2023-studio-2/issues/283) and will finalise weapons in the game. 
This will be to: 
 - Modify Weapons attack animation and holding sprite to use image rotation
 - Implement Nuke Weapon + a new explosion particle effect
 - Implement an Additional Melee weapon
 - Implement Weapon reload functionality
 - Implement Weapon testing
 - Bug fixes any issues with weapons

# **Dependencies**
- As polished weapons aims to primarily to be an improvement to weapons the main dependency is the existing [weapons implementation](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)

# **Milestones**
List of steps that need to be completed for this task. 
 - [x] Weapon Image rotation (Oct. 10)
 - [x] Nuke  (Oct. 10)
 - [x] New Melee weapon (Oct. 10)
 - [x] Weapon reload functionality (Oct. 16)
 - [x] Weapon testing  (Oct. 18)
 - [x] Bug fixes any issues with weapons & Update Weapons Wiki  (Oct. 19)

**Completion Deadline:** Oct. 19

# **Documentation**
- [Weapon Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Weapons)
 
# **Member**
- Daniel van Niekerk(@Daniel-vanNiekerk0) (Daniel van Niekerk)
