### ISSUE TITLE
Creating enemy assets for (1 small enemy, 1 boss, 1 melee weapon, 1 ranged weapon) (Aug. 30)

### ISSUE THREAD

**Issue by kk4w4i** [UQcsse3200/2023-studio-2#47]
# **Description**
The issue is responsible for bringing the  elements to life and adding a little flair and excitement. The following assets will be designed and animated by sprint 1.
- 1 small enemy type
- 1 boss enemy type
- 1 melee weapon
- 1 ranged weapon 

# **Dependency** 
- Enemies Class
  - Enemies, weapons
- Globaly
  - Story, Map

# **Documentation**
[Enemy assets and animation](https://github.com/UQcsse3200/2023-studio-2/wiki/Enemies'-Features)

# **Milestone**
- [x] Complete enemy asset designs (Aug 25) 
- [x] Complete attacking asset designs (Aug 25)
- [x] Animations for enemies (Aug 27)
- [x] Animations for attacks (Aug 27)

# **Members**
- Kintaro Kawai (@kk4w4i) (0xkin)
- Aryaman Tiwari (@Aryamant21) (at007)
