### ISSUE TITLE
Improve/update Sound Effects  

### ISSUE THREAD

**Issue by aman-86** [UQcsse3200/2023-studio-2#471]
# **Description**
**Task:** [Improve sound experience](https://github.com/UQcsse3200/2023-studio-2/issues/471) 
**Feature:** [Polished player](https://github.com/UQcsse3200/2023-studio-2/issues/458)

This task is meant to add and update some more sound effects in the game to make it more interactive an juicy. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add Upgrade Tree Close Button Sound effects (Oct. 11)
- [x] Add Sound effects fro weapons (Oct. 18)
- [x] Unit Testing  (Oct. 18)
 
**Completion Deadline:**  - Oct.20

# **Documentation**
- [Sound Effects Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Sound-Effects)
 
# **Member**
- Aman (@aman-86 ) (Aman Gupta)
