### ISSUE TITLE
Upgrade boss task,  fix animation responsiveness and bugs fixing. 

### ISSUE THREAD

**Issue by samv26** [UQcsse3200/2023-studio-2#472]
# **Description**
**Task:** [Enemy final touch](#3).
**Feature:** [Enemy mechanic and enemy actions](#2)

This task will merge chase task into bosses task that was recreated in sprint 4. This will incorporate pathfinding into bosses enemy characters that is currently using invisibility, jump or god task. This task also aim to fix the animation rendering delay when enemy switches task to get it close to instantaneous as possible. 
 
## **Example (optional)**
- Enemy playing the attacking animation while chasing
- Enemy doesn't switches direction of attack and direction of movement
- Most bosses task doesn't have the newly implemented path finding 

# **Dependencies**
- Kin reconfiguration on enemy configs file. (this enable spawning selective enemy and selecting the right task for that enemy)

 
# **Milestones and deadline**
List of steps that need to be completed for this task.
- [x] Path finding for God task (13 Oct).
- [x] Path finding for Invisibility (14 Oct).
- [x] Path finding for Jump (14 Oct)
- [x] Animation playing bug fixing (18 Oct)

 
 
# **Member**
-Trong Vuong (samv26) (samv)
