### ISSUE TITLE
Game Perfection Sprint: Refined Gameplay & Enhanced UI/UX

### ISSUE THREAD

**Issue by aniketgupta17** [UQcsse3200/2023-studio-2#475]
# **Description**
This feature ticket outlines the objectives for our upcoming sprint, focusing on further enhancing our game. Key tasks include completing the controls screen, refining the initial screen, completing dialogues for the entire game, enhancing the title box, tutorial map  and adding menu buttons. We will also work on integrating the UI according to the Gamestyle . These efforts aim to provide a polished and engaging user interface and gameplay experience.

## SubFeature/component
- **Controls Screen Completion:** - Finalising the controls screen with all necessary details and interactions.
- **Initial Screen Refinement:** -Improving the initial screen to ensure a captivating first impression for players.
- **Dialogue Completion:** -Completing dialogues for the entire game to enhance storytelling and player engagement.
- **Title Box Enhancement:**-Enhancing the design and functionality of the title box for better visual appeal and usability.
- **Menu Button Improvement:**-Enhancing the menu buttons for a more intuitive and seamless navigation experience.
- **Tutorial Map Completion:**-Completing the Tutorial map by adding triggers ,NPC and the dialogue completion .

# **Milestones**
List of sub-features you intend to have done and in main by the end of the sprint.
- [x] Design and layout  the controls screen by adding a map to the Screen .
- [x] All necessary details and interactions integrated into the controls screen .
- [x] Integration of improved graphics and animations  in the Initial Screen .
- [x] Dialogues reviewed and refined to ensure engaging storytelling and player involvement and coordinating the game flow .
- [x] Integration of enhanced visual elements and improved usability within the title box.
- [x] Addition of menu button for a more intuitive and seamless navigation experience.
- [x] Addition of triggers and events in the Tutorial map for seamless gameplay progression.
- [x] Integration of NPCs and dialogue completion for an informative and engaging tutorial experience.

**Completion Deadline** October 19, 2023

# **Extras**
TBA

# **Documentation**

- [Complete Story](https://github.com/UQcsse3200/2023-studio-2/wiki/Complete-Story)
- [Modified TitleBox Class](https://github.com/UQcsse3200/2023-studio-2/wiki/Modified-TitleBox-Class)
- [TutorialScreen Class Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/TutorialScreen-Class-Documentation)
- [ControlScreen Class Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/ControlScreen-Class-Documentation)
- [Revamp InitialScreenDisplay Class](https://github.com/UQcsse3200/2023-studio-2/wiki/Revamp-InitialScreenDisplay-Class)
- [Menu Button](https://github.com/UQcsse3200/2023-studio-2/wiki/Menu-Button)

# **Members**

- Yash Mittal (@YashMitttal} (s4823869)
- Rachit Chaurasia (@rachitchaurasia) (s4823870)
- Dev Gupta (@DRG31) (xdrgx)
- Aniket Gupta (@aniketgupta17) (s4824063)
- Jival Kapoor (@JivalX) (s4824576)

**Comment by YashMitttal** [comment]
All done
