### ISSUE TITLE
Update the names and reorder the levels in the game.

### ISSUE THREAD

**Issue by TDay1** [UQcsse3200/2023-studio-2#476]
# **Description**
**Task:** Update the names and reorder the levels in the game.
**Feature:** [Space Feature Finalisation](#552)

The story team has changed the names of the levels and the order in which they're played. The have requested that:
1. The level/planet names be updated.
2. The levels be reordered in the game
3. The this reordering should be reflected in the space map

# **Dependencies**
- [x] Maps completed: #646 (The final map must be completed before we can reorder the final map to be the first map)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Levels renamed (Oct. 13)
- [x] Levels reordered (Oct. 15)
- [x] Space map reordered (Oct. 15)
 
**Completion Deadline:** Oct. 16
 
# **Member**
- Thomas Day (TDay1) (Tom Day)
- HenryBatt @henrybatt
