### ISSUE TITLE
Pause Game

### ISSUE THREAD

**Issue by racheljadel** [UQcsse3200/2023-studio-2#477]
# **Description**
**Task:** [Pause Game](https://github.com/UQcsse3200/2023-studio-2/issues/477)
**Feature:** [Polish Player](https://github.com/UQcsse3200/2023-studio-2/issues/458)

The pause game functionality will allow the user to temporarily pause the game, and will be implemented in a dedicated pause button. This pause button, when clicked, will give the player the option to either return to the game or exit to the main menu. It will replace the exit button in the top right corner. All game functions (entities' attacks etc.) will be 'paused' when the button is pressed, or the paused() functionality is called upon. A [collaboration ticket](https://github.com/UQcsse3200/2023-studio-2/issues/511) was made to merge menu button functionality made by Team 8. 
 
# **Dependencies**
- [Base Planet GameArea Type](https://github.com/UQcsse3200/2023-studio-2/issues/184)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Created pause window and pause button UI. (Oct. 13)
- [x] Created pause functionality and listener (Oct. 14)
- [x] Created unit testing for the pause button.  (Oct. 15)
- [x] Implemented and tested the pause button. (Oct. 16)
- [x] Implemented and tested pause functionalities for other windows. (Oct. 16)
- [x] Created wiki documentation for the pause button. (Oct. 17)
 
**Completion Deadline:** Oct. 18

# **Extras (optional)**
- [ ] Add settings button and implement accessibility through game.
 
# **Documentation**
- [Pause Game](https://github.com/UQcsse3200/2023-studio-2/wiki/Pause-Game)
 
# **Member**
Rachel Leathers (@racheljadel) (Rachel Leathers)
