### ISSUE TITLE
Creating enemy mechanics, behaviour and stats (1 small enemy, 1 boss) (Aug 30)

### ISSUE THREAD

**Issue by kk4w4i** [UQcsse3200/2023-studio-2#48]
# **Description**
Responsible for implementing the base enemy entity, behavior and attacks with different variances that others teams could utilize for different storylines. 
Responsible for implementing the boss enemy entity, with more health, faster movement, more damage, and larger entity size.

# **Dependencies** 
Enemy weapons keep tracks of different weapon usages which will leads to change in attack statistic
Extractor classes and player classes control the behaviour of the enemies classes like proximity targeting.

# **Milestones** 
- [x] Based enemy variance and movement (20 Aug)
- [x] Attacking behaviour (24 Aug)
- [x] Spawning and death actions (25 Aug)
- [x] Implement usages of different attacks (27 Aug)

# **Documentation**
[Enemy mechanics and behaviours](https://github.com/UQcsse3200/2023-studio-2/wiki/Enemies'-Features)

# **Members**
Trong Vuong (@samv26) (samv_v)
Ojaswin Kohli (@OjaswinKohli) (ojaswinkohli)
Aryaman Tiwari (@Aryamant21) (at007)
