### ISSUE TITLE
Place and destroy sound effects for structure

### ISSUE THREAD

**Issue by aman-86** [UQcsse3200/2023-studio-2#487]
# **Description**
**Task:** Place and destroy sound effects for structure
**Feature:** [polish Player](https://github.com/UQcsse3200/2023-studio-2/issues/458)

This task is meant to add sound effects on placing and destroying structures. This will be done via Collaboration Ticket with team 7 and team 4. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add sound effects for placing and destroying structures (Oct. 16 )
- [x] Add java docs(Oct. 16)
- [x] Unit testing through video(Oct. 17)

**Completion Deadline:** Oct. 18

 
# **Documentation**

- TBD

# **Member**
- Aman (@aman-86 ) (Aman Gupta)
- Yugansh (@Yugansh-Uq ) (Yugansh Pancholi)
