### ISSUE TITLE
Tweening Animated Flowers and Fire into Respective Maps

### ISSUE THREAD

**Issue by neil-nb** [UQcsse3200/2023-studio-2#488]
# **Description**
**Task:** [Tweening Animated Flowers and/or Icicles and/or Fire into Respective Maps](#488).
**Base Task:** [Homogenization of the Game](#443)

To add to the beautification of the maps, it was decided that animated visuals would be a pleasant addition. As a result, multiple different species of flower have been added to multiple maps, in addition to some dynamic fire for planet 3. These additions do not have a hitbox, and they are not interactable, they have simply been added to aesthetically improve the game.

# **Dependencies**
The only ticket this addition depends on is #443, as the animated entities need to exist first before they can be added to the game.
- [x] [Homogenization of the Game (#433)](#443)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Creating the flower sprite sheets (Oct. 14)
- [x] Creating fire sprite sheets (Oct. 14)
- [x] Animating the flowers (Oct. 14)
- [x] Animating the fires (Oct. 14)
- [x] Adding animated flowers to planet 1 (Oct. 14)
- [x] Adding animated flowers to planet 2 (Oct. 14)
- [x] Adding animated fires to planet 3 (Oct. 16)
- [x] Making fire harm player (Oct. 17)
 
**Completion Deadline:** Oct. 19
 
# **Documentation**
- [Map Overview - Wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/Map-Overview)
 
# **Member**
- Neil Barigye (@neil-nb) 
- Mitchell Hall (@s4697858)
