### ISSUE TITLE
Hotbar UI Improvements

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#489]
# **Description**
**Task:** [UI Improvement - Unlocked Items Visibility](#3).
**Feature:** [Enhanced User Interface](https://github.com/UQcsse3200/2023-studio-2/issues/458)

This task aims to enhance the UI to offer a more accessible view of the user's unlocked items to provide a more engaging and informative user interface. 

Currently, the Hotbar only displays one item from each slot (melee, ranged, and building hammer), and all unlocked items are only visible in the `UpgradeTree` menu. The improved UI will allow the user to see all unlocked items added to their weapon slot hotbar as soon as they unlock it. This will involve implementing a new UI element, wherein all the unlocked items are easily noticeable on the screen.

# **Dependencies**
- [x] (#144)
- [x] (#191)

# **Milestones**
- [x] Step 1: Develop UI Mockups for the new unlocked items hotbar (Oct. 13)
- [x] Step 2: Implement the UI for Buildables Hotbar & Integrate with Current UI (Oct. 14)
- [x] Step 3: Implement the UI for Melee and Ranged weapons & Integrate with Current UI (Oct. 15)
- [x] Step 4: Modify `KeyboardPlayerInputComponent` to implement more intuitive weapon switching. (Oct. 16)
- [x] Step 5: Conduct Testing and polishing (Oct. 16)

**Completion Deadline:** Oct. 16

# **Documentation**
- [Player Inventory](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Inventory)

# **Member**
- Name (GitHub Username) (Slack Handle)
- Connor (@connor-golin)
- Rowan (@rowan-gray)

**Comment by rowan-gray** [comment]
Finished on time... YAY 😄. Merged into main with this pull request. https://github.com/UQcsse3200/2023-studio-2/pull/496

**Comment by connor-golin** [comment]
> Finished on time... YAY 😄. Merged into main with this pull request. #496

Excellent work fellow studio member. I am pleased with our teamwork.
