### ISSUE TITLE
Creating attacking mechanics and stats (1 melee , 1 ranged ) (Aug. 30)

### ISSUE THREAD

**Issue by kk4w4i** [UQcsse3200/2023-studio-2#49]
# **Description**
The focus of this task is to implement different ways for the enemy to apply damage to its targets. The creation of several weapons, including melee and ranged weapons, will allow different types of enemies to apply damage in their own unique ways, and applies pressure onto the player in game.

# **Dependency** 
Strong connection with Story Team and Map Team

# **Documentation**
[Enemy attack mechanics](https://github.com/UQcsse3200/2023-studio-2/wiki/Enemies'-Features)

# **Milestone**
- [x] Create the first working melee attack with base stats for enemy (Aug 23rd)
- [x] Implement a simple working ranged attack(Aug 25th)
- [x] Junit Tests (Aug 30th)

# **Members**
Firstname Surname (@github) (Discord Handle)
- Theodore Kim (@thoemodachi) (thoemodachi)
- Kintaro Kawai (@kk4w4i) (0xkin)
- Milo Hunter (@mhUnt3rS) (iavfjbdb#8394)
