### ISSUE TITLE
General Balance in Game 

### ISSUE THREAD

**Issue by Yugansh-Uq** [UQcsse3200/2023-studio-2#491]
# **Description**

In this task, we aim towards providing a finishing and polishing to the some aspects of our game. In this task of Sprint 4, we will be working on the following:
 - Redefining unlock costs for weapons / structures.
 - Implement costs for placing structures.
 - Requirements for leaving a planet.
 - Reset damage caused to weapons by enemies.
 - Enemy Health
 
# **Milestones**
- [x] Set unlock costs for weapons and other structures
- [ ] Set costs for placing structures and decide and set requirements for leaving planet
- [x] Set damage caused to weapons and enemy health.
 
**Completion Deadline:** Oct 17

 
# **Documentation**
- TBD

 
# **Member**
- Yugansh (@Yugansh-Uq) (Yugansh Pancholi)
