### ISSUE TITLE
Improved Heal Tool

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#492]
# **Description**
The goal of this task is to improve the heal tool such that healing a structure is proportional to the cost of the structure itself instead of simply being a fixed rate. This is being done to improve the balance of the game since a dirt wall should be cheaper to heal than a turret.

# **Dependencies**
All dependencies have already been implemented in previous tasks.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Refactor code to be dependent on structure cost.
- [x] Refactor existing tests to match new functionality and implement additional tests to ensure the heal cost is dependent on structure cost.
- [x] Update Heal Tool wiki to match new functionality.
 
**Completion Deadline:** Aug. 15
 
# **Documentation**
- [Heal Tool](../wiki/Healing-Tool)
 
# **Member**
- Rowan (@rowan-gray)

**Comment by rowan-gray** [comment]
Improved implementation and testing merged to main in this pull. https://github.com/UQcsse3200/2023-studio-2/pull/493

**Comment by rowan-gray** [comment]
Wiki page updated. All milestones are now complete 😄
