### ISSUE TITLE
Companion Powerup Inventory Refactor

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#498]
# **Description**
**Task:** Companion Powerup Inventory Refactor
**Feature:** #446 

This feature is refactoring how the powerup inventory will work.

The previous codebase of CompanionInventoryComponent uses a queue data structure and has legacy weapon code which has no relavence.

I will create a new component, CompanionPowerupInventoryComponent, which is just concerning the powerups in the inventory. It will use a hashmap and have safe operations performed so that the inventory state is always correct.

Then, disable the old inventory component, since it will not be in use.

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct 7 - 9 ) NA
- [x] Step 2 (Oct 10-11) Create new component which contains a hashmap of the powerup inventory
- [x] Step 3 (Oct 12) Polish off new component with safe addition/subtraction operation, and delete reference to old inventory component

**Completion Deadline:** Oct. 12
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
- Maxwell Schroder (@MaxwellSchroder)
