### ISSUE TITLE
Companion Powerup Activator UI

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#499]
# **Description**
**Task:** Companion Inventory UI Update
**Feature:** #446 

There will be a new button on the right hand side of the screen which will act as the ACTIVATOR for powerups. There will be a button to toggle between the powerups which are currently in the inventory.

When you click on the main button, it will activate that powerup and remove it from the inventory.

There will be left and right buttons next to the activator to toggle between the powerup types currently contained within the inventory.

**example**
Normal game

Click inventory button, inventory UI open

Companion or player walks across powerup -> it adds the powerup to the inventory

Inventory UI is updated to include the recent powerup addition in the counts

Inventory activation UI is updated to include the recent powerup addition

If the mouse clicks on the activation button with the current powerup, it activates that powerup and removes 1 powerup of that type from the inventory.

If the inventory becomes empty, it shows no powerups to be activated.

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1, Create a new UI component which will act as the powerup activator
- [x] Step 2, Make sure the UI component only shows powerups which are actually in the inventory, and when it clicks it activates it.
- [x] Step 3, Make sure the activation of the powerups is changing UI correctly e.g. removes it from inventory count, activates it, and calls an updated UI

**Completion Deadline:** Oct. 16
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
- Maxwell Schroder (@MaxwellSchroder)
- Saakshi Gupta (saakshigupta2002) (@saakshigupta)
