### ISSUE TITLE
Space - Implement game state management class

### ISSUE THREAD

**Issue by TDay1** [UQcsse3200/2023-studio-2#5]
# **Description**
**Task:** Global State Management.
**Feature:** [Space Feature](#3)

Develop the global state management system to manage all state in the game. This task involves creating a data structure to store planet information, updating the state based on player actions, and ensuring data synchronization.

## **Example (optional)**
- **Part**: When players collect resources on a planet, the global state management system should accurately update the resource count for that planet.

# **Dependencies**
- [x] Inter-Planetary Travel mechanism must be implemented (#10 ).

# **Milestones**
- [x] Design the global state data structure and update the documentation (Aug. 19).
- [x] Set up the data structure to store planet attributes (Aug. 20).
- [x] Implement mechanisms to update the global state based on player actions (Aug. 23).
- [x] Test global state updates and data synchronization (Aug. 23).

**Completion Deadline:** Aug. 23

# Pull Request
* #61 

# Documentation
* https://github.com/UQcsse3200/2023-studio-2/wiki/Storing-Game-State
* https://uqcsse3200.github.io/2023-studio-2/com/csse3200/game/services/GameState.html
# **Member**
- Thomas Day (TDay1)

**Comment by TDay1** [comment]
PR Merged completed, approved, and merged: https://github.com/UQcsse3200/2023-studio-2/pull/61
