### ISSUE TITLE
Extractor mechanics

### ISSUE THREAD

**Issue by AnshulDadhwal** [UQcsse3200/2023-studio-2#50]
# **Description**
**Task:** Implementing main structure of Extractor minigame code.
**Feature:** Extractor Repair Mini Game Feature (#37)

An extractor minigame featuring a whack-a-mole game that will pop up in the game when interacted with by the player. The minigame will overlay the main game itself (Similar to that in Among Us crewmate tasks). The game is time-based with problems popping up on the extractor machines and the player must use their reflexes to click on as many pop-ups as possible in the short time duration.
 
# **Dependencies**
This ticket's implementation of the extractor team for the minigame feature.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Working on pop-up window for the minigame (Aug. 21)
- [x] Completion of basic extractor minigame (Aug. 25)
- [x] Main structure of the code for the minigame (Aug. 27)
- [ ] JUnit Tests (Aug. 30)
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- TBD

# **Member**
- Kenny (@JunxianHuang)
- Zhen Feng (@Foref)

**Comment by Foref** [comment]
Have not Integrated into Pop up window. Working pop up window done by @Minirobbo
