### ISSUE TITLE
Companion Shield Update

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#500]
# **Description**
**Task:** Companion Shield Update
**Feature:** #446 
This feature is updating how the shield works.

Currently, the shield is a weapon that has no effect on the entities around it.

We are going to add "area of effect" damage to enemies which come within a short range of the shield.

Therefore, the shield will only be activated when in defence mode. The shield will rotate in a circle around the companion, and it will deal a short range of area of effect damage to any enemies in a very close distance. This way, the companion is slightly protected by killing the closest enemies in defence mode.

**example**
Companion enters defence mode

Shield 'weapon' is spawned and rotates around the companion

Enemy comes close to companion and the shield

The shield deals area of effect damage, and eventually kills the enemy which is close to the companion

# **Dependencies**
NONE 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Oct 14-15), Put area of effect weapon code in the codebase, but it is attached to a long range weapon.
- [x] Step 2 (Oct 16-17) Update the components and effects of the current shield to include the area of effect damage
- [x] Step 3 (Oct 17-18) Make sure the enemies are being damaged when they come close to the shield, but the shield has no effect to enemies far away.

**Completion Deadline:** Oct. 18
 
# **Documentation**
- Main documentation : https://github.com/UQcsse3200/2023-studio-2/wiki/Companion
 
# **Member**
- Daksh Jain (Daksh2607) (@daksh_52443)
- Maxwell Schroder (@MaxwellSchroder)
