### ISSUE TITLE
Controls Screen Completion

### ISSUE THREAD

**Issue by YashMitttal** [UQcsse3200/2023-studio-2#505]
# **Description**
**Task:** Controls Screen Completion
**Feature:** Controls Screen Completion

Design and layout the controls screen by adding a map to the Screen. This task involves finalizing the controls screen and integrating all necessary details and interactions into it.

# **Dependencies**

- [x] Tutorial Map completion

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design and layout of the controls screen map. (Oct 19)
- [x] Design a controls screen image to be placed above the map. (Oct 12)

**Completion Deadline:** Oct 19

 
# **Documentation**
- [ControlScreen Class Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/ControlScreen-Class-Documentation)
 
# **Member**
- Yash Mittal (@YashMitttal} (s4823869)
- Dev Gupta (@DRG31) (xdrgx)
- Jival Kapoor (@JivalX) (s4824576)

**Comment by YashMitttal** [comment]
done
