### ISSUE TITLE
Dialogue Completion for the newly constructed story

### ISSUE THREAD

**Issue by YashMitttal** [UQcsse3200/2023-studio-2#507]
# **Description**
**Task:** Dialogue Completion
**Feature:** Dialogue Completion and Story Completion

Complete dialogues for the entire game to enhance storytelling and player engagement. Ensure that dialogues coordinate the game flow effectively.

# **Dependencies**
NA

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Completion of new story to make it totally sci-fi. (Sept 25)
- [x] Review and refinement of dialogues (Oct. 11)
- [x] Incorporation of NPC and companion to make them useful for every level. (Oct 11)
 
**Completion Deadline:** Oct 11
 
# **Documentation**
- [Complete Story](https://github.com/UQcsse3200/2023-studio-2/wiki/Complete-Story)
 
# **Member**
- Yash Mittal (@YashMitttal} (s4823869)

**Comment by YashMitttal** [comment]
Completed the dialogues, will implement after the title box refinement is done.
