### ISSUE TITLE
Title Box Enhancement

### ISSUE THREAD

**Issue by YashMitttal** [UQcsse3200/2023-studio-2#508]
# **Description**
**Task:** Title Box Enhancement
**Feature:** Title Box Enhancement

Enhance the design and functionality of the title box for better visual appeal and usability.

# **Dependencies**
NA
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Integration of enhanced visual elements and improved usability within the title box (Oct. 19)
- [x] Adding letter-by-letter text animations. (Oct 19)
- [x] Installing TypingLabel library capabilities to TitleBox and DialogueBox classes. (Oct 19)
 
**Completion Deadline:** Oct 19

# **Documentation**
- [Modified TitleBox Class](https://github.com/UQcsse3200/2023-studio-2/wiki/Modified-TitleBox-Class)
 
# **Member**
- Yash Mittal (@YashMitttal} (s4823869)
- Dev Gupta (@DRG31) (xdrgx)

**Comment by YashMitttal** [comment]
done and added to game

**Comment by rachitchaurasia** [comment]
Updated the documentation
