### ISSUE TITLE
Space obstacle minigame - Map and spaceship movement

### ISSUE THREAD

**Issue by AnshulDadhwal** [UQcsse3200/2023-studio-2#51]
# **Description**
**Task:** Implementing the map and spaceship mechanics of the space obstacle minigame
**Feature:** Space Obstacle Course Minigame Feature (#8)

The task involves implementing the map on which the spaceship will move and figuring out the implementation of the spaceship in the minigame.

# **Dependencies**
To be decided based on the requirements of the other teams - Most likely the map and space feature team as they will be using this game for transitions based on the document provided by Design Committee.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Main structure of the map (Aug. 21)
- [x] #77
- [x] Spaceship movements (Aug. 24)
- [x] Adjust camera movements (Aug. 26)
- [ ] JUnit Tests (Aug. 28)
 
**Completion Deadline:** Aug. 28

# **Documentation**
- TBD
 
# **Member**
- Arsh Upadhyaya (@mr-popo123)
- Manpreet Singh (@Manpreetingh)
