### ISSUE TITLE
Upgrade Tree - Save/Load

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#513]
# **Description**
**Task:** Upgrade Tree - Save/Load
**Feature:** [Polished Player](https://github.com/UQcsse3200/2023-studio-2/issues/458)

The aim of this task is to integrate saving and loading with the Upgrade Tree. This will enhance the user experience by allowing them to keep all their hard-earned weapon and tool upgrades when they reload the game. 
As unlocks are stored inside `UpgradeTree` which is attached to the Player Entity, the `PlayerConfig` will be updated to store unlocked items - as per the requirements of the [SavableComponent](https://github.com/UQcsse3200/2023-studio-2/wiki/Saveable-Component). The `UpgradeTree` class will then utilise this `PlayerConfig` to suit.
 

# **Dependencies**

- [x] #490 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] `UpgradeTree` updated to take `PlayerConfig` as input. (Oct. 17).
- [x] Method to store unlocks added to `PlayerConfig`. (Oct. 17)
- [x] `UpgradeTreeTest` class updated to suit. (Oct. 17)
- [x] List of unlocks integrated with save component via `PlayerFactory`. (Oct. 17)
 
**Completion Deadline:** Oct. 17

# **Documentation**
- [Upgrade Tree](https://github.com/UQcsse3200/2023-studio-2/wiki/Upgrade-Tree)
 
# **Member**
- Connor (@connor-golin)
- Isaac (@Minirobbo)

**Comment by connor-golin** [comment]
Completed: https://github.com/UQcsse3200/2023-studio-2/pull/504
