### ISSUE TITLE
Improvement: Add max range for structure tools.

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#516]
# **Description**
The purpose of this task is to improve the structure functionality by implementing a customisable max range for each structure tool. This will improve the gameplay experience by making it, so the player has to move around the map to place and remove structures which will result in more dynamic gameplay.

An example of why this improvement is necessary is the ExtractorTool. Currently the player is able to play and extractor from any distance as long as there is a fissure to place it on. This makes it far too easy to place all the extractors immediately upon spawning into the level and removes the difficulty in fighting your way through the enemies to be able to place an extractor and begin extracting resources.

# **Dependencies**
The structure tools which have already been implemented.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add range to Tool and make it so the tool cannot be used outside of its range.
- [x] Add a range parameter to the ToolConfig to allow the range to be set for each tool.
- [x] Update ToolTest to test new functionality.
- [x] Add a max range for picking up structures.
- [x] Update Tool documentation.
 
**Completion Deadline:** Oct. 18
 
# **Documentation**
 
# **Member**
- Rowan (@rowan-gray)

**Comment by rowan-gray** [comment]
Added range to the Tool class and ToolConfig in commit c644bcc8eee6ed75e060dd06e06dfd62a101b2c4.

**Comment by rowan-gray** [comment]
Testing updated in commit d96bb10549990637691e7a2d107d795a426dc8df.

**Comment by rowan-gray** [comment]
Completed
