### ISSUE TITLE
Converting Boss Tasks to Components, Removing redundant ChaseTasks from Boss Attacks

### ISSUE THREAD

**Issue by Thoemodachi** [UQcsse3200/2023-studio-2#518]
# **Description**
Previously, Boss attacks were created on the base code for Task classes, which holds priority values and switches between tasks. However, every boss attack created was built upon the ChaseTask, and had redundant copies of the ChaseTask in every class. To remove the redundancies, and also to implement Sprint 3's A* Pathfinding, every attack will be converted to Component classes, and Enemy Movement and Attacks would become independent.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Convert SpecialAttackTask.java to RingBurstComponent.java (Oct. 17)
- [x] Convert SprayTask.java to SprayComponent.java (Oct. 17)
- [x] Convert SpawnAttackTask.java to SummonerComponent.java(Oct. 18)
- [x] JUnit Tests and Test Plan (Oct. 18)

**Completion Deadline:** Oct. 19
 
# **Member**
- Theodore Kim (@Thoemodachi) (thoemodachi)
- Milo Hunter (@mhUnt3rS) (iavfjbdb#8394)
