### ISSUE TITLE
Space obstacle minigame - Map design

### ISSUE THREAD

**Issue by AnshulDadhwal** [UQcsse3200/2023-studio-2#52]
# **Description**
**Task:** Implementing the map design which includes enemies and obstacle generation of the space obstacle minigame
**Feature:** Space Obstacle Course Minigame Feature (#8)

The task involves implementing the creation of entities like enemies and obstacles on the map for the space obstacle minigame. This involves implementing a hitbox for every entity. The task is also to ensure that there is a goal/endpoint/end goal/finish line.
 
# **Dependencies**
Dependent on the task ticket assigned to Arsh and Manpreet. (#51)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Asset acquisition for the enemies and the obstacles of the game (Aug. 20)
- [x] Implementing the main structure of the main entities (Aug. 22)
- [x] Adding hitboxes to the spaceship, enemies, and obstacles (Aug. 24)
- [x] Completion of the first map design that we want for the map (Aug. 27)
- [ ] JUnit testing (Aug. 30)
 
**Completion Deadline:** Aug. 30

# **Documentation**
- TBD
 
# **Member**
- Anshul Dadhwal (@AnshulDadhwal)
- Zhen Feng (@Foref)

**Comment by Foref** [comment]
Basic Design Done
