### ISSUE TITLE
Inventory - Save/Load

### ISSUE THREAD

**Issue by connor-golin** [UQcsse3200/2023-studio-2#528]
# **Description**
**Task:** [Inventory - Save/Load]().

The aim of this task is to integrate saving and loading with the Player's Inventory. This will enhance the user experience by allowing them to keep their favorite weapons equipped when they exit and reload the game - rather than having to switch to them again.
The `InventoryComponent` is attached to the Player Entity, therefore the `PlayerConfig` will be updated to store a map of the currently equipped weapons - as per the requirements of the [SavableComponent](https://github.com/UQcsse3200/2023-studio-2/wiki/Saveable-Component). The `InventoryComponent` class will then be updated to utilise this `PlayerConfig`.
 
# **Dependencies**

- [x] #490 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] `InventoryComponent` updated to take `PlayerConfig` as input. (Oct. 18).
- [x] Method to store equipped items added to `PlayerConfig`. (Oct. 18).
- [x] `InventoryComponent` class updated to suit. (Oct. 18).
- [x] List of unlocks integrated with save component via `PlayerFactory`. (Oct. 18).
 
**Completion Deadline:** Oct. 18

# **Documentation**
- [Player Inventory](https://github.com/UQcsse3200/2023-studio-2/wiki/Player-Inventory)
 
# **Member**
- Connor (@connor-golin)
