### ISSUE TITLE
Story outline of planet 1 and resource collection mechanics

### ISSUE THREAD

**Issue by DRG31** [UQcsse3200/2023-studio-2#53]
# **Description**
**Task:** Planet 1 Environment detail and NPCs implementation (#53).
**Feature:** Story (#53)

## **Example**
- **Resource Collection**: Players can gather different resources for upgradation for inventory. Upgraded resources can be used to repair space craft and survival of player and companions.
 
# **Milestones**
- [x] Create Story outline, Planet 1 Environment
- [x] Change the UI (font and button styles) according to the game requirements
- [x] Create a Botanist NPC 
- [x] Design dialogue box structure to display with NPCs
 
**Completion Deadline:** Aug. 31

# **Documentation**
- [Story Outline](https://github.com/UQcsse3200/2023-studio-2/wiki/Story-Outline)
- [Botanist NPC Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/Botanist-NPC)
- [User Interface Change wiki](https://github.com/UQcsse3200/2023-studio-2/wiki/User-Interface-Skin-Configuration)
 
# **Member**
- Dev Gupta (@DRG31 ) (xdrgx)
- Rachit Chaurasia (@rachitchaurasia) (s4823870)
