### ISSUE TITLE
Adjustment of Enemy Stats and JUnits

### ISSUE THREAD

**Issue by Thoemodachi** [UQcsse3200/2023-studio-2#532]
# **Description**
Previously, Enemies were too strong for the player, and one enemy basic attack would make players unable to play the game due to the enhanced difficulty. The stats of each enemy will be modified so the game is not too difficult for the player, but also continue to provide an incentive to dodge enemy attacks.

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Changing Stats for Small enemies (Ranged and Melee) (Oct. 17)
- [x] Changing Boss Stats (Enemies using projectiles) (Oct. 17)
- [x] Changing Boss Stats (Melee Enemies) (Oct. 17)
- [x] JUnit Tests and Test Plan  (Oct. 18)
 
**Completion Deadline:** Oct. 19
 
# **Member**
- Trong Vuong (@samv26) (samv_v)
- Ojaswin Kohli (@OjaswinKohli) (ojaswinkohli)
- Aryaman Tiwari (@Aryamant21) (at007)
