### ISSUE TITLE
Damage Overtime in Certain Areas

### ISSUE THREAD

**Issue by SamarthDevVaish** [UQcsse3200/2023-studio-2#534]
# **Description**
Task: Follow up to environmental damage

# **Dependencies**
Cooperation with the Player team maybe be required

# **Milestones**
List of steps that need to be completed for this task.
- [x] Discuss with the relevant teams (Oct. 14)
- [x] Create a collaboration ticket if required (Oct. 15)
- [x] Implement classes relevant to cause damage (Oct. 16)
- [x] Implement custom layouts to maps (Oct. 17)
- [x] Testing and bugfixing (Oct. 18)
 
**Completion Deadline:** Oct. 18th

# **Member**
Mitchell Hall (@s4697858 ) (Mitchell Hall)
Jordan Singh (@rike568) (Jordan Singh)
