### ISSUE TITLE
Change Earth and Hell Maps

### ISSUE THREAD

**Issue by SamarthDevVaish** [UQcsse3200/2023-studio-2#535]
# **Description**
Task: Revise the two main maps

# **Dependencies**
Cooperation with the Story team maybe be required

# **Milestones**
List of steps that need to be completed for this task.
- [x] Discuss amongst teammates (Oct. 14)
- [x] Delete unnecessary stuff from earth map (Oct. 16)
- [x] Change hell map layout (Oct. 17)
- [x] Testing and bugfixing (Oct. 18)
 
**Completion Deadline:** Oct. 18th

# **Member**
Mitchell Hall (@s4697858 ) (Mitchell Hall)
Manvi Narang(@ManviNarang01) (Manvi Narang)
