### ISSUE TITLE
Maps Are Ready

### ISSUE THREAD

**Issue by SamarthDevVaish** [UQcsse3200/2023-studio-2#536]
# **Description**
**Task**: Maps are ready to be loaded without any bugs and are ready for gameplay

# **Dependencies**
Collaborating with all teams to check whether the maps are fine for gameplay. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Assign one team member on each map (Oct. 14)
- [x] Removing all unnecessary stuff (Oct. 15)
- [x] Checking for bugs (Oct. 17)
- [x] Testing all maps (Oct. 18)
 
**Completion Deadline:** Oct. 19
 
# **Member**
Jordan Singh (@rike568) (Jordan Singh)
Mitchell Hall (@s4697858 ) (Mitchell Hall)
Anshuman Misra (@Anshuman0157 ) (Anshuman Misra)
Samarth Dev Vaish (@SamarthDevVaish) (Samarth Dev Vaish)
Armando Liebenberg (@ArmandoLiebenberg ) (Armando Liebenberg)
Manvi Narang(@ManviNarang01) (Manvi Narang)
