### ISSUE TITLE
Revision for Ice Map

### ISSUE THREAD

**Issue by SamarthDevVaish** [UQcsse3200/2023-studio-2#539]
# **Description**
**Task**: Change pathing in Ice Map

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Assign new tile set to the ice map (Oct. 14)
- [x] Add new pathing to the map (Oct. 15)
- [x] Check for sliding on ice (Oct. 16)
- [x] Testing ice map (Oct. 17)
 
**Completion Deadline:** Oct. 17
 
# **Member**
Samarth Dev Vaish (@SamarthDevVaish) (Samarth Dev Vaish)
