### ISSUE TITLE
Game Introduction Story and dialogues

### ISSUE THREAD

**Issue by aniketgupta17** [UQcsse3200/2023-studio-2#54]
# *Description*
*Task:* Design and implement captivating introduction sequence (#54).
*Feature:* Introduction and initial progression (#54)

# *Milestones*
- [x] Storyboarding and script writing for the introduction 
- [x] Integrate the story introduction into the game as a Title Box.
- [x] Created comic assets to display the story.
- [x] Test and refine the introduction's pacing and impact
- [x] Design a modular dialogue system structure which is to implemented in the upcoming sprints.
 
*Completion Deadline:* Aug. 31

# *Documentation*
- [Story Screen Implementation documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/STORY-SCREEN-DOCUMENTATION)
- [Main Menu and Setting Menu Display](https://github.com/UQcsse3200/2023-studio-2/wiki/MAIN-MENU-AND-SETTING-MENU-DISPLAY-CHANGES)
- [TitleBox Implementation Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/TitleBox-Class-Documentation)
 
# *Member*
- Aniket Gupta (@aniketgupta17) (s4824063)
- Yash Mittal (@YashMitttal) (s4823869)

**Comment by YashMitttal** [comment]
All Done!
