### ISSUE TITLE
Player slowing down feature

### ISSUE THREAD

**Issue by SamarthDevVaish** [UQcsse3200/2023-studio-2#541]
# **Description**
**Task**: PLayer slows down if he steps into certain areas of the map

# **Dependencies**
Possible collaboration with the player team. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Select map areas (Oct. 14)
- [x] Check how slow we have to make the player (Oct. 15)
- [x] Checking for bugs while the player slows down (Oct. 16)
- [x] Testing the map (Oct. 17)
 
**Completion Deadline:** Oct. 18
 
# **Member**
Jordan Singh (@rike568) (Jordan Singh)
Mitchell Hall (@s4697858 ) (Mitchell Hall)
Anshuman Misra (@Anshuman0157 ) (Anshuman Misra)
