### ISSUE TITLE
Spawning enemies in secret area

### ISSUE THREAD

**Issue by SamarthDevVaish** [UQcsse3200/2023-studio-2#543]
# **Description**
**Task**: This task allows us to spawn enemies in the secret areas

# **Dependencies**
Collaborating with enemy team to check what enemy to spawn in the secret area and where. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Deciding if enemies have to be spawned or not in the secret area (Oct. 14)
- [x] Creating collaboration ticket if required (Oct. 15)
- [x] Confirming how many enemies have to be spawned (Oct. 17)
- [x] Testing secret areas with enemies (Oct. 18)
 
**Completion Deadline:** Oct. 19
 
# **Member**
Jordan Singh (@rike568) (Jordan Singh)
Anshuman Misra (@Anshuman0157 ) (Anshuman Misra)
Samarth Dev Vaish (@SamarthDevVaish) (Samarth Dev Vaish)
Manvi Narang(@ManviNarang01) (Manvi Narang)
