### ISSUE TITLE
 Damage Calculation for shield

### ISSUE THREAD

**Issue by Daksh2607** [UQcsse3200/2023-studio-2#546]
# **Description**
**Task:** Damage Calculation for shield .

Implement a logic for rotating the shield in defense mode. The shield should also calculate the damage dealt to enemies based on the distance between the companion and the enemies. The closer the enemies are to the shield, the more damage they should receive. This logic should include particle effects to enhance the visual representation of the shield's actions. The defense mode can be turned on by pressing the key C.

## **Example**
- **Damage Calculation**: The damage inflicted on enemies should be inversely proportional to the distance between the companion and the enemies.

# **Milestones**
- [x] Step 1: Calculate damage based on distance. Oct 16
- [x] Step 2: Integrate particle effects. Oct 17
- [x] Step 3: Test and fine-tune the shield behavior Oct 18

**Completion Deadline:** Oct. 18

# **Member**
- Developer: Daksh Jain (@Daksh2607)
