### ISSUE TITLE
Space Unit Testing + Logging

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#548]
# **Description**
**Task:** [Space Unit Testing + Logging](#548)
**Feature:** [Space Feature Finalisation](#552)

It is important to ensure comprehensive testing is conducted on components and features of the game, especially so when they provide integral functionality like the `PlanetScreen` and PlanetTravel classes, as such appropriately comprehensive tests must be written. Additionally, the logging of actions in the Space features is vital to easily understand and visualise the steps the game is taking at any given moment and what `GameState` data is being updated or the `PlanetScreen` is being displayed.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete PlanetScreen JUnit Tests (Oct. 18)
- [x] Complete PlanetTravel JUnit Tests (Oct. 18)
- [x] Write Testing Plan Documentation (Oct. 18) 
- [x] Write Logging for PlanetScreen (Oct. 15)
- [x] Write GameState Logging (Oct. 15) 
 
**Completion Deadline:** Oct. 18

 
# **Documentation**
- [PlanetScreen Testing Plan](https://github.com/UQcsse3200/2023-studio-2/wiki/PlanetScreen-Testing-Plan)
- [PlanetTravel Testing Plan](https://github.com/UQcsse3200/2023-studio-2/wiki/PlanetTravel-Testing-Plan)
 
# **Member**
- Henry Batt @henrybatt
