### ISSUE TITLE
Space Feature Finalisation

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#552]
# **Description**
This sprint is all about polishing and finalising the game and our team components. To do this we need to complete our JUnit testing, logging, code cleanup, and ensuring our components are as reusable and appropriately documented as possible.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Refactor Star Background for modularity and ensure utilised where appropriate (Oct. 13) (#456)
- [x] Update Space Map + Levels with new order as per story teams request (Oct. 16) (#476)
- [x] Finalise Logging of Space Code (Oct. 15) (#548)
- [x] Finish JUnit Testing (Oct. 18) (#548)

**Completion Deadline:** Oct. 18

# **Members**
- Henry Batt @henrybatt
- Thomas Day TDay1 tday1
