### ISSUE TITLE
Revise Hell Map

### ISSUE THREAD

**Issue by ManviNarang01** [UQcsse3200/2023-studio-2#559]
# **Description**
**Task**: Revise Hell Map

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Gather new Tilesets (Oct. 14)
- [x] Expand Map Area (Oct. 15)
- [x] Check for Different Layers for different Sprites on the Map (Oct. 16)
- [x] Testing Hell map (Oct. 17)
 
**Completion Deadline:** Oct. 17
 
# **Member**
Manvi Narang (@ManviNarang01) (Manvi Narang)
