### ISSUE TITLE
Companion Obstacle Detection and Avoidance 

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#56]
# **Description**
**Task:** Companion obstacle detection and avoidance (#)
**Feature:** Companion (#7 )

Implement hit boxes on the objects on the map and the companion. Make sure the movement of the companion takes into account the objects on the map. 
 
## **Example (optional)**
- **Tree on map**: If the companion is circling the player, it might cross the path of a tree on the map. It adjusts its movement to avoid the tree and not go over it.

# **Dependencies**
- [ ] Put companion on map (#38 )
- [ ] Get companion moving (#39 )
- [ ] Map setup (#33 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 -  Place an object on the map (Aug. 26)
- [ ] Step 2 - Create a minimum distance between the companion and all the objects on the map (Aug. 26)
- [ ] Step 3 - adjust movement algorithms to smoothly avoid the objects (Aug. 28)
- [ ] Step 4 - Create smart objects with 2 hit boxes. One hit box would be a finite bounds which the companion cannot cross. The second, larger hitbox is where some sort of effect will happen to the companion. For example, if companion walks through thorny patch, it will do some damage to companion health. (Aug. 29)
 
**Completion Deadline:** Aug. 29

 
# **Documentation**
- TBD
 
# **Member**
- Maxwell Schroder (@MaxwellSchroder)
- Atharav Gupta (@atharvagupta2003)
