### ISSUE TITLE
Companion Unit Tests

### ISSUE THREAD

**Issue by gaurikadiwan** [UQcsse3200/2023-studio-2#562]
# **Description**
**Task:** Unit Tests(#3).
**Feature:** Companion

Task ticket for Pending Test classes, implemented using Mockito. 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add Test Class For CompanionWeaponTargetController(15th Oct)
- [x] Add Test Class For CompanionPowerUpActivationDisplay(16th Oct)
- [x] Add Test Class For CompanionInventoryComponent(18thOct)
- [x] Add Test Class For CompanionPowerupActivationDisplay(18th Oct)
- [x] Add Test Class For CompanionDeathScreenDisplay(12th Oct)
- [x] Add Test Class For CompanionDeathScreenActions(12th Oct)
 
**Completion Deadline:** Oct 20

 
# **Documentation**

- https://github.com/UQcsse3200/2023-studio-2/wiki/Test-Plan-for-CompanionPowerupActivationDisplay
- https://github.com/UQcsse3200/2023-studio-2/wiki/Test-Plan-For-CompanionWeaponComponent
- https://github.com/UQcsse3200/2023-studio-2/wiki/Companion-Inventory-Test-plan

 
# **Member**
- Gaurika Diwan (@gaurikadiwan )(@gaurikadiwan_03168)
