### ISSUE TITLE
Game testing 

### ISSUE THREAD

**Issue by JivalX** [UQcsse3200/2023-studio-2#563]
# **Description**
**Task:** Create Extensive Test Classes and Test Plans
**Feature:**  Create Extensive Test Classes and Test Plans 

This task involves the creation of comprehensive test classes and corresponding test plans to ensure the robustness and reliability of the game. Detailed test cases will be designed and implemented to validate various game components, interactions, and functionalities.

## **Dependencies**
- None

# **Milestones**
List of steps that need to be completed for this task-
- [x] Develop test classes for game components.
- [x] Fix the existing test classes to accommodate changes to their classes.
- [x] Create detailed test plans for various scenarios and edge classes.

**Completion Deadline:** [Oct 18]

# **Documentation**
- [Test Plan for asset loading](https://github.com/UQcsse3200/2023-studio-2/wiki/Test-Plan-For-Asset-Loading)
- [BotanistanimationController Test Plan](https://github.com/UQcsse3200/2023-studio-2/wiki/Test-Plan:-BotanistAnimationController-Class)
- [TutnpcAnimationController Test Plan](https://github.com/UQcsse3200/2023-studio-2/wiki/Test-plan-For-TutNpc-Animation-Controller)

# **Member**
- Jival Kapoor (@JivalX) (s4824576)
- Aniket Gupta (@aniketgupta17) (s4824063)

**Comment by YashMitttal** [comment]
done
