### ISSUE TITLE
Spawner Component Refactoring, Target Component for Destructible Targetting Enemies

### ISSUE THREAD

**Issue by Thoemodachi** [UQcsse3200/2023-studio-2#564]
# **Description**
The Spawner Component and Enemy Factory are refactored to identify enemies based on their nicknames rather than a combination of enemy types, as of Sprint 3. The Target Component for DTE enemies was implemented so they could retarget extractors and turrets when they get placed or destroyed.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Spawner Refactored (Oct. 17)
- [x] Apply TargetComponent (Oct. 17)
- [x] JUnit Tests (Oct. 18)

**Completion Deadline:** Oct. 19
 
# **Member**
- Kintaro Kawai (@kk4w4i) (0xkin)
