### ISSUE TITLE
Modifying necromancer functionality

### ISSUE THREAD

**Issue by mhUnt3rS** [UQcsse3200/2023-studio-2#573]
# **Description**
Modify The necromancer enemy type and SpawnAttackTask so that the entity interacts with the players and spawn entities appropriately. Currently the necromancer enemy does not use the SpawnAttackTask and is given the same tasks as a regular ranged entity. SpawnAttackTask/SpawnTask also have bugs which stop the owner entity from spawning/moving and spawns enemies outside of game area
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Adjust enemy factory so necromancer is given correct functionality (Oct. 18)
- [x] Adjust SpawnTask logic so enemies are not spawned out of game area (Oct. 18)
- [x] Adjust SpawnAttackTask logic to ensure it starts and stops appropriately.  (Oct. 18)
- [x] Additional JUnit Tests for SpawnAttackTask (Oct. 19)

**Completion Deadline:** Oct. 19
# **Member**
- Milo Hunter (@mhUnt3rS ) (iavfjbdb)
