### ISSUE TITLE
Companion Path

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#58]
# **Description**
**Task:** [Companion direction].
**Feature:** [Companion sprint 1] (#7 )

Adding a basic mechanic to the companion that will allow for game mechanics between other enemies and entities later on in the game. Added Bullet Texture path. 

# **Dependencies**
-[] Companion initialisation on map (#38) 
-[] companion movement (#39 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 - Derive the direction of the companion based off movement (Aug. 26)
- [x] Step2 - Impose Bullet Texture path.
- [x] objects in that area (Aug 28)
 
**Completion Deadline:** Aug 31.

 
# **Documentation**
- [Basic Player Tracking](https://github.com/UQcsse3200/2023-studio-2/wiki/Basic-Player-Tracking-Feature)
 
# **Member**
- Gaurika Diwan(gaurikadiwan)(@gaurikadiwan_03168)
