### ISSUE TITLE
Companion Alerts and Pop-ups

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#59]
# **Description**
**Task:** [Companion Alerts and Pop-ups].
**Feature:** [Companion first features](#7 )

Implement the companion pop up alerts. Should initially display default text on screen, and not covering the companion. Furthermore, the pop up will be initially triggered by a timer. Furthermore, the pop-up text should change to displaying useful in game state or information, such as low player or extractor health.
 
## **Example (optional)**
- **Low Player Health**: If player gets to critically low health, the companion will display text on screen showing this

# **Dependencies**
- [ ] Dependency 1 - Initialise companion on screen (#7 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 - Get a box with text appearing on screen  at regular intervals of a timer (Aug. 25)
- [ ] Step 2 - Create observers to analyse useful game state information, such as player health and extractor health (Aug. 28)
- [ ] Step 3 - Display useful game state information on pop up boxes (Aug. 29) 
- [ ] Step 4 - Adjust state information to be more relevant for companion (Aug 31)
**Completion Deadline:** Aug. 31

# **Documentation**
- TBD
 
# **Member**
- Saakshi Gupta (saakshigupta2002) (@saakshigupta)
- Daksh Jain (Daksh2607) (@daksh_52443)
- Maxwell Schroder (Magwello) (@MaxwellSchroder)
