### ISSUE TITLE
Simplify GameState class' interface.

### ISSUE THREAD

**Issue by TDay1** [UQcsse3200/2023-studio-2#68]
# **Description**
**Task:** Simplify GameState class' interface.
**Feature:** [Game State Management Feature](#3).

Rework the interface of the GameState class to be more developer friendly. Specifically, the new interface should implement "set" and "put" method to mimic the behavior of a simple hashmap.

## **Example (optional)**
- **Part**: For instance, an entity might need to fetch its current score from the game state. With the previous setup, it would fetch a cloned state data, which can be costly if done frequently. With the new approach, it can directly fetch its data using `get` method, which is quicker and thread-safe. 

# **Dependencies**
- [ ] The original `GameState` structure needs to be implemented with proper synchronization (#5).

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design the refactored `GameState` class structure and document it on the wiki (Aug. 25).
- [ ] Implement the `get` and `put` methods in `GameState` class (Aug. 25).
- [ ] Unit test the methods of the `GameState` class (Aug. 25).
- [ ] Integrate the `GameState` class with the `ServiceLocator` class (Aug. 25).
- [ ] Document the `GameState` use cases on wiki (Aug. 25).
 
**Completion Deadline:** Aug. 25
