### ISSUE TITLE
Initial Companion Features

### ISSUE THREAD

**Issue by MaxwellSchroder** [UQcsse3200/2023-studio-2#7]
# **Description**
Design a simple skin/costume for the companion in the first version. This is essential. Place the companion-object/avatar onto the game screen. This is essential. Implement very basic user tracking, where the companion follows the main character around, but maintains a minimum distance. It won't have any object/zone detection, and will just track the player. Lastly, we will implement alerts. Alerts are defined as text popped up on screen, which will initially be default text, but improved to show useful information such as player health, extractor health, etc.

## SubFeature/component (optional)
Alerts would be the main sub features. The first three features outlined above are critical for the first sprint to be successful.

# **Dependencies**
1. Player. We depend on the player for location/health/other information to follow. The companion must follow the player, and thus the player must already exist and be placed onto the screen.
2. Map. There must be a screen/map for us to place the companion on.
3. Extractor. We depend on the extractor team for the information to pop up on screen.

e.g. explain (#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Tuesday Aug. 15) - Finish downloading/creating an asset to be used as the visual component of the skin/avatar.
- [ ] Goal 2 (Thursday Aug. 17) - Companion avatar is placed on the screen at an arbitrary location.
- [ ] Goal 3 (Monday Aug. 21) - Companion is moving around a particular point with a minimum distance. (MUST WAIT FOR PLAYER LOCATION BEFORE CENTERING AROUND PLAYER)
- [ ] Goal 4 (Thursday Aug. 24) - Companion is centred around player. Companion pops up text alerts of any random text. Change to pop up useful information from other teams, such as player health, extractor health, etc if the other components are finished.

**Completion Deadline:** Friday Aug. 25

# **Documentation**
- 
- 

# **Members**
- Name (GitHub Username) (Discord Handle) -- only one is needed if they are the same.
- Maxwell (MaxwellSchroder) (@Magwell)
- Saakshi Gupta (saakshigupta2002) (@saakshigupta)
- Atharva Gupta (atharvagupta2003) (@atharva0179)
- Daksh Jain (Daksh2607) (@daksh_52443)
- Raghavendra Singh Gulia (RagGul)(tantrik8119)
- Gaurika Diwan(gaurikadiwan)(@gaurikadiwan_03168)
