### ISSUE TITLE
Building Placement Handlers

### ISSUE THREAD

**Issue by mira-alford** [UQcsse3200/2023-studio-2#71]
# **Description**
**Task:** [Building Placement Handlers](#).
**Feature:** [Walls & Gates](#6) and [Extractors](#22) 

Implement handlers on the game map that allow placement of structures with option for rejection by map, useful for many teams.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement a registration function 25 August
- [x] Implement handler to instantiate extractors when called 25 August
- [x] Implement generic handler to add any entity to the current game area (26 Aug)

 
# **Documentation**
- [Main description of feature](../wiki/Building-Placement)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- McArthur (@McArthur-Alford) (McArthur)
- Rowan (@rowan-gray) (Rowan)
