### ISSUE TITLE
Keyboard Interact Component Collaboration

### ISSUE THREAD

**Issue by Minirobbo** [UQcsse3200/2023-studio-2#72]
# **Description**
**Feature:** #26 #13 

A component that can be added to entities that runs a particular function on a given key press. The key and function will be flexible.

# **Milestones**
- [x] Implementation of interaction component
- [x] Link keyboard input to trigger player interactions
- [x] Complete Unit tests for interaction component
- [x] Complete documentation for interaction component

# **Documentation**
- [Interaction and Interactable Components Documentation](https://github.com/UQcsse3200/2023-studio-2/wiki/Entity-Interactions)
 
# **Member**
- Name (GitHub Username) (Discord Handle)
- Isaac @Minirobbo Minirobbo
- Connor @connor-golin

**Comment by Minirobbo** [comment]
Scope of component slightly changed - Now the `InteractionControllerComponent` has an `interact()` call that is triggered for the player by a keypress. This can be added to any entity to enable interaction with objects.
