### ISSUE TITLE
Health Bar

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#76]
# **Description**
**Task:** [Health Bar](#76).
**Feature:** [Enemies](#46) & [Walls & Gates](#6)

Implement a DisplayEntityHealthComponent which will display a health bar for the entity it is added to. The health bar will only display if the entity it is added to also has a CombatStatsComponent.

This will be useful for the buildables feature and the enemies feature to display the current health of the entity.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create UI element (Aug. 24)
- [x] Position UI element on top of entity (Aug. 24)
- [x] Follows entity (Aug. 25)
- [x] Listens for a change in health (Aug. 25)
 
# **Documentation**
[Health Bar Component](../wiki/health-bar-component)

**Completion Deadline:** Aug. 26

**Comment by rowan-gray** [comment]
Implemented in pull request #73
