### ISSUE TITLE
Space Obstacle Course Minigame Feature

### ISSUE THREAD

**Issue by AnshulDadhwal** [UQcsse3200/2023-studio-2#8]
# **Description**
This feature seeks to implement a minigame based on asteroid shooting where the player is expected to go a certain distance in an obstacle course that will be included in the map for increasing the engagement of the player in the main game. (Similar to a top-down shooter - Bullet Hell)

## SubFeature/component
1. Ship Movement
2. Obstacle Generation
3. Progress Bar (Time-based survival method)
4. Map Generation (2D Plane)
5. Shooting Ability (Optional)
6. Ship Health (3 Time Hit Death)
7. End Goal: Reach the destination to unlock a new map in the main game.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Basic layout of the map (Aug. 17)
- [x] Movement of Ship (Aug. 19)
- [x] Progress Bar (Success conditions - Test if in an empty map, the game could be completed with the ship moving in an empty space) (Aug. 21)
- [x] Obstacle Generation (Aug. 23)
- [x] Ship Health (Game Over conditions) (Aug. 27)
- [x] JUnit Tests (Aug. 17 - Aug. 30)
- [x] Shooting Ability (Optional) (Aug. 29)

**Completion Deadline:** Aug. 30

# **Documentation**
- To be fixed

# **Members**
- Anshul Dadhwal (@AnshulDadhwal)
- Zhen Feng Ting (@Foref)
- Manpreet Singh (@Manpreetingh)
- Arsh Upadhyaya (@mr-popo123)
- Junxian Huang (@JunxianHuang)
