### ISSUE TITLE
Sprites and Background for interplanetary minigame

### ISSUE THREAD

**Issue by neil-nb** [UQcsse3200/2023-studio-2#80]
# **Description**
**Task:** [Sprites and Background for interplanetary minigame](#3).
**Feature:** [Space obstacle minigame - Map design](#52)

Implementing the sprite of the ship used in the interplanetary asteroid avoidance minigame, in addition to the implementation of a custom background chosen by the minigame team. This could also potentially include different backgrounds for different instances of the game being played between the different planets.
 
## **Example**
- **Between Earth and planet 2**: A sea of beautiful nebulae behind the player as they avoid the inbound asteroids 
- **Between planet 2 and planet 3**: A black hole behind the player, seemingly about to suck it up as they avoid the inbound asteroids 
- **Between planet 3 and planet 4**: A vast galaxy behind the player as they arrive at their newfound home
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finding image(s) to use as a background (Aug. 28)
- [x] Integrating at least one image as a background (Aug. 28)
- [x] Changing ship sprite to the primary version (Aug. 29)
 
**Completion Deadline:** Sept. 1
 
# **Documentation**
- TBD
 
# **Member**
- Neil (@neil-nb)
- Zhen Feng (@Foref)
