### ISSUE TITLE
GameStateObserver + GameStateInteraction JUnit Testing

### ISSUE THREAD

**Issue by henrybatt** [UQcsse3200/2023-studio-2#81]
# **Description**
**Task:** [GameStateObserver + GameStateInteraction JUnit Testing].
**Feature:** [Game State Management Feature](#3)

Write JUnit testing for the `GameStateOberver` and `GameStateInteraction` classes to ensure they work as intended.
 

# **Dependencies**
- [x] The State Interaction Helper classes need to be written for testing. (#12 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write tests in `ServiceLocatorTest` to ensure `GameStateObserver` registers. (Aug. 30)
- [x] Write `GameStateObserver` tests that cover all functionality. (Aug. 31)
- [x] Write `GameStateInteraction` tests that cover all functionality. (Aug. 31)
**Completion Deadline:** Aug. 31
 
# **Member**
- Henry Batt @henrybatt
