### ISSUE TITLE
Wall/Gate Sprites

### ISSUE THREAD

**Issue by rowan-gray** [UQcsse3200/2023-studio-2#9]
# **Description**
**Task:** [Wall/Gate Sprites](#9).
**Feature:** [Barricades/Walls](#6 )

Find/create a set of sprites to use for walls and gates within the game. The sprites should allow for the future addition of adjacent walls being visibly connected (via a sprite change).
 
# **Dependencies**
- [x] Decision on art style.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find/create wall sprites (Aug. 19)
- [x] Find/create gate sprites (opened and closed variants) (Aug. 20)
- [x] Add sprites to assets folder (Aug. 21)
 
**Completion Deadline:** Aug. 23
 
# **Member**
- Raghav (@NotRaghavAggarwal ) (Raghav Aggarwal)

**Comment by NotRaghavAggarwal** [comment]
Added Wall and Gate Sprites
